wireapp/wire-web-packages

- packages/proteus/libsodium.d.ts
- packages/proteus/src/demo/demo.html
- packages/proteus/src/demo/demo.js
- packages/proteus/src/proteus/derived/CipherKey.ts
- packages/proteus/src/proteus/derived/MacKey.ts
- packages/proteus/src/proteus/keys/KeyPair.ts
- packages/proteus/src/proteus/keys/PreKeyBundle.ts
- packages/proteus/src/proteus/keys/SecretKey.ts
- packages/proteus/src/proteus/util/KeyDerivationUtil.ts
- packages/proteus/src/proteus/util/MemoryUtil.ts
Updated from [libsodium-types-generator](https://github.com/ffflorian/libsodium-type-generator) [v1.0.8](https://github.com/ffflorian/libsodium-type-generator/releases/tag/v1.0.8).
> chore(proteus): Update libsodium types

- packages/cryptobox/src/demo/demo.html
- packages/cryptobox/src/demo/demo.js
- packages/proteus/bower.json
- packages/proteus/libsodium.d.ts
- packages/proteus/src/demo/demo.html
- packages/proteus/src/demo/demo.js
libsodium typings taken from [libsodium-type-generator](https://github.com/ffflorian/libsodium-type-generator) [v1.0.10](https://github.com/ffflorian/libsodium-type-generator/releases/tag/v1.0.10).
> chore(proteus,cryptobox): Update libsodium in browser + update typings

- packages/store-engine/package.json
- packages/store-engine/webpack.config.test.js
> test(store-engine): Run browser tests with bundled Dexie

- packages/travis-bot/package.json
Closes https://github.com/wireapp/wire-web-packages/pull/389.
> chore(travis-bot): Update core to latest version

- packages/react-ui-kit/demo/Demo.jsx
- packages/react-ui-kit/src/Form/Checkbox.jsx
> fix: Checkmark inside the checkbox (WEBAPP-4905)

- packages/api-client/package.json
- packages/cbor/package.json
- packages/commons/package.json
- packages/core/package.json
- packages/cryptobox/package.json
- packages/lru-cache/package.json
- packages/priority-queue/package.json
- packages/proteus/package.json
- packages/react-ui-kit/package.json
- packages/store-engine/package.json
Closes https://github.com/wireapp/wire-web-packages/pull/615.
> chore: Update webpack-cli to 2.1.4

- packages/react-ui-kit/demo/Demo.jsx
Check the preview here: https://deploy-preview-739--wire-react-ui-kit.netlify.com/
> chore(react-ui-kit): Better demo for the colors

- packages/react-ui-kit/src/Layout/StyledApp.jsx
/cc @olivereitalu 
For the default `<p>` it was `24px` and becomes now `28px`..
> chore(react-ui-kit): Change the default line-height

- packages/core/src/demo/echo.js
> fix(core): MessageTimer in Demo, disable markdown

- packages/react-ui-kit/src/Layout/Column.jsx
That broke the web!
https://deploy-preview-848--wire-react-ui-kit.netlify.com/
> fix(react-ui-kit): Revert remove flex-basis of columns

- packages/react-ui-kit/demo/Demo.jsx
- packages/react-ui-kit/src/Text/Text.jsx
Will be used for showing the price (https://wire.com/pricing/)
> feat(react-ui-kit): Large text

- packages/core/src/main/Account.ts
> refactor(core): Reduce amount of return types for "decodeGenericMessage"

- packages/react-ui-kit/src/Layout/HeaderMenu.jsx
> fix(react-ui-kit): Padding in header menu when opened

- packages/react-ui-kit/package.json
- yarn.lock
Reverts wireapp/wire-web-packages#935
> fix(deps): revert styled-components from 3.4.0 to 3.3.3

- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/changelog-bot/src/main/cli.ts
- packages/core/src/main/Account.ts
- packages/travis-bot/src/main/cli.ts
- packages/travis-bot/src/main/index.ts
- tslint.json
> chore: Enforce template expressions for TypeScript code

- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
> feat(core): Emit edited messages (WEBFOUND-18)

- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/PayloadBundle.ts
- packages/core/src/main/conversation/content/LocationContent.ts
> feat(core): Send and receive locations (WEBFOUND-21)

- packages/core/src/main/conversation/PayloadBundle.ts
This change has already been introduced in #926 and I don't know why it got lost. 🤔
> chore(core): Make conversation ID mandatory

- packages/core/src/demo/echo.js
- packages/core/src/demo/sender.js
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/PayloadBundle.ts
> feat(core): Send conversation clearing (WEBFOUND-23)

- packages/core/src/main/conversation/ConversationService.ts
> fix(core): Remove timer from conversation clearing

- packages/api-client/src/main/Client.ts
- packages/api-client/src/main/Config.ts
- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/cli-client/src/main/index.ts
- packages/core/src/demo/echo.js
- packages/core/src/demo/sender.js
- packages/core/src/demo/status-bot.js
- packages/core/src/main/Account.test.node.js
- packages/core/src/main/test/AccountHelper.js
- packages/travis-bot/src/main/index.ts
> refactor(api-client): Remove Config class

- packages/bot-api/package.json
- yarn.lock
~~- [ ] My code is covered by tests~~
~~- [ ] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes~~
> fix(bot-api): Upgrade dependencies

- packages/api-client/src/main/team/service/Service.ts
- packages/api-client/src/main/team/service/ServiceAPI.ts
- packages/api-client/src/main/team/service/ServiceWhitelistData.ts
- packages/api-client/src/main/team/service/Services.ts
- packages/api-client/src/main/team/service/index.ts
https://github.com/wireapp/wire-web-packages/issues/970
> feat(api-client): Service endpoints

- packages/core/src/main/conversation/ConversationService.ts
> feat(core): Archive conversations

- packages/core/src/main/Account.ts
> fix(core): Emit assets correctly (WEBFOUND-20)

- packages/core/src/main/client/ClientService.ts
> feat(core): Get clients

- packages/api-client/karma.conf.js
- packages/api-client/package.json
- packages/bazinga64/karma.conf.js
- packages/bazinga64/package.json
- packages/commons/karma.conf.js
- packages/commons/package.json
- packages/core/karma.conf.js
- packages/core/package.json
- packages/cryptobox/karma.conf.js
- packages/cryptobox/package.json
- packages/priority-queue/karma.conf.js
- packages/priority-queue/package.json
- packages/store-engine/karma.conf.js
- packages/store-engine/package.json
- yarn.lock
Inspired by: https://github.com/wireapp/wire-webapp/pull/4291
> feat: Print time elapsed for each test

- packages/commons/src/main/util/ArrayUtil.test.node.js
- packages/commons/src/main/util/ArrayUtil.ts
> feat(commons): Add array chunking

- packages/react-ui-kit/src/Layout/index.js
> chore(react-ui-kit): Expose WIDTH, STEP, GUTTER

- packages/api-client/src/main/auth/AuthenticationError.ts
- packages/api-client/src/main/auth/index.ts
- packages/api-client/src/main/http/BackendErrorMapper.ts
- packages/api-client/src/main/http/StatusCode.ts
> refactor(api-client): Enum and MissingCookieError

- .prettierignore
~~- [ ] My code is covered by tests~~
~~- [ ] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes~~
> feat: Let prettier ignore .travis.yml

- packages/bot-api/src/main/Bot.ts
- packages/core/src/main/Account.ts
This PR adds missing payload bundle types which were not handled and handles a connection request correctly.
> fix(core,bot-api): Handle missing payload bundle types

- packages/core/src/main/Account.ts
> fix(core): Emit edited messages (WEBFOUND-19)

- packages/commons/src/main/util/Runtime.ts
> refactor(commons): Export operating system families

- packages/core/src/main/Account.ts
> fix(core): Emit ping

- packages/core/src/main/Account.ts
> fix(core): Emit confirmation

- packages/core/src/demo/echo.js
> fix(core): Get correct reaction type

- packages/bot-api/package.json
- packages/bot-api/src/main/Bot.ts
- packages/bot-api/src/main/MessageHandler.test.node.js
- packages/bot-api/src/main/MessageHandler.ts
> feat(bot-api): Send image

- packages/api-client/src/main/asset/AssetAPI.ts
- packages/api-client/src/test/node/spec/asset/AssetAPI.test.js
- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/content/ConversationContent.ts
- packages/core/src/main/conversation/content/EditedTextContent.ts
- packages/core/src/main/conversation/content/LinkPreviewContent.ts
- packages/core/src/main/conversation/content/TextContent.ts
- packages/core/src/main/conversation/content/TweetContent.ts
- packages/core/src/main/conversation/content/index.ts
> feat(core,api-client): Send link previews (WEBFOUND-33)

- packages/react-ui-kit/src/Text/Paragraph.jsx
> fix(react-ui-kit): Font weight for Lead set to 300

- packages/api-client/index.js
- packages/api-client/src/main/Client.ts
- packages/api-client/src/main/auth/AccessTokenStore.ts
- packages/api-client/src/main/auth/AuthAPI.ts
- packages/api-client/src/main/http/HttpClient.ts
- packages/api-client/src/main/tcp/WebSocketClient.ts
- packages/api-client/src/test/node/spec/Client.test.js
- packages/api-client/src/test/node/spec/auth/AuthAPI.test.js
> test(api-client): Add cases for AuthAPI

- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService.ts
See [messages.proto#L107](https://github.com/wireapp/generic-message-proto/blob/master/proto/messages.proto#L107).
> fix(core): Get correct hidden message ID

- packages/bot-api/src/main/MessageHandler.ts
- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/cli-client/src/main/index.ts
- packages/core/src/demo/echo.js
- packages/core/src/demo/sender.js
- packages/core/src/demo/status-bot.js
- packages/core/src/main/Account.smoke-test.node.js
- packages/core/src/main/Account.test.node.js
- packages/core/src/main/conversation/ConversationService.test.node.js
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/PayloadBundle.ts
- packages/core/src/main/conversation/TextContentBuilder.ts
- packages/core/src/main/conversation/content/index.ts
- packages/travis-bot/src/main/index.ts
Old:
```ts
const textMessage = conversation.createText(text, linkPreviews, messageId);
```
New:
```ts
const textMessage = conversation.createText(text, messageId).withLinkPreviews(linkPreviews);
```
> refactor(core): Add TextContentBuilder [BREAKING]

- packages/core/package.json
- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService.test.node.js
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/TextContentBuilder.ts
- packages/core/src/main/conversation/content/ConversationContent.ts
- packages/core/src/main/conversation/content/MentionContent.ts
- packages/core/src/main/conversation/content/TextContent.ts
- packages/core/src/main/conversation/content/index.ts
- yarn.lock
Example:
```ts
const text = 'Hello @user!';
const mention = {
end: 11,
start: 6,
userId: '1234-5678-...',
};
const textMessage = conversation.createText(text).withMentions([mention]).build();
await conversation.send(textMessage);
```
> feat(core): Send and receive mentions

- packages/core/src/demo/echo.js
> fix(core): Connection request and location in demo

- packages/lru-cache/src/main/LRUCache.ts
- packages/lru-cache/test/specs/LRUCacheSpec.js
> feat(lru-cache): Implement deleteAll

- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/content/ClearedContent.ts
- packages/core/src/main/conversation/content/ConversationContent.ts
> feat(core): Emit "cleared" messages

- packages/core/src/main/Account.ts
Follow-up to https://github.com/wireapp/wire-web-packages/pull/1117.
> fix(core): Incoming mentions

- packages/core/src/main/conversation/ConversationService.ts
> feat(core): Mute and unmute conversations (WEBFOUND-39)

- packages/lru-cache/src/main/LRUCache.ts
~~- [ ] My code is covered by tests~~
> refactor(lru-cache): Re-use NodeMap

- packages/lru-cache/package.json
- packages/lru-cache/src/main/LRUCache.ts
- packages/lru-cache/test/specs/LRUCacheSpec.js
> fix(lru-cache): Use generator for iteration

- packages/api-client/src/main/auth/RegisterData.ts
- packages/api-client/src/main/team/payment/Currency.ts
- packages/api-client/src/main/team/payment/InvoiceData.ts
- packages/api-client/src/main/team/payment/PaymentStripeCharge.ts
- packages/api-client/src/main/team/payment/PaymentStripePlan.ts
- packages/api-client/src/main/team/payment/SupportedCurrency.ts
- packages/api-client/src/main/team/payment/index.ts
- packages/api-client/src/main/team/team/TeamData.ts
> refactor(api-client): Add currency type

- packages/api-client/src/main/Client.ts
- packages/api-client/src/main/asset/AssetAPI.ts
- packages/api-client/src/main/auth/AuthAPI.ts
- packages/api-client/src/main/client/ClientAPI.ts
- packages/api-client/src/main/connection/ConnectionAPI.ts
- packages/api-client/src/main/conversation/ConversationAPI.ts
- packages/api-client/src/main/giphy/GiphyAPI.ts
- packages/api-client/src/main/http/HttpClient.ts
- packages/api-client/src/main/invitation/InvitationAPI.ts
- packages/api-client/src/main/notification/NotificationAPI.ts
- packages/api-client/src/main/self/SelfAPI.ts
- packages/api-client/src/main/shims/browser/cookie.ts
- packages/api-client/src/main/shims/node/cookie.ts
- packages/api-client/src/main/team/invitation/TeamInvitationAPI.ts
- packages/api-client/src/main/team/member/MemberAPI.ts
- packages/api-client/src/main/team/payment/PaymentAPI.ts
- packages/api-client/src/main/team/service/ServiceAPI.ts
- packages/api-client/src/main/team/team/TeamAPI.ts
- packages/api-client/src/main/user/UserAPI.ts
> refactor(api-client): Clarify return data

- packages/changelog-bot/package.json
- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/changelog-bot/src/main/ChangelogData.ts
- packages/changelog-bot/src/main/cli.ts
- packages/changelog-bot/src/main/interfaces.ts
- packages/changelog-bot/src/main/start.ts
- yarn.lock
> refactor(changelog-bot): Support sending to multiple conversations (WEBFOUND-47)

- packages/core/src/main/conversation/ConversationService.test.node.js
- packages/core/src/main/conversation/ConversationService.ts
> fix(core): Add missing users on message sending

- packages/api-client/src/main/auth/RegisterData.ts
> fix(api-client): Mark expires_in in RegisterData as optional

- packages/api-client/index.js
- packages/api-client/src/demo/demo.js
- packages/api-client/src/main/APIClient.ts
- packages/api-client/src/main/auth/AccessTokenStore.ts
- packages/api-client/src/main/http/HttpClient.ts
- packages/api-client/src/main/tcp/WebSocketClient.ts
- packages/bot-api/src/main/Bot.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/client/ClientService.ts
- packages/core/src/main/cryptography/CryptographyService.ts
- packages/core/src/main/notification/NotificationService.ts
- packages/cryptobox/src/demo/demo.js
- packages/cryptobox/src/main/Cryptobox.ts
> chore(api-client,bot-api,core-cryptobox): Align import of logdown

- .yarnrc
From https://yarnpkg.com/lang/en/docs/workspaces/:
> Workspaces are [...] available by default starting from Yarn 1.0.
- ~~[x] My code is covered by tests~~
- ~~[x] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes~~
> chore: Remove .yarnrc

- packages/bazinga64/src/main/bazinga64.ts
> refactor: Batched string conversion for array buffers

- packages/store-engine/src/main/engine/IndexedDBEngine.test.browser.js
- packages/store-engine/src/main/engine/IndexedDBEngine.ts
- packages/store-engine/src/main/engine/error/LowDiskSpaceError.ts
- packages/store-engine/src/main/engine/error/index.ts
- packages/store-engine/src/main/index.ts
> feat(store-engine): Check for disk space before using IndexedDB

- packages/store-engine/src/main/engine/IndexedDBEngine.ts
- yarn.lock
> refactor(store-engine): Map Dexie errors

- .travis.yml
Follow-up to https://github.com/wireapp/wire-web-packages/pull/1352.
- ~~[ ] My code is covered by tests~~
- ~~[ ] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes~~
> chore: Use regex for PR dependency bump test

- packages/bot-api/src/main/Bot.ts
- packages/cli-client/src/main/index.ts
- packages/core/src/demo/echo.js
- packages/core/src/demo/sender.js
- packages/core/src/main/Account.test.node.js
- packages/core/src/main/Account.ts
- packages/travis-bot/src/main/index.ts
> feat(core): Add error emit

- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService.test.node.js
- packages/core/src/main/conversation/TextContentBuilder.ts
> fix(core): Read expectsReadConfirmation flag

- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/GenericMessageType.ts
> fix(core): Check if external message is needed

- packages/proteus/src/main/session/RecvChain.ts
> fix(proteus): Typo in error message

- packages/copy-config/src/main/CopyConfig.test.js
- packages/copy-config/src/main/CopyConfig.ts
> feat(copy-config): Add filter, fix single file copy

- packages/copy-config/src/main/CopyConfig.test.js
- packages/copy-config/src/main/CopyConfig.ts
> fix(copy-config): Support paths from Windows systems

- packages/react-ui-kit/tsconfig.json
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015#issuecomment-463062037
> fix(react-ui-kit): Declare global types

- packages/api-client/tsconfig.json
- packages/bazinga64/tsconfig.json
- packages/bot-api/tsconfig.json
- packages/cbor/tsconfig.json
- packages/changelog-bot/tsconfig.json
- packages/cli-client/tsconfig.json
- packages/commons/tsconfig.json
- packages/copy-config/tsconfig.json
- packages/core/tsconfig.json
- packages/cryptobox/tsconfig.json
- packages/lru-cache/tsconfig.json
- packages/priority-queue/tsconfig.json
- packages/proteus/tsconfig.json
- packages/react-ui-kit/package.json
- packages/react-ui-kit/src/Form/Button.tsx
- packages/react-ui-kit/src/Form/InputSubmitCombo.tsx
- packages/react-ui-kit/src/Form/RoundIconButton.tsx
- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/Tooltip.tsx
- packages/react-ui-kit/src/Layout/Container.tsx
- packages/react-ui-kit/src/Misc/Loading.tsx
- packages/react-ui-kit/src/Misc/Pill.tsx
- packages/react-ui-kit/src/Text/Label.tsx
- packages/store-engine/tsconfig.json
- packages/travis-bot/tsconfig.json
- yarn.lock
This closes https://github.com/wireapp/wire-web-packages/pull/1520 and closes https://github.com/wireapp/wire-web-packages/pull/1492.
> fix(react-ui-kit): Update style-components types

- packages/copy-config/src/main/CopyConfig.ts
Log output before:
```
ℹ️  @wireapp/copy-config/CopyConfig Copying "[path]/spec/helpers/**" -> "[path]/.temp/"
```
After:
```
ℹ️  @wireapp/copy-config/CopyConfig Resolving "[path]/spec/helpers/**"
ℹ️  @wireapp/copy-config/CopyConfig Copying "[path]/spec/helpers/test1.txt" -> "[path]/.temp/test1.txt"
ℹ️  @wireapp/copy-config/CopyConfig Copying "[path]/spec/helpers/test2.txt" -> "[path]/.temp/test2.txt"
```
> feat: Log all files hidden behind a glob

- packages/core/package.json
- packages/core/webpack.config.js
- yarn.lock
> chore(core): Replace uglifyjs-webpack-plugin with terser-webpack-plugin

- .prettierignore
- packages/bazinga64/package.json
- packages/bazinga64/src/Converter.ts
- packages/bazinga64/src/DecodedData.ts
- packages/bazinga64/src/Decoder.ts
- packages/bazinga64/src/EncodedData.ts
- packages/bazinga64/src/Encoder.ts
- packages/bazinga64/src/IData.ts
- packages/bazinga64/src/UnsupportedInputError.ts
- packages/bazinga64/src/index.ts
- packages/bazinga64/tsconfig.json
> refactor(bazinga64): Organize classes in separate files

- packages/api-client/src/main/APIClient.ts
- packages/api-client/src/main/auth/AuthenticationError.ts
- packages/api-client/src/main/http/BackendErrorMapper.ts
- packages/api-client/src/main/tcp/WebSocketClient.ts
> fix(api-client): Disconnect WebSocket when cookie is invalid

- packages/api-client/src/main/team/member/Permissions.test.ts
- packages/api-client/src/main/team/member/Permissions.ts
- packages/api-client/src/main/team/member/PermissionsData.ts
- packages/api-client/src/main/team/member/Role.test.ts
- packages/api-client/src/main/team/member/Role.ts
- packages/api-client/src/main/team/member/index.ts
- packages/core/src/main/user/UserService.test.node.js
> feat(api-client): Add Permission & Role helpers

- packages/copy-config/src/main/CopyConfig.test.js
- packages/copy-config/src/main/CopyConfig.ts
- packages/copy-config/src/main/CopyConfigOptions.ts
> feat(copy-config): Add basedir configuration and cleanup basedir after copying files

- packages/bot-api/src/main/Bot.ts
- packages/bot-api/src/main/Interfaces.ts
> feat(bot-api): Add backend selection

- packages/commons/src/main/util/ValidationUtil.test.node.js
- packages/commons/src/main/util/ValidationUtil.ts
> feat(commons): Export regular expressions for validations

- packages/commons/package.json
- packages/commons/src/main/util/UrlUtil.test.browser.js
- packages/commons/src/main/util/UrlUtil.ts
- yarn.lock
It's using url-search-params now
> refactor(commons): Use URLSearchParams in UrlUtil 

- packages/bot-api/src/main/Bot.ts
> feat(bot-api): Expose send text method

- .travis.yml
> chore: Don't publish testing related commits

- packages/commons/src/test/helpers/ExceptionHandler.js
- packages/core/src/demo/echo.js
- packages/core/src/demo/sender.js
See https://nodejs.org/api/process.html#process_event_unhandledrejection
> chore(core,commons): log unhandled rejections correctly

- packages/bot-api/src/main/MessageHandler.ts
- packages/commons/src/main/util/UrlUtil.test.browser.ts
- packages/core/src/demo/echo.js
- packages/core/src/demo/sender.js
- packages/core/src/main/Account.smoke-test.node.js
- packages/core/src/main/conversation/message/MessageBuilder.ts
- packages/core/src/main/cryptography/MessageHashService.test.browser.js
- packages/core/src/main/cryptography/MessageHashService.test.node.js
- packages/core/src/main/cryptography/MessageHashService.ts
- packages/store-engine/src/main/test/updateSpec.ts
> chore(core): Cleanup and fix demo

- packages/commons/src/main/util/ValidationUtil.test.node.js
- packages/commons/src/main/util/ValidationUtil.ts
> feat(commons): Add isValidEmail to ValidationUtil

- packages/prettier-config/README.md
- packages/prettier-config/index.json
- packages/prettier-config/package.json
> feat(prettier-config): Add prettier-config package

- .eslintrc.js
- package.json
- packages/cryptobox/src/demo/benchmark.js
- packages/eslint-config/README.md
- packages/eslint-config/eslintrc.json
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- packages/prettier-config/README.md
- packages/react-ui-kit/webpack.config.js
- yarn.lock
> feat(eslint-config): Add eslint-config for wireapp

- packages/eslint-config/eslintrc.json
> chore(eslint-config): More react rules

- package.json
- packages/eslint-config/package.json
- packages/tslint-config/README.md
- packages/tslint-config/package.json
- packages/tslint-config/tslint.json
- tslint.json
> feat(tslint-config): Add package tslint-config.

- packages/tslint-config/package.json
- packages/tslint-config/tslint.json
> chore(tslint-config): No unused variables

- packages/tslint-config/tslint.json
> chore(tslint-config): Add jsx-wrap-multiline false

- packages/react-ui-kit/demo/DemoInputs.jsx
- packages/react-ui-kit/src/Menu/TabBar.tsx
- packages/react-ui-kit/src/Menu/index.ts
> feat(react-ui-kit): TabBar component

- packages/react-ui-kit/demo/Demo.jsx
- packages/react-ui-kit/src/Identity/Avatar.tsx
> fix(react-ui-kit): Use max 2 chars for initials

- packages/react-ui-kit/src/Form/Button.tsx
> fix(react-ui-kit): Export buttonLinkStyles

- packages/api-client/src/main/env/Backend.ts
> feat(api-client): Add BackendData interface

- packages/api-client/src/main/conversation/OTRClientMap.ts
- packages/api-client/src/main/conversation/OTRRecipients.ts
- packages/api-client/src/main/user/UserAPI.ts
- packages/bazinga64/src/Converter.ts
- packages/copy-config/src/main/CopyConfig.ts
- packages/copy-config/src/main/CopyConfigOptions.ts
- packages/cryptobox/src/main/store/CryptoboxCRUDStore.ts
- packages/lru-cache/src/main/LRUCache.ts
- packages/proteus/src/main/errors/ProteusError.ts
- packages/proteus/src/main/util/MemoryUtil.ts
- packages/react-ui-kit/src/Identity/colors.ts
- packages/react-ui-kit/src/mediaQueries.ts
- packages/store-engine/src/main/engine/MemoryEngine.ts
- packages/store-engine/src/main/store/TransientStore.ts
> refactor: Use built-in Record type

- packages/api-client/src/main/team/identityprovider/IdentityProviderAPI.ts
- packages/api-client/src/main/team/invitation/TeamInvitationAPI.ts
- packages/api-client/src/main/team/legalhold/LegalHoldAPI.ts
- packages/api-client/src/main/team/member/MemberAPI.ts
- packages/api-client/src/main/team/payment/PaymentAPI.ts
- packages/api-client/src/main/team/team/TeamAPI.ts
> refactor(api-client): Don't return void as data

- packages/bot-api/src/main/MessageHandler.ts
- packages/core/package.json
- packages/core/src/demo/echo.js
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/content/ReactionContent.ts
- packages/core/src/main/conversation/message/MessageBuilder.ts
- yarn.lock
> fix(core): Add Legal Hold flag to Reaction

- packages/react-ui-kit/demo/DemoIcons.jsx
- packages/react-ui-kit/src/Icon/TriangleIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit): TriangleIcon

- packages/react-ui-kit/demo/DemoInputs.jsx
- packages/react-ui-kit/src/Form/Button.tsx
- packages/react-ui-kit/src/Identity/colors.ts
- packages/react-ui-kit/src/Misc/Loading.tsx
> feat(react-ui-kit): Loading spinner inside of Button

- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/content/ClientAddContent.ts
- packages/core/src/main/conversation/content/ClientRemoveContent.ts
- packages/core/src/main/conversation/content/ConversationContent.ts
- packages/core/src/main/conversation/content/index.ts
- packages/core/src/main/conversation/message/PayloadBundle.ts
> feat(core): Add events for client add/remove

- packages/store-engine-fs/src/index.test.ts
- packages/store-engine-fs/src/index.ts
> refactor(store-engine-fs): async/await and cleanup

- packages/api-client/package.json
- packages/api-client/src/main/http/HttpClient.ts
- packages/api-client/src/main/notification/NotificationAPI.ts
- packages/api-client/src/main/tcp/WebSocketClient.ts
- packages/commons/src/main/index.ts
- packages/commons/src/main/util/TimeUtil.ts
- packages/commons/src/main/util/index.ts
- packages/core/src/demo/TimeUnits.js
- packages/core/src/demo/sender.js
> feat(commons): Add TimeUtil

- packages/api-client/src/main/team/legalhold/index.ts
> refactor(api-client): Export legal hold member status

- packages/api-client/src/main/team/payment/PaymentData.ts
https://github.com/wireapp/wire-team-settings/pull/2201
> fix(api-client): Payment exports

- packages/api-client/src/main/event/UserEvent.ts
> feat(api-client): Add legal hold request event

- packages/api-client/src/main/APIClient.ts
> fix(api-client): Remove redundant emitter

- packages/api-client/src/main/team/legalhold/LegalHoldAPI.ts
- packages/api-client/src/main/team/legalhold/LegalHoldMemberStatus.ts
> feat(api-client): Add legal hold member data

- packages/api-client/src/main/asset/AssetAPI.ts
- packages/core/src/main/conversation/content/AssetContent.ts
- packages/core/src/main/conversation/content/ClearedContent.ts
- packages/core/src/main/conversation/content/ClientActionContent.ts
- packages/core/src/main/conversation/content/ConfirmationContent.ts
- packages/core/src/main/conversation/content/DeletedContent.ts
- packages/core/src/main/conversation/content/HiddenContent.ts
- packages/core/src/main/conversation/content/LinkPreviewContent.ts
- packages/core/src/main/conversation/content/MentionContent.ts
- packages/core/src/main/conversation/content/QuoteContent.ts
- packages/core/src/main/conversation/content/TweetContent.ts
> refactor(core): Re-export interfaces from protobuf

- packages/eslint-config/eslintrc.json
Issue:
(seen in https://travis-ci.org/wireapp/wire-web-packages/builds/547613555#L550)
---
Related to https://github.com/yannickcr/eslint-plugin-react/issues/2218 and https://github.com/yannickcr/eslint-plugin-react/issues/2252
> fix(eslint-config): Use latest React version

- packages/api-client/src/main/conversation/Conversation.ts
- packages/api-client/src/main/event/ConversationEvent.ts
> refactor(api-client): Simplify conversation access enums

- packages/api-client/src/demo/demo.js
- packages/api-client/src/main/tcp/WebSocketClient.ts
> fix(api-client): Log ping/pong only as debug

- package.json
- packages/api-client/src/demo/demo.js
- packages/core/src/main/test/PayloadHelper.js
- packages/eslint-config/README.md
- packages/eslint-config/eslintrc.json
- packages/eslint-config/package.json
- packages/react-ui-kit/demo/Demo.jsx
- packages/react-ui-kit/demo/DemoColors.jsx
- packages/react-ui-kit/demo/DemoInputs.jsx
- packages/react-ui-kit/demo/index.jsx
- yarn.lock
> feat(eslint-config): Sort imports and keys automatically

- packages/api-client/src/main/client/ClientAPI.ts
- packages/api-client/src/main/conversation/ConversationAPI.ts
- packages/api-client/src/main/team/identityprovider/IdentityProviderAPI.ts
- packages/api-client/src/main/team/payment/PaymentAPI.ts
- packages/api-client/src/main/user/UserAPI.ts
> feat(api-client): Precise property typings, cleanup

- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/content/CallingContent.ts
- packages/core/src/main/conversation/content/ConversationContent.ts
- packages/core/src/main/conversation/content/index.ts
> feat(core): Receive calling messages

- packages/bot-api/src/main/MessageHandler.ts
- packages/core/src/main/conversation/message/MessageBuilder.ts
> feat(bot-api,core): Expose call signaling

- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
> feat(core): Propagate calling events

- packages/store-engine-dexie/src/index.ts
> fix(store-engine-dexie): Use error instance like Cryptobox

- packages/api-client/src/main/APIClient.ts
- packages/api-client/src/main/auth/AccessTokenStore.ts
- packages/api-client/src/main/http/HttpClient.ts
- packages/api-client/src/main/tcp/WebSocketClient.ts
- packages/bot-api/src/main/Bot.ts
- packages/cbor/src/main/cbor/Decoder.ts
- packages/cbor/src/main/cbor/Encoder.ts
- packages/copy-config/src/main/CopyConfig.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/client/ClientService.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/MessageTimer.ts
- packages/core/src/main/conversation/message/TextContentBuilder.ts
- packages/core/src/main/cryptography/CryptographyService.ts
- packages/core/src/main/cryptography/MessageHashService.ts
- packages/core/src/main/notification/NotificationService.ts
- packages/cryptobox/src/main/Cryptobox.ts
- packages/license-collector/src/LicenseCollector.ts
- packages/lru-cache/src/main/LRUCache.ts
- packages/priority-queue/src/main/PriorityQueue.ts
- packages/store-engine-bro-fs/src/index.ts
- packages/store-engine-sqleet/src/index.ts
- packages/store-engine/src/main/store/TransientStore.ts
- packages/tslint-config/tslint.json
- `public-instance-field`
- `public-constructor`
- `private-instance-field`
- `private-constructor`
- `public-instance-method`
- `protected-instance-method`
- `private-instance-method`
> feat(tslint-config): Change ordering

- packages/core/src/main/Account.ts
> fix(core): add missing LH fields

- packages/api-client/src/main/team/member/MemberData.ts
- packages/api-client/src/main/team/member/PermissionsData.ts
- packages/api-client/src/main/team/team/NewTeamData.ts
- packages/api-client/src/main/team/team/TeamAPI.ts
- packages/api-client/src/main/team/team/TeamData.ts
- packages/api-client/src/main/team/team/UpdateTeamData.ts
- packages/api-client/src/main/team/team/index.ts
- packages/core/src/main/team/TeamService.ts
> feat(api-client, core): Update interfaces for team icons

- packages/api-client/src/main/team/member/MemberData.ts
> fix(api-client): Merge MemberData interfaces

- packages/core/src/main/conversation/ConversationService.test.node.js
- packages/core/src/main/conversation/message/TextContentBuilder.ts
> fix(core): Set default legal hold status to 'unknown'

- packages/react-ui-kit/demo/DemoIcons.jsx
> chore(react-ui-kit): Align item in center for the demo

- packages/core/src/main/Account.ts
- packages/core/src/main/client/ClientDatabaseRepository.ts
- packages/core/src/main/conversation/ConversationService.test.node.js
- packages/core/src/main/conversation/message/MessageBuilder.ts
- packages/core/src/main/notification/NotificationDatabaseRepository.ts
- packages/core/src/main/notification/NotificationService.ts
- packages/core/src/main/user/UserService.ts
> refactor(core): Use async/await

- packages/api-client/index.js
- packages/api-client/src/main/account/AccountAPI.ts
- packages/api-client/src/main/asset/AssetAPI.ts
- packages/api-client/src/main/auth/AuthAPI.ts
- packages/api-client/src/main/broadcast/BroadcastAPI.ts
- packages/api-client/src/main/client/ClientAPI.ts
- packages/api-client/src/main/connection/ConnectionAPI.ts
- packages/api-client/src/main/conversation/ConversationAPI.ts
- packages/api-client/src/main/giphy/GiphyAPI.ts
- packages/api-client/src/main/http/HttpClient.ts
- packages/api-client/src/main/notification/NotificationAPI.ts
- packages/api-client/src/main/self/SelfAPI.ts
- packages/api-client/src/main/shims/node/cookie.ts
- packages/api-client/src/main/team/invitation/TeamInvitationAPI.ts
- packages/api-client/src/main/team/member/MemberAPI.ts
- packages/api-client/src/main/team/payment/PaymentAPI.ts
- packages/api-client/src/main/team/service/ServiceAPI.ts
- packages/api-client/src/main/team/team/TeamAPI.ts
- packages/api-client/src/main/user/UserAPI.ts
> refactor(api-client): Use async/await

- packages/proteus/spec/util/ArrayUtilSpec.js
- packages/proteus/src/main/util/ArrayUtil.ts
> fix(proteus): Use for-of loop in non-zero assertion

- packages/api-client/src/main/team/index.ts
> fix(api-client): Export missing member info

- packages/api-client/src/main/team/payment/PaymentAPI.ts
> refactor(api-client): Use PaymentDataUpdate in deletePaymentData

- packages/react-ui-kit/src/Identity/Avatar.tsx
> feat(react-ui-kit): Size in avatar optional

- packages/store-engine-bro-fs/src/index.ts
- packages/store-engine-dexie/src/index.test.ts
- packages/store-engine-fs/src/index.test.ts
- packages/store-engine-fs/src/index.ts
- packages/store-engine-sqleet/src/index.ts
> fix(store-engine-bro-fs,store-engine-sqleet): Unify error types

- packages/react-ui-kit/demo/Demo.jsx
- packages/react-ui-kit/src/Identity/Avatar.tsx
- packages/react-ui-kit/src/Identity/AvatarGrid.tsx
> fix(react-ui-kit): Set default Avatar & AvatarGrid size

- packages/store-engine/src/main/engine/CRUDEngine.ts
- packages/store-engine/src/main/engine/LocalStorageEngine.ts
- packages/store-engine/src/main/engine/MemoryEngine.ts
- packages/store-engine/src/main/store/TransientStore.ts
- packages/store-engine/src/main/test/updateSpec.ts
> refactor(store-engine): Sort interface and class members

- packages/react-ui-kit/src/Identity/Avatar.tsx
> fix(react-ui-kit): Fix min-width for Avatar

- packages/store-engine/src/main/engine/MemoryEngine.test.ts
- packages/store-engine/src/main/engine/MemoryEngine.ts
> feat(store-engine): Add initWithObject to MemoryEngine

- packages/store-engine/src/main/engine/MemoryEngine.test.ts
- packages/store-engine/src/main/engine/MemoryEngine.ts
> feat(store-engine): Auto-increment primary keys in MemoryEngine

- packages/react-ui-kit/demo/Demo.jsx
> chore(react-ui-kit): Fix typo in demo

- packages/store-engine/src/main/engine/MemoryEngine.test.ts
- packages/store-engine/src/main/engine/MemoryEngine.ts
> fix(store-engine): Primary key should only increment on creation

- packages/store-engine-bro-fs/src/index.ts
- packages/store-engine-dexie/src/index.test.ts
- packages/store-engine-fs/src/index.ts
- packages/store-engine-sqleet/src/index.ts
- packages/store-engine/src/main/engine/LocalStorageEngine.ts
- packages/store-engine/src/main/engine/MemoryEngine.test.ts
- packages/store-engine/src/main/engine/MemoryEngine.ts
- packages/store-engine/src/main/test/updateOrCreateSpec.ts
> feat(store-engine,store-engine-bro-fs,store-engine-dexie,store-engine-fs,store-engine-sqleet): Auto-increment primary keys

- packages/store-engine/package.json
Since we moved filesystem and bro-fs engines to separate packages, we don't need the dependencies anymore in the main package.
> chore(store-engine): Remove unused dependencies

- packages/store-engine-bro-fs/package.json
- packages/store-engine-dexie/package.json
- packages/store-engine-fs/package.json
- packages/store-engine-sqleet/package.json
- packages/store-engine/README.md
> docs(store-engine,store-engine-bro-fs,store-engine-dexie,store-engine-fs,store-engine-sqleet): Add package description

- packages/store-engine-fs/src/index.ts
- packages/store-engine/src/main/test/updateOrCreateSpec.ts
> test(store-engine): Verify that auto-incremented primary keys are integers

- packages/store-engine-sqleet/src/SchemaConverter.ts
- packages/store-engine-sqleet/src/index.test.ts
- packages/store-engine-sqleet/src/index.ts
- packages/store-engine/src/main/test/createSpec.ts
- yarn.lock
> fix(store-engine,store-engine-sqleet): Verify that strings and objects can be saved

- packages/proteus/spec/util/WasmUtilSpec.js
- packages/proteus/src/main/util/WASMUtil.ts
> feat(proteus): Add WASMUtil

- packages/react-ui-kit/demo/DemoIcons.jsx
- packages/react-ui-kit/src/Icon/InfoIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit): Add InfoIcon

- packages/react-ui-kit/demo/DemoIcons.jsx
- packages/react-ui-kit/src/Icon/ArchiveIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit): Add archive icon

- packages/store-engine-dexie/src/index.ts
> refactor(store-engine-dexie): Use async/await

- packages/store-engine-dexie/package.json
- packages/store-engine-dexie/src/index.ts
> fix(store-engine-dexie): Use logdown instead of console

- packages/store-engine-dexie/src/index.ts
> fix(store-engine-dexie): Check usage after assigning db

- packages/store-engine/src/main/engine/MemoryEngine.ts
- packages/store-engine/src/main/store/TransientStore.ts
> refactor(store-engine): Use async/await

- packages/store-engine-bro-fs/src/index.ts
- packages/store-engine-web-storage/src/WebStorageEngine.ts
> refactor(store-engine-bro-fs,store-engine-web-storage): Use async/await

- packages/api-client/package.json
- packages/api-client/src/main/APIClient.ts
- packages/api-client/src/main/auth/AccessTokenStore.ts
- packages/api-client/src/main/http/HttpClient.ts
- packages/api-client/src/main/tcp/WebSocketClient.ts
- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
- yarn.lock
> fix(api-client): Don't disconnect WebSocket on failed ping

- packages/api-client/src/main/tcp/ReconnectingWebsocket.ts
- packages/api-client/src/main/tcp/WebSocketClient.ts
> refactor(api-client): Sorting, import, redundant enum

- packages/api-client/src/main/tcp/ReconnectingWebsocket.test.node.js
> test(api-client): Use shorter while

- packages/api-client/src/main/conversation/IncomingNotification.ts
> chore(api-client): Document "transient" property

- packages/api-client/src/main/auth/AuthenticationError.ts
- packages/api-client/src/main/tcp/ReconnectingWebsocket.test.node.js
- packages/api-client/src/main/tcp/WebSocketClient.test.node.js
> fix(api-client): Set correct prototype for InvalidTokenError

- packages/react-ui-kit/src/Identity/Avatar.tsx
> fix(react-ui-kit): Min height for avatar component

- packages/react-ui-kit/src/Misc/index.ts
> fix(react-ui-kit): Export useLongTouch

- packages/react-ui-kit/src/Misc/useLongTouch.ts
> fix(react-ui-kit): Remove preventDefaults from touch events

- packages/core/src/main/Account.ts
> refactor: Add default notification handler

- .github/workflows/main.yml
> chore: Add Windows tests

- packages/core/src/main/cryptography/CryptographyService.test.node.ts
> test(core): Check for unique message counters during encryption

- packages/priority-queue/package.json
- packages/priority-queue/src/main/Config.ts
- packages/priority-queue/src/main/Item.ts
- packages/priority-queue/src/main/PriorityQueue.ts
- packages/priority-queue/src/test/browser/PriorityQueue.test.js
- packages/priority-queue/src/test/node/spec/PriorityQueue.test.js
- packages/priority-queue/tsconfig.json
> feat(priority-queue): Growing retry delay

- packages/api-client/src/main/user/data/UserPropertiesSetData.ts
> feat(api-client): Export WebappProperties

- packages/api-client/src/main/user/data/UserPropertiesSetData.ts
> fix(api-client): Add report_errors to privacy in WebappProperties

- packages/api-client/src/main/user/data/UserPropertiesSetData.ts
> fix(api-client): Add interface to WebappProperties

- packages/api-client/src/main/APIClient.ts
- packages/api-client/src/main/tcp/ReconnectingWebsocket.ts
- packages/api-client/src/main/tcp/WebSocketClient.test.node.js
- packages/api-client/src/main/tcp/WebSocketClient.ts
- packages/core/src/main/Account.ts
> feat(core,api-client): Fetch notification stream before fully connecting the websocket

- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/content/AssetContent.ts
- packages/core/src/main/conversation/content/ConversationContent.ts
- packages/core/src/main/conversation/content/FileContent.ts
> feat(core): Send audio and video metadata

- packages/bot-api/src/main/MessageHandler.ts
- packages/core/src/main/user/UserService.ts
> fix(core): Return single user info

- packages/core/src/main/conversation/ConversationService.ts
This was introduced in [#2480](https://github.com/wireapp/wire-web-packages/pull/2480/files#diff-7659fc1e7b17e608837c4c101bd880eaL811).
> fix(core): Set userIds as optional

- packages/store-engine-sqleet/src/SQLeetEngine.ts
- packages/store-engine-sqleet/src/SchemaConverter.ts
> fix(store-engine-sqleet): Add correct record typings

- packages/api-client/src/main/self/SelfAPI.ts
This endpoint is needed to check the existence of a password.
> feat(api-client): HEAD /self/password endpoint

- packages/api-client/src/main/auth/AuthAPI.ts
- packages/api-client/src/main/auth/SendLoginCode.ts
https://github.com/zinfra/backend-issues/issues/974
> fix(api-client): Add undocumented force flag to /login/send endpoint data

- packages/proteus/.nycrc.json
- packages/proteus/jasmine.json
- packages/proteus/package.json
- packages/proteus/spec/derived/CipherKeySpec.ts
- packages/proteus/spec/derived/DerivedSecretsSpec.ts
- packages/proteus/spec/derived/MacKeySpec.ts
- packages/proteus/spec/errors/DecryptErrorSpec.ts
- packages/proteus/spec/keys/IdentityKeyPairSpec.ts
- packages/proteus/spec/keys/KeyPairSpec.ts
- packages/proteus/spec/keys/PreKeyBundleSpec.ts
- packages/proteus/spec/keys/PreKeySpec.ts
- packages/proteus/spec/keys/PublicKeySpec.ts
- packages/proteus/spec/message/EnvelopeSpec.ts
- packages/proteus/spec/message/MessageSpec.ts
- packages/proteus/spec/session/SessionSpec.ts
- packages/proteus/spec/util/ArrayUtilSpec.ts
- packages/proteus/spec/util/KeyDerivationUtilSpec.ts
- packages/proteus/spec/util/MemoryUtilSpec.ts
- packages/proteus/spec/util/WasmUtilSpec.ts
- packages/proteus/src/main/errors/DecryptError.ts
- packages/proteus/src/main/keys/PublicKey.ts
- packages/proteus/src/main/keys/SecretKey.ts
- packages/proteus/tsconfig.json
> refactor(proteus): Convert tests to TypeScript

- packages/api-client/src/main/APIClient.ts
- packages/api-client/src/main/auth/AccessTokenStore.ts
- packages/api-client/src/main/http/HttpClient.ts
- packages/api-client/src/main/tcp/WebSocketClient.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/notification/NotificationService.ts
- packages/cryptobox/src/main/Cryptobox.ts
- packages/store-engine/src/main/store/TransientStore.ts
> refactor(api-client,core,cryptobox,store-engine): Remove declare keyword

- packages/api-client/src/account/AccountAPI.ts
- packages/api-client/src/asset/AssetAPI.ts
- packages/api-client/src/auth/AccessTokenStore.ts
- packages/api-client/src/broadcast/BroadcastAPI.ts
- packages/api-client/webpack.browser.js
> fix(api-client): Remove Dexie from webpack

- packages/cli-client/README.md
- packages/cli-client/package.json
> fix(cli-client): Correct bin entry

- packages/store-engine-sqleet/src/SQLeetEngine.ts
- packages/store-engine-sqleet/src/SchemaConverter.ts
> refactor(store-engine-sqleet): Simplify mappings

- bin/testUpdated.js
- package.json
- packages/api-client/src/APIClient.ts
> chore: Improve build & test performance

- packages/api-client/src/client/ClientAPI.ts
- packages/api-client/src/client/NewClient.ts
- packages/api-client/src/client/RegisteredClient.ts
- packages/api-client/src/user/data/UserClientAddData.ts
> feat(api-client): Add putClient

- packages/api-client/src/APIClient.ts
- packages/api-client/src/account/AccountAPI.ts
- packages/api-client/src/auth/AccessTokenStore.ts
- packages/api-client/src/auth/AuthAPI.ts
- packages/api-client/src/auth/CookieStore.ts
- packages/api-client/src/broadcast/BroadcastAPI.ts
- packages/api-client/src/client/ClientAPI.ts
- packages/api-client/src/connection/ConnectionAPI.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/giphy/GiphyAPI.ts
- packages/api-client/src/http/HttpClient.ts
- packages/api-client/src/notification/NotificationAPI.ts
- packages/api-client/src/self/SelfAPI.ts
- packages/api-client/src/tcp/WebSocketClient.ts
- packages/api-client/src/team/feature/FeatureAPI.ts
- packages/api-client/src/team/identityprovider/IdentityProviderAPI.ts
- packages/api-client/src/team/invitation/TeamInvitationAPI.ts
- packages/api-client/src/team/legalhold/LegalHoldAPI.ts
- packages/api-client/src/team/member/MemberAPI.ts
- packages/api-client/src/team/payment/PaymentAPI.ts
- packages/api-client/src/team/service/ServiceAPI.ts
- packages/api-client/src/team/team/TeamAPI.ts
- packages/api-client/src/user/UserAPI.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/notification/NotificationService.ts
- packages/cryptobox/src/main/Cryptobox.ts
- packages/store-engine/src/main/store/TransientStore.ts
> refactor(api-client,core,cryptobox,store-engine): Use readonly instead of getter

- package.json
> chore: Use true fallback for from-package publishing

- packages/api-client/src/connection/ConnectionStatus.ts
- packages/api-client/src/conversation/ConversationCode.ts
- packages/api-client/src/conversation/data/ConversationCodeUpdateData.ts
- packages/api-client/src/conversation/data/ConversationCreateData.ts
- packages/api-client/src/conversation/data/ConversationMemberUpdateData.ts
- packages/api-client/src/conversation/data/ConversationReceiptModeUpdateData.ts
- packages/api-client/src/conversation/data/index.ts
- packages/api-client/src/event/ConversationEvent.ts
- packages/api-client/src/giphy/GiphyResult.ts
> feat(api-client): Add Receipt Mode Update Event

- packages/api-client/src/conversation/Member.ts
- packages/api-client/src/conversation/OtherMember.ts
> feat(api-client): Add conversation role to conversation members

- packages/api-client/src/conversation/ConversationAPI.ts
> feat(api-client): Add putConversationReceiptMode

- packages/api-client/src/conversation/ConversationAPI.ts
> feat(api-client): Add conversation code endpoints

- packages/api-client/src/conversation/Conversation.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/conversation/data/ConversationAccessUpdateData.ts
> feat(api-client): Add putAccess

- packages/api-client/src/APIClient.ts
- packages/api-client/src/conversation/Conversation.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/conversation/ConversationMembers.ts
- packages/api-client/src/conversation/ConversationRole.ts
- packages/api-client/src/conversation/Conversations.ts
- packages/api-client/src/conversation/Member.ts
- packages/api-client/src/conversation/NewOTRMessage.ts
- packages/api-client/src/conversation/OTRRecipients.ts
- packages/api-client/src/conversation/OtherMember.ts
- packages/api-client/src/conversation/data/ConversationMemberUpdateData.ts
- packages/api-client/src/conversation/index.ts
- packages/api-client/src/http/HttpClient.ts
- packages/api-client/src/shims/node/cookie.ts
- packages/api-client/src/team/conversation/ConversationAPI.ts
- packages/api-client/src/team/conversation/TeamConversationAPI.ts
- packages/api-client/src/team/conversation/index.ts
- packages/api-client/src/team/index.ts
- packages/api-client/src/team/team/TeamAPI.ts
- packages/api-client/src/user/User.ts
> feat(api-client): Add conversation roles and TeamConversationAPI

- packages/api-client/src/giphy/GiphyImage.ts
Example output from the API:
```
{
"data":{
"type":"gif",
"id":"xTiTnw2jwUPLpc9gBO",
"url":"https:\/\/giphy.com\/gifs\/star-wars-the-force-awakens-episode-vii-xTiTnw2jwUPLpc9gBO",
"slug":"star-wars-the-force-awakens-episode-vii-xTiTnw2jwUPLpc9gBO",
"bitly_gif_url":"https:\/\/gph.is\/1GPUEhZ",
"bitly_url":"https:\/\/gph.is\/1GPUEhZ",
"embed_url":"https:\/\/giphy.com\/embed\/xTiTnw2jwUPLpc9gBO",
"username":"",
"source":"https:\/\/www.youtube.com\/watch?v=ngElkyQ6Rhs",
"title":"flying star wars GIF",
"rating":"pg",
"content_url":"",
"source_tld":"www.youtube.com",
"source_post_url":"https:\/\/www.youtube.com\/watch?v=ngElkyQ6Rhs",
"is_sticker":0,
"import_datetime":"2015-04-16 18:52:33",
"trending_datetime":"2015-04-16 19:16:20",
"images":{
"downsized_large":{
"height":"203",
"size":"427289", …
```
> feat(api-client): Add images data to GiphyImage

- packages/api-client/src/self/Self.ts
- packages/api-client/src/team/conversation/TeamConversation.ts
- packages/api-client/src/team/conversation/TeamConversationAPI.ts
- packages/api-client/src/team/team/TeamInfo.ts
> feat(api-client): Add missing endpoints for team conversations

- packages/bot-api/src/MessageHandler.ts
> feat(bot-api): Add quote sending

- packages/bot-api/src/MessageHandler.ts
- packages/core/src/main/conversation/message/OtrMessage.ts
- packages/core/src/main/conversation/message/TextContentBuilder.ts
> feat(bot-api): Use message to send a quote

- packages/api-client/src/giphy/GiphyAPI.ts
- packages/api-client/src/giphy/GiphyOptions.ts
- packages/cbor/package.json
- packages/core/src/main/giphy/GiphyService.ts
> fix(core): Giphy search return value

- packages/cbor/package.json
> fix(cbor): Add missing dependency

- packages/bot-api/src/MessageHandler.ts
> feat(bot-api): Add get conversation endpoints

- packages/api-client/src/giphy/GiphyAPI.ts
- packages/api-client/src/giphy/GiphyOptions.ts
- packages/api-client/src/giphy/GiphySearch.ts
- packages/api-client/src/giphy/index.ts
- packages/core/src/main/giphy/GiphyService.ts
> refactor(api-client): Expose query through Giphy search options

- packages/core/src/main/conversation/ConversationService.ts
https://github.com/wireapp/wire-web-packages/blob/master/packages/api-client/src/conversation/ConversationAPI.ts#L620-L623
> fix(core): Fix parameter order for setMemberConversationRole

- packages/react-ui-kit/demo/DemoColors.jsx
- packages/react-ui-kit/demo/DemoLayouts.jsx
- packages/react-ui-kit/src/Identity/colors.ts
> refactor(react-ui-kit): Reduce derived colors

- packages/api-client/src/team/member/MemberAPI.ts
- packages/api-client/src/team/member/Members.ts
- packages/core/src/main/broadcast/BroadcastService.ts
- packages/core/src/main/team/TeamService.ts
This endpoint is a draft and is currently not provided by the backend
> feat(api-client): Get Members by ID list (BREAKING)

- packages/store-engine-sqleet/src/SQLeetEngine.test.ts
- packages/store-engine-sqleet/src/SQLeetEngine.ts
> fix(sqleet-engine): Parse JSON in readAll (WEBAPP-6765)

- packages/react-ui-kit/src/Form/Input.tsx
- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/TextArea.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Input.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/TextArea.test.tsx.snap
- packages/react-ui-kit/src/Layout/Theme.tsx
> fix(react-ui-kit): Adjust disabled input colors

- packages/api-client/src/event/TeamEvent.ts
- packages/api-client/src/team/data/TeamMemberUpdateData.ts
> feat(api-client): Add TeamMemberUpdateData

- packages/api-client/src/team/legalhold/LegalHoldMemberStatus.ts
See [`LegalHold.hs#L223`](https://github.com/wireapp/wire-server/blob/324c1f2f712bc286ce665302a2d19d83d8ceec46/libs/brig-types/src/Brig/Types/Team/LegalHold.hs#L223)
> fix(api-client): Legal Hold client ID

- packages/api-client/src/http/BackendErrorLabel.ts
https://github.com/zinfra/backend-issues/issues/1237
> feat(api-client): Add team owner deletion error labels

- packages/core/src/main/Account.ts
> feat(core): Make apiClient public

- packages/proteus/package.json
- packages/proteus/src/demo/benchmark.ts
- packages/proteus/tsconfig.json
- yarn.lock
> chore(proteus): Add benchmarks (WEBAPP-6788)

- packages/api-client/src/broadcast/BroadcastAPI.ts
- packages/api-client/src/conversation/NewOTRMessage.ts
> feat(api-client): Report missing clients in message body

- packages/api-client/src/broadcast/BroadcastAPI.ts
> fix(api-client): Add missing params in BroadcastAPI

- packages/eslint-config/eslintrc.json
> feat(eslint-config): Don't prefer uppercase when sorting

- packages/commons/src/main/util/DateUtil.test.node.js
- packages/commons/src/main/util/DateUtil.ts
- packages/commons/src/main/util/StringUtil.test.node.js
- packages/commons/src/main/util/StringUtil.ts
> feat(commons): Add DateUtil and pluralize

- packages/api-client/demo/demo.js
- packages/cli-client/src/index.ts
- packages/copy-config/src/main/cli.ts
- packages/license-collector/src/cli.ts
- packages/store-engine/README.md
- packages/travis-bot/src/cli.ts
> refactor: Convert all Promises to async/await

- packages/bot-api/package.json
- packages/bot-api/src/Bot.ts
- packages/bot-api/src/MessageHandler.test.node.js
- packages/core/package.json
- packages/core/src/main/Account.test.browser.js
- packages/core/src/main/conversation/AssetService.test.node.ts
- packages/core/src/main/conversation/message/MessageBuilder.ts
- packages/core/src/main/notification/NotificationService.test.browser.js
- packages/core/src/main/test/PayloadHelper.ts
- packages/core/src/main/user/UserService.ts
- packages/cryptobox/package.json
- packages/cryptobox/test/store/IndexedDB.test.browser.js
- packages/priority-queue/package.json
- yarn.lock
This closes https://github.com/wireapp/wire-web-packages/issues/3083.
> refactor: Use uuidjs instead of pure-uuid

- packages/react-ui-kit/src/Form/Input.tsx
- packages/react-ui-kit/src/Form/InputSubmitCombo.tsx
- packages/react-ui-kit/src/Form/TextArea.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Input.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/TextArea.test.tsx.snap
> feat(react-ui-kit): Outline selected form elements

- packages/webapp-events/src/index.ts
> feat(webapp-events): Add Analytics events

- packages/bot-handler-uptime/.nycrc.json
- packages/bot-handler-uptime/jasmine.json
- packages/bot-handler-uptime/package.json
- packages/bot-handler-uptime/src/UptimeHandler.test.ts
- packages/bot-handler-uptime/src/UptimeHandler.ts
> fix(bot-handler-uptime): Prevent type error when importing moment

- packages/api-client/src/http/HttpClient.ts
> fix(api-client): Add headers to config if they don't exist yet

- packages/bot-handler-avs/package.json
- packages/bot-handler-avs/src/AVSHandler.ts
- yarn.lock
> fix(bot-handler-avs): Add compatibility with Node.js 14

- .github/workflows/notify.yml
> chore: Add more informations to build notifications

- .github/labeler.yml
- .github/workflows/label.yml
> chore: Label PRs automatically

- packages/api-client/src/user/data/UserPropertiesSetData.ts
> feat(api-client): Remove last bits of contact import

- .github/labeler.yml
- .github/workflows/label.yml
> chore: Automatically add project labels on files changed in PR

- packages/api-client/src/auth/ClientPreKey.ts
- packages/api-client/src/auth/PreKey.ts
- packages/api-client/src/auth/PreKeyBundle.ts
- packages/bot-api/src/Bot.ts
- packages/bot-api/src/MessageHandler.test.node.js
- packages/bot-api/src/MessageHandler.ts
- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/core/src/main/conversation/ConversationService.ts
> feat(api-client,bot-api,core): Send messages to specific clients only

- packages/api-client/src/APIClient.ts
> fix(api-client): Always emit logout event to application

- packages/api-client/src/APIClient.test.node.ts
- packages/api-client/src/APIClient.ts
> fix(api-client): Display logout error as warning

- packages/api-client/src/http/HttpClient.ts
> fix(api-client): Don't mix up isSynchronousRequest with tokenAsParam

- packages/eslint-config/eslintrc.json
I sorted all config properties and added a rule to [disallow assignment operators in conditional statements](https://eslint.org/docs/rules/no-cond-assign).
> feat(eslint-config): Disallow assignment operators in conditional statements

- packages/commons/src/main/util/Runtime.ts
> refactor(commons): Add comment to clarify lowercasing

- packages/api-client/src/user/UserUpdate.ts
> refactor(api-client): Shorten UserUpdate

- packages/webapp-events/src/index.ts
> feat(webapp-events): Add CONVERSATION.VERIFICATION_STATE_CHANGED (WEBAPP-7106)

- packages/webapp-events/src/index.ts
> feat(webapp-events): Add events to show preferences

- packages/copy-config/package.json
> fix(copy-config): CLI path

- packages/api-client/src/auth/RegisterData.ts
- packages/api-client/src/auth/SendLoginCode.ts
- packages/api-client/src/user/SendActivationCode.ts
> refactor(api-client): Simplify redundant interfaces

- packages/commons/package.json
- packages/copy-config/package.json
> fix(commons,copy-config): Publish .d.ts files to npm

- packages/api-client/package.json
- packages/bazinga64/package.json
- packages/bot-api/package.json
- packages/cbor/package.json
- packages/commons/package.json
- packages/copy-config/package.json
- packages/lru-cache/package.json
- packages/priority-queue/package.json
- packages/proteus/package.json
- packages/react-ui-kit/package.json
- packages/store-engine-bro-fs/package.json
- packages/store-engine-dexie/package.json
- packages/store-engine-fs/package.json
- packages/store-engine-sqleet/package.json
- packages/store-engine-web-storage/package.json
- packages/store-engine/package.json
> fix: Don't publish test files

- packages/react-ui-kit/src/Form/Input.tsx
- packages/react-ui-kit/src/Form/InputSubmitCombo.tsx
- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/TextArea.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Input.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/TextArea.test.tsx.snap
> feat(react-ui-kit): Default border around inputs

- packages/react-ui-kit/src/Form/Checkbox.md
- packages/react-ui-kit/src/Form/Checkbox.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
> feat(react-ui-kit): New Checkbox design

- packages/api-client/package.json
- packages/bazinga64/package.json
- packages/bot-api/package.json
- packages/cbor/package.json
- packages/commons/package.json
- packages/copy-config/package.json
- packages/lru-cache/package.json
- packages/priority-queue/package.json
- packages/proteus/package.json
- packages/react-ui-kit/package.json
- packages/store-engine-bro-fs/package.json
- packages/store-engine-dexie/package.json
- packages/store-engine-fs/package.json
- packages/store-engine-sqleet/package.json
- packages/store-engine-web-storage/package.json
- packages/store-engine/package.json
Reverts wireapp/wire-web-packages#3343
> Revert "fix(bot-api): Publish source files on npm"

- .github/workflows/test_build_deploy.yml
> chore: Use new npm token

- packages/react-ui-kit/src/Form/Button.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Button.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/ButtonLink.test.tsx.snap
> feat(react-ui-kit): Remove uppercase textTransform from Button

- .github/workflows/test_build_release.yml
> chore: Change "deploy" to "release" in workflow

- packages/api-client/package.json
- packages/bazinga64/package.json
- packages/bot-api/package.json
- packages/bot-handler-avs/package.json
- packages/bot-handler-debug/package.json
- packages/bot-handler-uptime/package.json
- packages/bot-handler-wizard/package.json
- packages/cbor/package.json
- packages/copy-config/package.json
- packages/core/package.json
- packages/cryptobox/package.json
- packages/lru-cache/package.json
- packages/priority-queue/karma.conf.ts
- packages/priority-queue/package.json
- packages/priority-queue/src/main/PriorityQueue.ts
- packages/priority-queue/src/test/browser/PriorityQueue.test.js
- packages/priority-queue/src/test/node/spec/PriorityQueue.test.js
- packages/proteus/package.json
- packages/store-engine-bro-fs/package.json
- packages/store-engine-dexie/package.json
- packages/store-engine-dexie/src/index.test.ts
- packages/store-engine-fs/package.json
- packages/store-engine-sqleet/package.json
- packages/store-engine-web-storage/package.json
- packages/store-engine/package.json
- yarn.lock
> fix(priority-queue): Run tests with Jasmine 3.6

- packages/commons/src/main/util/Runtime.ts
> refactor(commons): Simplify and cleanup

- packages/api-client/src/user/data/UserConnectionData.ts
- packages/api-client/src/user/data/UserUpdateData.ts
- packages/core/src/demo/echo.js
- packages/core/src/demo/sender.js
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/message/UserMessage.ts
- packages/core/src/main/notification/NotificationService.ts
- packages/core/src/main/user/UserMapper.test.node.ts
- packages/core/src/main/user/UserMapper.ts
> fix(core,api-client): Fix demos and events

- packages/api-client/src/user/UserAPI.ts
- packages/core/src/main/conversation/ConversationService.ts
> fix(api-client,core): Endpoints can return qualified types

- packages/api-client/src/user/UserAPI.ts
> fix(api-client): Add missing path for getHandle endpoint

- packages/commons/src/main/util/TypeUtil.test.ts
- packages/commons/src/main/util/TypeUtil.ts
> feat(commons): Add OptionalKeys and RequiredKeys and add tests

- packages/api-client/src/broadcast/BroadcastAPI.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/commons/src/main/util/StringUtil.test.node.js
- packages/commons/src/main/util/StringUtil.ts
- packages/core/src/demo/sender.js
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/MessageService.ts
- packages/core/src/main/cryptography/CryptographyService.ts
> fix(core): Use onClientMismatch and properly use additional data

- packages/commons/src/main/util/UrlUtil.test.browser.ts
> test(commons): whitelist in pathWithParams

- packages/api-client/src/user/UserAPI.ts
> fix(api-client): Get federated handles

- packages/api-client/src/conversation/QualifiedUserClients.ts
- packages/api-client/src/conversation/index.ts
- packages/api-client/src/user/UserAPI.ts
- packages/core/src/main/conversation/message/MessageService.ts
> feat(api-client): Add endpoint /list-prekeys

- packages/api-client/src/broadcast/BroadcastAPI.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/self/Self.ts
- packages/api-client/src/team/search/TeamContact.ts
- packages/api-client/src/user/User.ts
- packages/api-client/src/user/UserAPI.ts
- packages/api-client/src/user/index.ts
> fix(api-client): call getHandle with string, don't encode protobuf messages

- packages/eslint-config/eslintrc.json
> feat(eslint-config): Add return-await rule

- tsconfig.json
> chore: Use target "es2017" to preserve native async / await

- packages/core/src/main/cryptography/CryptographyService.test.node.ts
> test(core): Initialize Proteus before testing

- packages/api-client/src/client/QualifiedPublicClients.ts
- packages/api-client/src/conversation/QualifiedUserClients.ts
- packages/api-client/src/user/Contact.ts
- packages/api-client/src/user/HandleInfo.ts
- packages/api-client/src/user/QualifiedHandle.ts
- packages/api-client/src/user/QualifiedId.ts
- packages/api-client/src/user/User.ts
- packages/api-client/src/user/index.ts
> feat(api-client): Add "none" domain for non-federated users

- nyc.config.js
- package.json
- packages/api-client/babel.config.js
- packages/api-client/src/http/RequestProgressHandler.ts
- packages/api-client/src/http/TraceState.ts
- packages/api-client/src/self/Name.ts
- packages/api-client/src/self/Picture.ts
- packages/bot-handler-debug/src/index.ts
- packages/bot-handler-uptime/src/UptimeHandler.test.ts
- packages/changelog-bot/src/main/cli.ts
- packages/copy-config/src/main/cli.ts
- packages/core/karma.conf.ts
- packages/core/src/main/auth/LoginSanitizer.test.node.ts
- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/MessageTimer.test.node.ts
- packages/core/src/main/cryptography/CryptographyService.test.node.ts
- packages/core/src/main/cryptography/MessageHashService.test.node.ts
- packages/core/webpack.config.js
- packages/cryptobox/karma.conf.ts
- packages/eslint-config/eslintrc.json
- packages/eslint-config/package.json
- packages/license-collector/src/cli.ts
- packages/react-ui-kit/styleguide.config.js
- packages/store-engine-bro-fs/babel.config.js
- packages/store-engine-dexie/babel.config.js
- packages/store-engine-sqleet/babel.config.js
- packages/store-engine-web-storage/babel.config.js
- packages/store-engine/webpack.config.js
- yarn.lock
Blocked by: https://github.com/Stuk/eslint-plugin-header/issues/39
> feat(eslint-config): Automatically add license header

- packages/api-client/src/user/LimitedQualifiedUserIdList.ts
- packages/api-client/src/user/UserAPI.ts
- packages/api-client/src/user/index.ts
> feat(api-client): Implement postListClients v2

- packages/api-client/src/asset/AssetAPI.ts
- packages/bot-api/src/Bot.ts
- packages/bot-api/src/MessageHandler.test.node.ts
- packages/bot-api/src/MessageHandler.ts
- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/cli-client/src/index.ts
- packages/core/src/demo/echo.ts
- packages/core/src/demo/sender.ts
- packages/core/src/main/Account.test.node.ts
- packages/core/src/main/conversation/AssetService.ts
- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/MessageBuilder.ts
- packages/core/src/main/cryptography/AssetCryptography.browser.ts
- packages/core/src/main/cryptography/AssetCryptography.node.ts
- packages/core/src/main/cryptography/CryptographyService.test.browser.js
- packages/core/src/main/cryptography/CryptographyService.test.node.ts
> feat(core): Add cipher options for encrypting assets and use named parameters (SQCORE-644)

- packages/api-client/src/conversation/ConversationAPI.ts
- packages/core/package.json
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/util/TypePredicateUtil.ts
> feat(api-client): Add qualified members to a conversation

- packages/core/src/main/user/UserService.ts
- packages/core/src/main/util/TypePredicateUtil.ts
- packages/core/src/main/util/index.ts
> fix(core): Check if QualifiedIdArray is an array

- packages/api-client/src/conversation/NewConversation.ts
- packages/api-client/src/conversation/OtherMember.ts
- packages/api-client/src/conversation/data/ConversationMemberUpdateData.ts
> feat(api-client): Add QualifiedUsers to NewConversation interface

- package.json
- yarn.lock
Reverts wireapp/wire-web-packages#4024
> Revert "chore(deps-dev): Bump husky from 4.3.8 to 7.0.1"

- packages/api-client/src/auth/AuthAPI.ts
- packages/api-client/src/self/SelfAPI.ts
> feat(api-client): New endpoint for changing email address (SQCORE-817)

- packages/api-client/src/self/SelfAPI.ts
> fix(api-client): Re-add existing endpoint for changing email address

- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/util/TypePredicateUtil.ts
> fix(core): Split up prekey fetching for federation

- packages/api-client/src/user/UserUpdate.ts
Follow-up to https://github.com/wireapp/wire-server/pull/1691
> fix(api-client): Name in UserUpdate is optional

- packages/certificate-check/README.md
- packages/certificate-check/src/CertUtil.ts
> docs(certificate-check): Add examples and verification sequence

- packages/api-client/src/APIClient.ts
- packages/api-client/src/auth/Context.ts
- packages/core/src/demo/echo.ts
- packages/core/src/demo/sendCounter.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/self/SelfService.ts
> feat(core): Add domain to context

- packages/api-client/src/APIClient.test.node.ts
- packages/api-client/src/APIClient.ts
- packages/bot-api/src/MessageHandler.test.node.ts
- packages/core/src/main/Account.test.browser.js
- packages/core/src/main/Account.test.node.ts
- packages/core/src/main/self/SelfService.ts
> feat(api-client): Get self domain when creating context

- packages/core/src/main/client/ClientDatabaseRepository.ts
- packages/core/src/main/client/ClientService.ts
> feat(core): Add domain to clients

- packages/api-client/src/conversation/ConversationAPI.ts
> feat(api-client): Delete qualified member from qualified conversation

- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/conversation/QualifiedConversationIds.ts
- packages/api-client/src/conversation/index.ts
> feat(api-client): Add getQualifiedConversationIds

- packages/react-ui-kit/src/Form/Checkbox.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
- packages/react-ui-kit/src/Identity/Avatar.tsx
> feat(react-ui-kit): Adjust checkbox styling

- packages/core/src/main/conversation/ConversationService.ts
> fix(core): Fix typecheck error

- packages/api-client/src/conversation/data/ConversationOtrMessageAddData.ts
See OtrMessage definition here https://nginz-https.anta.wire.link/api/swagger-ui for more details
> fix(api-client): Align ConversationOtrMessageData with backend definition

- packages/api-client/src/conversation/Conversation.ts
- packages/api-client/src/conversation/data/ConversationCreateData.ts
This is an auto generated interface from backend's swagger api.
> fix(api-client): Update backend conversation types with latest definitions

- packages/api-client/src/conversation/ConversationAPI.ts
> refactor(api-client): rename and deprecate conversation methods

- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/MessageService.test.node.ts
- packages/core/src/main/conversation/message/MessageService.ts
- packages/core/src/main/user/UserService.ts
- packages/core/src/main/util/TypePredicateUtil.ts
> feat(core): Add federated client mismatch handlers

- packages/api-client/src/http/BackendErrorLabel.ts
> feat(api-client): Add federation backend error labels

- packages/core/src/main/conversation/message/MessageService.test.node.ts
- packages/core/src/main/conversation/message/MessageService.ts
> fix(core): Cleanly delete users from payload when mismatch happens

- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/MessageService.test.node.ts
- packages/core/src/main/conversation/message/MessageService.ts
Enables the mismatch handler for regular message sending
> feat(core): Add mismatch hook for non-federated messages

- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/MessageService.test.node.ts
- packages/core/src/main/conversation/message/MessageService.ts
> chore(core): Improve types for onStart handler

- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/MessageService.ts
> feat(core): Do not call onSuccess when message sending errored

- packages/api-client/src/user/UserAPI.ts
> feat(api-client): Add domain parameter when searching for contacts

- packages/core/src/main/cryptography/GenericMessageMapper.ts
> feat(core): Add more qualifiedIds when mapping messages

- packages/api-client/src/user/User.ts
> feat(api-client): Add email unvalidated to user interface (SQSERVICES-231)

- packages/api-client/src/user/User.ts
- packages/api-client/src/user/UserAPI.ts
> feat(api-client): Add update user email endpoint (SQSERVICES-231)

- packages/core/src/main/conversation/content/FileContent.ts
> feat(core): Add image metadata to file metadata payload

- packages/core/src/main/conversation/ConversationService.ts
> feat(core): Add image metadata when building generic message

- packages/api-client/src/asset/AssetAPI.ts
- packages/api-client/src/services/ServicesAPI.ts
- packages/bot-api/src/MessageHandler.ts
- packages/core/src/demo/echo.ts
- packages/core/src/demo/sender.ts
- packages/core/src/main/conversation/AssetService.test.node.ts
- packages/core/src/main/conversation/AssetService.ts
- packages/core/src/main/linkPreview/LinkPreviewService.ts
> feat(core): Ability to cancel asset uploading

- packages/api-client/package.json
- packages/api-client/src/asset/AssetAPI.ts
- yarn.lock
> feat(api-client): Add federated asset upload endpoint (v4)

- packages/api-client/src/asset/AssetAPI.ts
- packages/api-client/src/user/UserAsset.ts
> feat(api-client): Adapt assets for federation

- packages/core/src/main/conversation/AssetService.ts
> feat(core): Add a method to upload an unencrypted asset

- packages/api-client/src/http/BackendErrorLabel.ts
> feat: Improved error messages for domain blocked (SQSERVICES-928)

- packages/api-client/src/asset/AssetAPI.ts
- packages/core/src/main/conversation/AssetService.ts
- packages/core/src/main/conversation/ConversationService.ts
> feat(core): Add method to download v4 assets

- packages/core/src/main/conversation/message/MessageToProtoMapper.ts
- packages/core/src/main/linkPreview/LinkPreviewService.ts
> feat(core): Enable link preview asset upload for federated env

- packages/api-client/src/team/team/LeadData.ts
- packages/api-client/src/team/team/TeamAPI.ts
> feat(api-client): adding new utms to api interface (SQSERVICES-1180)

- packages/api-client/src/conversation/Conversation.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/conversation/NewConversation.ts
- packages/api-client/src/conversation/data/ConversationAccessUpdateData.ts
> feat(api-client): adding access role v2

- packages/api-client/src/auth/AuthAPI.ts
- packages/api-client/src/auth/LoginData.ts
- packages/api-client/src/auth/VerificationActionType.ts
- packages/api-client/src/team/scim/ScimAPI.ts
- packages/api-client/src/user/UserAPI.ts
Adds optional verification codes and a new endpoint for generating verification codes via email 
in accord with https://wearezeta.atlassian.net/wiki/spaces/SER/pages/557580675/Tech+spec+BSI+-+1.8+Improve+User+Authentication
> feat(api-client): adding 2-factor verification codes (SQSERVICES-1158)

- packages/api-client/src/APIClient.test.node.ts
- packages/api-client/src/APIClient.ts
- packages/api-client/src/conversation/ConversationAPI.test.ts
> fix(api-client): Compute backend features based on actual used version

- packages/core/src/main/broadcast/BroadcastService.ts
This will allow sending broadcast message using fully qualified users
> feat(core): Allow sending broadcast message to federated env

- packages/api-client/src/APIClient.ts
- packages/api-client/src/http/HttpClient.ts
Will add the version prefix before any api call request
> feat(api-client): Prefix all api requests with version number

- packages/core/src/main/Account.ts
> fix(core): Do not use qualified session ids in non-federated env

- packages/api-client/src/conversation/ConversationAPI.ts
> fix(api-client): Chunk request to get conversations by qualified ids

- packages/api-client/src/user/UserAPI.ts
> fix(api-client): Chunk user prekeys requests

- packages/api-client/src/http/BackendErrorLabel.ts
> feat(api-client): add new error label for 2fa

- packages/api-client/src/team/feature/Feature.ts
- packages/api-client/src/team/feature/FeatureAPI.ts
- packages/api-client/src/team/feature/FeatureList.ts
> feat: add endpoint for 2ndFactorPassword feature config

- packages/react-ui-kit/src/Form/CodeInput.tsx
> fix(react-ui-kit): fix issue with mobile keyboard

- packages/api-client/src/client/ClientAPI.ts
- packages/core/src/main/client/ClientBackendRepository.ts
- packages/core/src/main/client/ClientService.ts
This adds the MLS endpoints to add keypackages to an MLS capable client. 
Also adds the method to delete a client from the core package
> feat(api-client): Add MLS clients endpoints

- packages/api-client/src/team/feature/Feature.ts
- packages/api-client/src/team/feature/FeatureAPI.ts
- packages/api-client/src/team/feature/FeatureList.ts
> feat(core, api-client): Add MLS team feature config (fs-653)

- packages/core/src/main/Account.ts
- packages/core/src/main/notification/NotificationService.ts
When the computer is disconnected, at some point the access token will  expire and we will need to generate a new one. 
At this point, when the computer is connected again, it tries to connect to the websocket and starts parsing the notification stream **but** the connection to the websocket will fail (because of the token being expired) and trigger an abort.
It will then get a new token and reconnect but the notification stream is already being parsed and there is nothing stopping it. 
It will then be parsed twice and messages decrypted twice. 
This handles the `abort` event sent by the websocket and stops parsing the notification stream if the websocket is disconnected
> fix(core): Abort notification stream handling when websocket is disconnected

- packages/react-ui-kit/src/Form/Button.tsx
> refactor(react-ui-kit): Export ButtonVariant enum

- packages/api-client/src/client/ClientAPI.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/conversation/data/MlsEventData.ts
- packages/api-client/src/http/ContentType.ts
- packages/api-client/src/http/HttpClient.ts
> feat(api-client): Add new MLS endpoints (FS-652)

- packages/api-client/src/team/identityprovider/IdentityProviderAPI.ts
current param for delete idp is not correct. should be purge not force. 
this is not a breaking change, it is a healing one. 🤗
> fix: incorrect param for delete idp (SQSERVICES-1387)

- packages/api-client/src/auth/AuthAPI.ts
This is not a breaking change as the endpoint in question is already removed on the BE side.
> chore: removing dead sso endpoint

- packages/core/package.json
- packages/core/src/main/Account.ts
- packages/core/src/main/util/encryptedStore.test.node.ts
- packages/core/src/main/util/encryptedStore.ts
- yarn.lock
> feat: Add encrypted storage for coreCrypto database key [FS-565]

- packages/api-client/src/APIClient.ts
- packages/api-client/src/asset/AssetAPI.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/services/ServicesAPI.ts
- packages/api-client/src/team/feature/FeatureAPI.ts
- packages/api-client/src/user/UserAPI.ts
- packages/core/src/main/util/encryptedStore.test.node.ts
This is preparation work for supporting backend API v2. (cf. https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/603095166/API+changes+v1+v2)
> feat(api-client): Adapt to api version 2

- packages/core/src/main/conversation/ConversationService.ts
Return correct users when creating mls conversation
> runfix: Return correct users when creating mls conversations

- packages/api-client/src/team/feature/Feature.ts
- packages/api-client/src/team/feature/FeatureAPI.ts
fix for deprecated endpoints, adding mls endpoint
> feat: update feature api

- packages/react-ui-kit/src/Form/Input.tsx
> fix: restore missing data-uie on input

- packages/commons/src/main/util/TypeUtil.test.ts
- packages/commons/src/main/util/TypeUtil.ts
> feat(commons): Add XOR type utility

- packages/react-ui-kit/src/Form/Input.tsx
> fix: toggle password input data-uie-name

- packages/api-client/src/http/BackendErrorLabel.ts
> feat: add new error label

- packages/react-ui-kit/src/Form/Checkbox.tsx
- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Layout/Theme.tsx
- packages/react-ui-kit/src/Misc/IconButton.tsx
- Use capital letters for React components in the theme object
- Add IconButton and its properties to the theme object
- Assign correct color values to the default themes
- Update the component to use the new theme
- Export the variant type
> feat: update icon button to use new theming

- packages/api-client/src/http/BackendErrorLabel.ts
> feat(api-client): add IDP_ISSUER_IN_USE error label (#SQSERVICES-1596)

- packages/api-client/src/team/feature/Feature.ts
- packages/api-client/src/team/feature/FeatureList.ts
> fix: issue with mls typing

- packages/api-client/src/team/feature/FeatureAPI.ts
> fix(api-client): broken mls endpoint

- packages/core/src/main/conversation/ConversationService.ts
> refactor(core): Use bazinga64 for encoding core crypto payload

- packages/react-ui-kit/src/Form/Checkbox.tsx
make custom attribute alignCenter in small case
> resolve warning about camelCase for custom attribute alignCenter(ACC-207)

- packages/api-client/src/conversation/ConversationAPI.ts
- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- [ x ] My code is covered by tests
- [ x ] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes
> feat(core, api-client): Use backend timestamp for mls messages

- packages/core/src/main/Account.ts
Remove client id from core crypto database name
> runfix: Remove client id from core crypto database name

- packages/core/package.json
- packages/core/src/main/Account.ts
- yarn.lock
> feat(core): update core-crypto, pass entropy to crypto-core (FS-682)

- packages/react-ui-kit/src/Form/Select.md
- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/SelectComponents.tsx
> feat: slight style changes for select

- packages/react-ui-kit/src/Form/Select.tsx
> fix: revert small select change

- packages/react-ui-kit/src/Form/SelectComponents.tsx
> fix: issue with data-uie-name

- packages/api-client/src/conversation/Conversation.ts
feat(api-client): add protocol to conversation
> feat(api-client): add protocol to conversation

- packages/react-ui-kit/src/Form/Select.tsx
> runfix(react-ui-kit): use react-select generics

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
remove a federated user from a group
> fix(api-client): remove a federated user from a group

- packages/api-client/src/http/BackendErrorLabel.ts
> feat(api-client): add missing federation error codes

- packages/api-client/src/http/BackendErrorLabel.ts
- packages/api-client/src/team/team/NewTeamData.ts
- packages/api-client/src/team/team/TeamAPI.ts
- packages/api-client/src/team/team/TeamData.ts
> fix: remove/deprecate binding teams

- packages/core/package.json
- packages/core/src/main/conversation/ConversationService/ConversationService.ts
- packages/core/src/main/notification/NotificationService.ts
- yarn.lock
feat: Upgrade @otak/core-crypto from 0.3.0-beta-2 to 0.3.0
> feat: Upgrade @otak/core-crypto from 0.3.0-beta-2 to 0.3.0

- packages/react-ui-kit/src/Form/Button.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Button.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/ButtonLink.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/ErrorMessage.test.tsx.snap
- packages/react-ui-kit/src/GlobalCssVariables.tsx
- packages/react-ui-kit/src/Identity/colors-v2.ts
- packages/react-ui-kit/src/Layout/Theme.tsx
- packages/react-ui-kit/src/Layout/headerMenu/MenuSubLink.tsx
- packages/react-ui-kit/src/Modal/Modal.tsx
- packages/react-ui-kit/src/Text/Link.tsx
- packages/react-ui-kit/src/Text/__snapshots__/Label.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/Link.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/TextLink.test.tsx.snap
- Add theming for primary and tertiary button variant
- Restore link component override props
- Change *petrol* name to *turquoise*
> refactor: update button style to new theme

- packages/react-ui-kit/src/Form/Button.tsx
- packages/react-ui-kit/src/GlobalStyle.tsx
- packages/react-ui-kit/src/Text/Link.tsx
- pass color to svg in tertiary button
- remove styling of links in Globalstyle
> runfix: tweak links and button component

- packages/react-ui-kit/src/Form/Button.tsx
- packages/react-ui-kit/src/Form/Input.tsx
- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/SelectComponents.tsx
- packages/react-ui-kit/src/Form/SelectStyles.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Button.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/ButtonLink.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Input.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
- packages/react-ui-kit/src/GlobalCssVariables.tsx
- packages/react-ui-kit/src/GlobalStyle.tsx
- packages/react-ui-kit/src/Layout/Theme.tsx
- packages/react-ui-kit/src/Text/Link.tsx
- Adjustments to the Select component
- Add missing variables to light and dark theme
- Small tweaks to link and button components
> runfix: style select component and add tweaks for preference tab

- packages/react-ui-kit/src/Form/SelectComponents.tsx
- packages/react-ui-kit/src/GlobalCssVariables.tsx
- packages/react-ui-kit/src/Layout/Theme.tsx
> runfix: correct color for select description

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/core/src/main/conversation/ConversationService/ConversationService.ts
> fix: remove user from proteus conversation

- packages/api-client/src/APIClient.ts
- packages/api-client/src/connection/ConnectionAPI.ts
- packages/api-client/src/connection/UserConnectionList.ts
- packages/bot-api/src/MessageHandler.test.node.ts
- packages/bot-api/src/MessageHandler.ts
- packages/bot-handler-debug/src/AutoConnectHandler.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/connection/ConnectionService.ts
- packages/core/src/main/user/UserService.ts
This reverts commit 849baa0960a751f3f6b5b717abf00bbbc025c178.
> runfix: revert remove deprecated/removed endpoints calls

- packages/core/src/main/notification/NotificationService.ts
> runfix(core): messages not being received on proteus

- packages/react-ui-kit/src/Form/Checkbox.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
- packages/react-ui-kit/src/Text/Link.tsx
- Set accent-color on focus-visible for links
- Set checkbox border width to 2px and add border radius to label
> runfix: address design review acc-79

- packages/api-client/src/conversation/Conversation.ts
- packages/core/src/main/conversation/ConversationService/ConversationService.ts
> feat: Add ability to send external proposal (FS-689)

- packages/core/src/demo/echo.ts
PR just here to have #4391 deployed
> fix: fix demo type errors

- packages/core/src/main/mls/MLSService/MLSService.ts
Removes duplicated code to send MLS commit bundles
> feat: Call clearPendingCommits when commit sending failed on backend

- packages/api-client/src/conversation/Conversation.ts
This data is returned by the backend for mls conversations
> feat: Add cipher_suite to conversation data (FS-881)

- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService/ConversationService.ts
- packages/core/src/main/mls/MLSService/MLSService.ts
- packages/core/src/main/mls/types.ts
- packages/core/src/main/notification/NotificationDatabaseRepository.ts
- packages/core/src/main/notification/NotificationService.ts
- packages/core/src/main/notification/types.ts
- packages/core/src/main/util/fullyQualifiedClientIdUtils.test.node.ts
- packages/core/src/main/util/fullyQualifiedClientIdUtils.ts
Handles incoming external proposal messages
needs https://github.com/wireapp/wire-web-packages/pull/4398
> feat: Handle external proposals

- packages/api-client/package.json
- packages/bazinga64/package.json
- packages/bot-api/package.json
- packages/bot-handler-avs/package.json
- packages/bot-handler-debug/package.json
- packages/bot-handler-uptime/package.json
- packages/bot-handler-wizard/package.json
- packages/certificate-check/package.json
- packages/changelog-bot/package.json
- packages/cli-client/package.json
- packages/commons/package.json
- packages/copy-config/package.json
- packages/core/package.json
- packages/license-collector/package.json
- packages/priority-queue/package.json
- packages/promise-queue/package.json
- packages/react-ui-kit/package.json
- packages/store-engine-bro-fs/package.json
- packages/store-engine-dexie/package.json
- packages/store-engine-fs/package.json
- packages/store-engine-sqleet/package.json
- packages/store-engine-web-storage/package.json
- packages/store-engine/package.json
- packages/webapp-events/package.json
> refactor: add prepare scripts

- bin/testUpdated.js
- package.json
- packages/api-client/package.json
- packages/bazinga64/package.json
- packages/bot-api/package.json
- packages/bot-handler-avs/package.json
- packages/bot-handler-debug/package.json
- packages/bot-handler-uptime/package.json
- packages/bot-handler-wizard/package.json
- packages/certificate-check/package.json
- packages/changelog-bot/package.json
- packages/cli-client/package.json
- packages/commons/package.json
- packages/copy-config/package.json
- packages/core/package.json
- packages/license-collector/package.json
- packages/priority-queue/package.json
- packages/promise-queue/package.json
- packages/react-ui-kit/package.json
- packages/store-engine-bro-fs/package.json
- packages/store-engine-dexie/package.json
- packages/store-engine-fs/package.json
- packages/store-engine-sqleet/package.json
- packages/store-engine-web-storage/package.json
- packages/store-engine/package.json
- packages/webapp-events/package.json
> chore: Stabilise building pipeline

- packages/core/package.json
- yarn.lock
This will fixe issue with handling people leaving an mls conversation
> fix: Upgrade core-crypto

- packages/core/src/main/Account.ts
This will give a clean event API for handling the websocket connection states. We now explicitely call the `onConnectionStateChange` with the appropriate values
BREAKING CHANGE: the `onConnected` callback has been removed in favor of a clean lifecycle event `ConnectionState.LIVE`
> fix: Improve websocket lifecycle hooks reliability

- packages/react-ui-kit/src/Form/Checkbox.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
- packages/react-ui-kit/src/Text/Link.tsx
> fix(react-ui-kit): Address issue with non-standard props passed to DOM elements

- packages/react-ui-kit/src/Form/Checkbox.tsx
- add prop to remove outline offset
> feat: add prop to checkbox component to remove focus outline offset

- packages/api-client/src/notification/NotificationAPI/NotificationAPI.ts
- packages/api-client/src/notification/NotificationAPI/NotificationsAPI.mocks.ts
- packages/api-client/src/notification/NotificationAPI/NotificationsAPI.test.ts
- packages/api-client/src/notification/NotificationAPI/index.ts
> fix: missing messages message bug for failing api calls

- packages/react-ui-kit/src/Form/SelectComponents.tsx
Adds `data-uie-selected="(true/false)"` attribute to select component's option (QA request).
> runfix(react-ui-kit): add missing selector to selected option in select component [SQSERVICES-1762]

- packages/react-ui-kit/src/GlobalStyle.tsx
> fix: font weight on windows pcs (FS-1081)

- packages/react-ui-kit/tsconfig.json
> fix: build of react-ui-kit with tsc

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/mls/MLSService/MLSService.ts
Ability to join a conversation by external commits
> feat: External commits support

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.types.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/WithMockedGenerics.test.ts
[BREAKING CHANGE](https://conventionalcommits.org/#summary): Removed deprecated overwrite of createProteusConversation
> feat: extract mthods from ConversationService into ProteusService

- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.types.ts
Regression was introduced with https://github.com/wireapp/wire-web-packages/pull/4610/files#diff-9f5a9c2c6dca9f04ad718b3ba952cf0c8c3b57f3fc5c850d872293c1e7773b3cR61
> fix: Fix creating new proteus conversations

- packages/api-client/src/user/data/UserPropertiesSetData.ts
- packages/webapp-events/src/index.ts
- Add a property and webapp event for setting the font size in preferences
- see [this ticket](https://wearezeta.atlassian.net/browse/ACC-302) and the linked figma for more information
> feat: add a user setting for font sizes [ACC-302]

- packages/core/package.json
- packages/core/src/Account.ts
- packages/core/src/client/ClientService.ts
- packages/core/src/cryptography/CryptographyService.ts
- yarn.lock
Use core crypto instead of cryptobox for proteus (and mls) client initialisation.
> feat: initialise proteus with core crypto [FS-1096]

- packages/core/src/broadcast/BroadcastService.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/conversation/message/messageSender.ts
- packages/promise-queue/src/PromiseQueue.test.ts
- packages/promise-queue/src/PromiseQueue.ts
This will add the possibility for a consumer to know if a queued message is being sent
> feat: Expose whether a message is being sent 

- packages/react-ui-kit/src/Form/Checkbox.tsx
- packages/react-ui-kit/src/Form/IndicatorRangeInput.styles.ts
- packages/react-ui-kit/src/Form/IndicatorRangeInput.tsx
- packages/react-ui-kit/src/Layout/Theme.tsx
- replace the hard coded color values with theme variables
- adjust the font size to display properly at all width in the app
- refactor the `String` types to `string`
> runfix: use theme variables in font slider

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
Trigger `cryptobox` -> `corecrypto` migration script after initialising proteus client.
> feat: trigger migration from cryptobox to corecrypto [FS-1095]

- packages/api-client/src/conversation/Conversation.ts
- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/data/ConversationAccessUpdateData.ts
Update type definitions in `access_role` field(s) for version 3 of api.
> feat(api-client): api v3 change access_role type definition [FS-1192]

- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/SelectComponents.tsx
- packages/react-ui-kit/src/Text/Link.tsx
- packages/react-ui-kit/src/types/enums.ts
Add Enum for TabIndex values that will also be shared with webapp.
> feat: add enum for TabIndex

- packages/api-client/src/asset/AssetAPI.ts
Add error case for if v3 is called without domain
> fix: update asset api (FS-1001)

- packages/api-client/src/team/member/MemberAPI.ts
- packages/api-client/src/team/member/Role.ts
- packages/api-client/src/team/search/TeamSearchOptions.ts
- packages/api-client/src/team/search/TeamSearchResult.ts
- packages/api-client/src/user/UserAPI.ts
Updates the expected api response from the search endpoint. 
Offers a suggestion for the deprecated getUsers endpoint
> feat: paginated search endpoint (SQSERVICES-1805)

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
> fix: Correctly init new mls client

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/Subconversation.ts
- adds subconversation requests' handlers 
- adds return data type
> feat(api-client): base for subconversations and conference calls [FS-1408]

- packages/api-client/src/conversation/Subconversation.ts
- packages/api-client/src/conversation/index.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
This is the way to initiate or join an mls conference call.
> feat: Add method to join mls conference subconversation

- .github/workflows/lint.yml
- .github/workflows/publish_all.yml
- .github/workflows/test_build_release.yml
see https://github.com/marketplace/actions/yarn-install-cache#deprecated for deprecation warning
> chore: replace deprecated ha-yarn-cache

- packages/react-ui-kit/src/Form/Input.tsx
- packages/react-ui-kit/src/Form/RangeInput.styles.ts
- packages/react-ui-kit/src/Form/SelectStyles.tsx
- packages/react-ui-kit/src/Form/TextArea.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/ErrorMessage.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Input.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/RangeInput.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/TextArea.test.tsx.snap
- packages/react-ui-kit/src/GlobalStyle.tsx
- packages/react-ui-kit/src/Identity/Avatar.tsx
- packages/react-ui-kit/src/Layout/headerMenu/MenuLink.tsx
- packages/react-ui-kit/src/Layout/headerMenu/MenuSubLink.tsx
- packages/react-ui-kit/src/Text/Heading.tsx
- packages/react-ui-kit/src/Text/Text.tsx
- packages/react-ui-kit/src/Text/__snapshots__/Heading.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/Label.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/Paragraph.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/Text.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/TextLink.test.tsx.snap
- There is feedback on font weight in light mode being too thing,  both general and accessibility related
- set default font size to 400 instead of 300
> fix: change default font weight from 300 to 400 [ACC-436]

- packages/core/package.json
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- yarn.lock
> feat: update @wireapp/core-crypto to latest version with ACME support [FS-748]

- packages/api-client/src/APIClient.ts
- packages/api-client/src/generic/GenericAPI.ts
- packages/api-client/src/generic/index.ts
A generic way to access the backend and receive data via api-client
> feat: add generic request for backend calls

- packages/core/src/Account.ts
This will make sure that we use `CoreCrypto` regardless of the userconfig if the user has already used CoreCrypto in the past
> fix: Enable CoreCrypto if user has already started using it

- packages/api-client/src/APIClient.test.ts
- packages/api-client/src/APIClient.ts
- packages/core/src/Account.ts
This will allow us to put `Infinity` as a `max` range of supported version. (need for more flexible dev env)
> feat: More flexible useVersion api

- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/conversation/ConversationService/ConversationService.types.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
Some improvements to adding users to MLS group related code.
> refactor(core): add users to mls conv

- packages/core/src/messagingProtocols/proteus/Utility/Recipients.ts
> refactor: Make recipients fetching code easier to read

- packages/core/src/conversation/ReactionType.ts
- update reaction type to accept string
> feat: update reaction type

- packages/react-ui-kit/package.json
- packages/react-ui-kit/src/Form/Form.md
- packages/react-ui-kit/src/Form/Tooltip.md
- packages/react-ui-kit/src/Form/Tooltip.test.tsx
- packages/react-ui-kit/src/Form/Tooltip.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Tooltip.test.tsx.snap
- packages/react-ui-kit/src/Theme/Theme.tsx
- yarn.lock
> feat(react-ui-kit): Implement new tooltip

- packages/api-client/src/team/feature/Feature.ts
- packages/api-client/src/team/feature/FeatureAPI.ts
- packages/api-client/src/team/feature/FeatureList.ts
Add PUT endpoint for MLS e2e id config updates
> feat: mls E2Eid config

- packages/react-ui-kit/src/Icon/SVGIcon.md
- packages/react-ui-kit/src/Icon/VerificationShieldIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat: add verification shield icon

- packages/cli-client/overrides/core-crypto/index.js
- packages/cli-client/overrides/core-crypto/package.json
- packages/cli-client/package.json
- packages/cli-client/src/index.ts
- yarn.lock
> fix: make cli-client compatible with latest core

- packages/api-client/src/user/UserAPI.ts
this change https://github.com/wireapp/wire-webapp/pull/14923 renders the webapp incompatible wth older versions of the api
Reintrodruce the previous webapp logic in `api-client`: if the response correspond to the old api, map users from the same backend in `found` and all federated users in `failed`
> fix: ensure fetching users is backward compatible [FS-1784]

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/data/ConversationJoinData.ts
Needed for the implementation of the deeplink for joining conversations with a password
> feat: Update getConversationJoin result data (SQSERVICES-1975)

- packages/api-client/src/http/BackendErrorLabel.ts
> refactor: Add missing backend errors

- packages/api-client/src/http/BackendErrorLabel.ts
> feat(api-client): Add invalid conversation password error to BackendError (SQSERVICES-1975)

- package.json
- packages/api-client/package.json
- packages/api-client/src/team/member/Permissions.ts
- packages/api-client/src/team/member/Role.ts
- packages/bazinga64/package.json
- packages/certificate-check/package.json
- packages/commons/package.json
- packages/copy-config/package.json
- packages/core/package.json
- packages/eslint-config/package.json
- packages/license-collector/package.json
- packages/prettier-config/package.json
- packages/priority-queue/package.json
- packages/promise-queue/package.json
- packages/react-ui-kit/package.json
- packages/store-engine-dexie/package.json
- packages/store-engine-fs/package.json
- packages/store-engine/package.json
- packages/webapp-events/package.json
- yarn.lock
> feat: update typescript

- packages/api-client/src/team/feature/Feature.ts
> feat: update mls e2eid feature config

- packages/api-client/src/conversation/Conversation.ts
- [] My code is covered by tests
- [] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes
> feat: Add new failed_to_add field to conversation (FS-1548)

- packages/api-client/src/team/feature/Feature.ts
- packages/api-client/src/team/feature/FeatureAPI.ts
- packages/api-client/src/team/feature/FeatureList.ts
Adds `mlsMigration` to feature list in api client.
> feat(api-client): add mls migration config

- packages/api-client/src/http/BackendErrorLabel.ts
> feat: add new invalid url synthetic error label

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
> feat: Return failed users when sending mls message (FS-2030)

- .github/workflows/test_build_release.yml
> fix(ci): set environment globally to prevent command injection from potentially untrusted input

- package.json
Argument was missing in version bump script
> runfix: include argument in version script

- package.json
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- yarn.lock
- Error thrown by `apiClient.api.conversation.postMlsCommitBundle` is not an instance of axios error, it's BackendError and error code is a number,
- Pending commits should get cleared before retrying to send a commit bundle, not after,
- Add retry option when processing any commit action
> runfix: upload commit bundle

- packages/api-client/src/client/ClientAPI.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
> fix(api-client,core): Handle failure to fetch keypackages (WPB-1913)

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/user/UserAPI.ts
- fetch MLS 1:1 conversation
- fetch the list supported protocols by user id
> feat(api-client): 1to1 mls conversations

- packages/core/package.json
- yarn.lock
Bump core crypto to version 1.0.0-rc.6
> feat: bump core crypto to version 1.0.0-rc.6

- packages/api-client/src/event/BackendEvent.ts
- packages/api-client/src/event/FederationEvent.ts
- packages/api-client/src/federation/data/FederationConnectionRemovedData.ts
- packages/api-client/src/federation/data/FederationDeleteData.ts
- packages/api-client/src/federation/data/index.ts
- packages/webapp-events/src/index.ts
> feat(api-client, webapp-events): add federation delete & connection remove events (WPB-203)

- packages/api-client/src/event/FederationEvent.ts
> fix: change data shape of federation events (WPB-203)

- packages/api-client/src/APIClient.ts
MLS has been pushed to api v5 and removed from v4
> fix: Finalize backend api v4

- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
This will fix a bug where:
if there are users from an offline backend (`B`) and you try to add users from `A` which is a backend that doesn't exist in the conversation already, the users from `A` (even if A is up and running) cannot be added. 
In this case the POST request to `/members` will fail twice and we will handle it as if `A` was an offline backend
> feat: Gracefully error when adding users with offline backend

- packages/bazinga64/README.md
- packages/bazinga64/src/Converter.test.ts
- packages/bazinga64/src/Converter.ts
- packages/core/package.json
- yarn.lock
add another converter function needed for E2EI (for now) and update the readme
> feat: add description and hexStringToArrayBufferView converter

- packages/core/package.json
- yarn.lock
Bumps corecrypto to the latest version.
> feat: bump corecrypto to latest version

- packages/core/src/conversation/ConversationService/ConversationService.ts
Adds a method for removing a conversation from the blacklist.
> feat: remove conversation from blacklist

- packages/api-client/src/APIClient.ts
- packages/core/src/Account.ts
Before initialising mls service, check whether a removal key is available on backend.
> feat: check if removal key is available on backend

- packages/core/package.json
- yarn.lock
> feat: bump core-crypto

- packages/react-ui-kit/src/Form/Select.md
- packages/react-ui-kit/src/Form/SelectStyles.tsx
Adjusting group styles for some design feedback/ theming.
> feat: update select group styles

- packages/core/package.json
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Helper/index.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/mls/utils/MLSId.ts
- yarn.lock
Will add the `getUserIdentity` method that will return the identity of a user in a conversation
> feat: Add user identity query 

- packages/react-ui-kit/src/Form/Select.md
- packages/react-ui-kit/src/Form/SelectStyles.tsx
> feat: update max-height for select menu

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
The problem was that we have 3 cases now:
- New User -> Regular Flow and wire Identity for the process -> flow exists
- Existing User with invalid OAuth refresh token -> Regular flow with different wire identity for the process -> flow exists
- Existing User with valid refresh token -> This case was missing and could not be done by the existing flow -> this has been added trough the PR
> feat(E2EI): add refresh flow to E2EIServiceInternal

- packages/api-client/package.json
- packages/api-client/src/http/HttpClient.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- yarn.lock
Adds exponential backoff algorithm when request has failed with 420 too many requests error.
> feat: exponential backoff

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
Logic was flawed before, now returns the value it should.
> fix(e2ei): return value of isFreshMLSSelfClient

- packages/api-client/src/team/feature/Feature.ts
- packages/api-client/src/team/feature/FeatureAPI.ts
- packages/api-client/src/team/feature/FeatureList.ts
- packages/webapp-events/src/index.ts
> feat: update types for download path

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Public keys need to be uploaded only once the certification process is first done. Then it should not change after renewal
> fix: Do not upload public keys when renewing certificate

- packages/core/package.json
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/schema.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIService.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/Authorization.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/DpopChallenge/DpopChallenge.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/DpopChallenge/DpopChallenge.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/OidcChallenge.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Storage/E2EIStorage.schema.ts
- yarn.lock
In core-crypto rc31, now challenges are created in 2 steps
> feat: Upgrade CoreCrypto to 1.0.0-rc.31

- packages/core/package.json
- yarn.lock
Bumps core-crypto version to rc32
> feat: bump core-crypto to rc32

- packages/core/package.json
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- yarn.lock
Rollback to cc 33 until version 34 is not fixed (We're hitting error 500 on acme server).
> runfix: rollback to cc 33

- packages/core/package.json
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIService.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.types.ts
- yarn.lock
see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md#100-rc35---2024-01-29 for CoreCrypto changelog
> feat: Upgrade to coreCrypto rc36 to support crl distribution points

- packages/core/package.json
- yarn.lock
> fix(core): Remove unneeded dexie-store-engine dependency

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIService.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
> refactor: streamline e2ei enrollment flow

- packages/core/package.json
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- yarn.lock
see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md#100-rc40---2024-02-20
> chore: Upgrade to CoreCrypto rc40

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
Will make sure all the initialization code is gathered under the `initialize` method
> refactor: Improve e2eidentity initialization method

- packages/core/package.json
- yarn.lock
see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md#100-rc40---2024-02-20
> fix: Upgrade CoreCrypto to rc41

- packages/core/package.json
- yarn.lock
see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md#100-rc45---2024-02-28
> fix: Address non-e2ei device not being able to join conversations

- packages/core/package.json
- yarn.lock
see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md#100-rc45---2024-02-28
> fix: Upgrade core-crypto to rc46

- packages/commons/src/util/Runtime.ts
Adds some Runtime vars to make our device lists more readable
> chore(dx): add runtime vars for dev devices

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
Adds a method to fetch MLS Self conversation from backend.
> feat: add method to fetch self mls conversation

- packages/api-client/package.json
- packages/core/package.json
- yarn.lock
Updating some deprecated packages.
> chore: update protocol-messaging deps

- packages/core/package.json
- yarn.lock
Bumps corecrypto with version that fixes some CRL bugs.
> runfix: bump corecrypto with some CRL fixes

- packages/core/package.json
- yarn.lock
see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md
> fix: Improve E2EI basic device handling

- packages/core/package.json
- yarn.lock
see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md#100-rc50---2024-03-11
> fix: Address revoked clients not being detected

- packages/core/__mocks__/@wireapp/core-crypto.ts
- packages/core/package.json
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIService.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- yarn.lock
see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md#100-rc51---2024-03-13
> fix: Address revoked devices not being detected

- packages/core/package.json
- yarn.lock
see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md#100-rc52---2024-03-14
> fix: Address federated crl distribution points not being detected

- packages/core/src/conversation/AssetService/AssetService.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/cryptography/AssetCryptography/AssetCryptography.test.ts
- packages/core/src/cryptography/AssetCryptography/AssetCryptography.ts
- packages/core/src/cryptography/AssetCryptography/index.ts
This will allow the consuming app to decrypt assets as they are being downloaded
> feat(core): Allow downloading and decrypting assets

- packages/api-client/src/user/data/UserPropertiesSetData.ts
- packages/webapp-events/src/index.ts
Add push to talk event and property value - this will allow us to enable/disable/change push to talk feature config value on webapp.
> feat: add call push to talk properties events

- .github/workflows/generate_test_report.yml
Adds a manual dispatch with exact commit SHA to generate test report job.
> chore: use manual commit input

- packages/react-ui-kit/package.json
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
- yarn.lock
> chore: downgrade the react-select to 5.7.7 to avoid `role="log"` WPB-7240

- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/SelectComponents.tsx
Adds ability to extend the default styles of select's menu component.
> feat: add ability to extend select menu styles

- .github/workflows/generate_test_report.yml
- packages/copy-config/tsconfig.json
Saves test reports to our s3 bucket.
> chore: save unit tests results to s3 bucket

- packages/core/src/conversation/SubconversationService/SubconversationService.ts
see https://wearezeta.atlassian.net/wiki/spaces/PAD/pages/1314750477/2024-07-29+1+1+calls+over+SFT#Do-not-leave-the-subconversation
This fixes an issue where 1:1 call over SFT would not be terminated if a participant leaves.
A decision has been made to call the `DELETE /conversations/:domain/:uuid/subconversations/conference` endpoint (Backend deletes the subconversation)i n that scenario instead of `DELETE /conversations/:domain/:uuid/subconversations/conference/self` endpoint (remove the user from the subconversation).
This prevents a subconversation to remain active when all participants attempt to leave
> fix: handle leaving a 1:1 call over SFT [WPB-7151]

- packages/core/package.json
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Helper/index.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- yarn.lock
> feat: update cc to 1.0.2

- packages/react-ui-kit/src/Layout/MatchMedia.tsx
[WPB-10675
](https://wearezeta.atlassian.net/browse/WPB-10675)
Updated useMatchMedia to handle isMatching state update when customWindowObj changes.
> fix: isMatching not updating in useMatchMedia [WPB-10675]

- packages/api-client/src/team/invitation/TeamInvitationAPI.ts
Added accept invitation endpoint in apiClient
> feat(user-migration): add accept invitation call in apiClient [WPB-11128]

- packages/core/src/conversation/message/MessageBuilder.ts
Added new field to let the other platforms know what to do with the message if they don't know it yet.
> feat: Add unknown strategy to in call reactions message (WPB-11750)

- packages/api-client/src/team/invitation/TeamInvitationAPI.ts
- packages/api-client/src/team/invitation/TeamMigrationPayload.ts
Add upgrade to personal user api call
> feat: add upgrade to personal user api call [WPB-11269]

- packages/telemetry/adr/001-initialize-library.md
> docs(telemetry): update 001-initialize-library adr status

- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
See: https://github.com/wireapp/wire-webapp/pull/18298
> feat(core): Throw error on crypto box migration failure (WPB-11409)

- packages/core/package.json
- yarn.lock
bumps core-crypto to 1.1.0 to fix a bug
> feat: update cc [WPB-14325]

- packages/api-client/src/APIClient.ts
- packages/api-client/src/auth/AccessTokenStore.ts
- packages/api-client/src/http/HttpClient.ts
- packages/api-client/src/shims/node/cookie.ts
- packages/api-client/src/tcp/ReconnectingWebsocket.ts
- packages/api-client/src/tcp/WebSocketClient.ts
- packages/commons/src/LogFactory.ts
- packages/commons/src/util/StringUtil.ts
- packages/core/src/Account.ts
- packages/core/src/client/ClientService.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.ts
- packages/core/src/cryptography/GenericMessageMapper.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/AcmeService.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/IncomingMessagesQueue/IncomingMesssagesQueue.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/notification/NotificationService.ts
- packages/core/src/self/SelfService.ts
- packages/core/src/util/LowPrecisionTaskScheduler/LowPrecisionTaskScheduler.ts
- packages/core/src/util/TaskScheduler/TaskScheduler.ts
See https://github.com/wireapp/wire-webapp/pull/18359
> feat(core, api-client): Serialize object arguments in desktop runtime

- packages/core/package.json
- yarn.lock
> feat: update cc to 1.1.1 [wpb-14325]

- packages/core/package.json
- yarn.lock
Bump core crypto to 1.1.2
Improve logs by providing information contained in `rust_stack_trace`
> runfix(core-crypto): improve core crypto error logs [WPB-14556]

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/user/UserAPI.ts
the endpoint changes are as follow:
- renamed POST /users/handles → POST /handles
- renamed HEAD /users/handles → HEAD /handles
- renamed POST /conversations/bots → POST /bot/conversations
- renamed DELETE /conversations/bots → DELETE /bot/conversations
- renamed POST /conversations/one2one → POST /one2one-conversations
- renamed GET /conversations/one2one → GET /one2one-conversations
see https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/1309868033/API+changes+v6+v7
> feat(api-client): implement v7 endpoint changes [WPB-14542]

- packages/api-client/src/oauth/OAuthAPI.ts
- packages/api-client/src/team/invitation/TeamInvitation.ts
- packages/api-client/src/team/scim/ScimAPI.ts
- packages/api-client/src/team/scim/ScimTokenInfo.ts
Changed some more endpoints to make sure web is incorporating everything leading up to v7
> feat: updating endpoints to fulfill v7 BE plans [WPB-14768]

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
A missing slash was discovered during the playtest session
> runfix: address playtest review for api v7

- packages/core/package.json
- yarn.lock
Bump core-crypto to the latest major version
see release notes here https://github.com/wireapp/core-crypto/releases/tag/v2.0.0
> feat: update core-crypto to 2.0.0 [WPB-11654]

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/CoreCryptoMLSError.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/CoreCryptoWrapper.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/DecryptionErrorGenerator/DecryptionErrorGenerator.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/DecryptionErrorGenerator/DecryptionErrorGenerator.ts
Description:
This PR connects the core crypto logging mechanism to our existing log system. It uses the setLogger method to register a callback (coreCryptoLogger) that forwards log messages from core crypto to our logging framework.
Key changes:
Implemented a coreCryptoLogger to map core crypto log levels to our logger.
Used logFunctions to ensure proper handling of different log levels (DEBUG, INFO, WARN, ERROR, etc.).
Configured the log level to INFO using the setMaxLogLevel method.
This integration ensures that core crypto logs are forwarded to the client’s native log system with appropriate levels and context for easier debugging and monitoring.
> feat: Integrate core crypto logger (WPB-14636)

- packages/webapp-events/src/index.ts
Add events for the notification changes https://github.com/wireapp/wire-webapp/pull/18476
> feat(webapp-events): add call hand raised and screen sharing ended events [WPB-8580]

- packages/api-client/src/user/data/UserPropertiesSetData.ts
- packages/webapp-events/src/index.ts
Add events for press space to unmute, removed push_to_talk_key events, we're not gonna use them anymore
> feat: events for press space to unmute [WPB-8580]

- packages/api-client/src/user/data/UserPropertiesSetData.ts
- packages/webapp-events/src/index.ts
Reverts wireapp/wire-web-packages#6753
> runfix: revert "feat: events for press space to unmute [WPB-8580]"

- packages/api-client/src/user/data/UserPropertiesSetData.ts
- packages/webapp-events/src/index.ts
Add events for press space to unmute, removed push_to_talk_key events, we're not gonna use them anymore
> feat: events add push to talk v2  [WPB-8580]  

- packages/core/src/Account.ts
- packages/core/src/team/TeamService.ts
Fix an issue with creating MLS clients even tho the Feature_Flag was diabled
> !fix(MLS): check feature flag before creating MLS clients [WPB-15020]

- packages/api-client/src/user/data/UserPropertiesSetData.ts
- packages/webapp-events/src/index.ts
Add events for markdown preview for rich text editor
> feat: markdown preview events [WPB-15101]

- packages/telemetry/package.json
Updated telemetry version to 0.2.0
> fix: updated telemetry version to 0.2.0

- packages/react-ui-kit/src/Icon/BlockquoteIcon.tsx
- packages/react-ui-kit/src/Icon/CodeBlockIcon.tsx
- packages/react-ui-kit/src/Icon/CodeInlineIcon.tsx
- packages/react-ui-kit/src/Icon/SVGIcon.md
- packages/react-ui-kit/src/Icon/index.ts
> feat: add Blockquote and CodeBlock icons [WPB-15264]

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
Removed unwanted curly bracket from conversation API URL
> fix: removed unwanted curly bracket from conv API URL [WPB-11925]

- packages/react-ui-kit/src/Form/Select.md
- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/SelectComponents.styles.ts
- packages/react-ui-kit/src/Form/SelectComponents.tsx
We need those changes as a part of that ticket https://wearezeta.atlassian.net/browse/WPB-3307
Screenshot from Figma
More info (Figma): https://www.figma.com/design/jnygr7PEOk1yHgjBF18udc/Desktop?node-id=4079-132857&node-type=section&t=9IoB8mLop8btzhae-0
> feat(react-ui-kit): add menuListHeading inside Select [WPB-3307]

- packages/core/package.json
- yarn.lock
> feat: update CC

- packages/react-ui-kit/src/Icon/PlayIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit): play icon [WPB-15809]

- packages/react-ui-kit/src/Icon/PauseIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit): pause icon [WPB-15809]

- packages/core/package.json
- yarn.lock
> feat: bump CC to 3.1  [WPB-16027]

- packages/react-ui-kit/adr/001-replace-styleguideist-with-storybook.md
Changing adr status to "Accepted"
> chore(react-ui-kit): accept 001-replace-styleguideist-with-storybook.md

- packages/react-ui-kit/src/Icon/SaveIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit): save icon [WPB-16106]

- packages/api-client/src/account/DomainRedirect.ts
Updated DomainRedirectPayload type, removed `due_to_existing_account` for sso and backend.
> fix: update DomainRedirectPayload type

- packages/react-ui-kit/src/Icon/OpenDetachedWindowIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
[Figma](https://www.figma.com/design/IcPEaWJZxUqZiIbCVDZLDR/Icons-and-Logo?node-id=2169-111&t=NesMCo14ATrnPRe1-4)
> feat(react-ui-kit): open detached window icon [WPB-16170]

- packages/api-client/src/cells/CellsAPI.ts
Changes the file path for the cells api upload.
> fix(api-client/cells): upload path

- packages/api-client/src/cells/CellsAPI.test.ts
> fix(api-client/cells): tests

- packages/react-ui-kit/src/Icon/CloseDetachedWindowIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
[Figma](https://www.figma.com/design/IcPEaWJZxUqZiIbCVDZLDR/Icons-and-Logo?node-id=2169-110&t=M05RZsYOv83rYl32-4)
> feat(react-ui-kit): close detached window icon [WPB-16170]

- packages/react-ui-kit/src/Icon/CloseDetachedWindowIcon.tsx
> fix(react-ui-kit): update CloseDetachedWindowIcon SVG attributes

- packages/api-client/package.json
- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- yarn.lock
Update cells-sdk to v0.1.1-alpha06
> feat(api-client/cells): update cells sdk to v0.1.1-alpha06

- packages/react-ui-kit/src/Icon/CollectionIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit/icon): add CollectionIcon

- .gitignore
Ignores the yalc files in `.gitignore`
> chore(gitignore): ignore yalc files

- packages/api-client/package.json
- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- yarn.lock
Updates cells sdk to alpha 07 + added searchFiles method
> feat(api-client/cells): update cells sdk to alpha 07 + searchFiles method

- packages/react-ui-kit/src/Icon/ChannelIcon.tsx
- packages/react-ui-kit/src/Icon/LockClosedIcon.tsx
- packages/react-ui-kit/src/Icon/ShieldIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
Added channel, shield and lock icons
> feat: add channel, shield and lock icons

- packages/core/src/conversation/content/ContentType.guards.ts
- packages/core/src/conversation/content/ConversationContent.ts
- packages/core/src/conversation/content/MultipartContent.ts
- packages/core/src/conversation/content/index.ts
- packages/core/src/conversation/message/MessageBuilder.ts
- packages/core/src/conversation/message/OtrMessage.ts
- packages/core/src/conversation/message/PayloadBundle.ts
- packages/core/src/cryptography/GenericMessageMapper.ts
Introduces a new message type "multipart", which will be used to develop the cells feature
> feat(core): multipart message [WPB-16551]

- packages/api-client/src/conversation/Conversation.ts
- packages/api-client/src/conversation/NewConversation.ts
- packages/api-client/src/team/feature/Feature.ts
- packages/api-client/src/team/feature/FeatureList.ts
Updated feature config and POST /conversations payload for channels
> feat: update feature config and POST /conversations payload for channels [WPB-15758]

- packages/react-ui-kit/src/Icon/UnavailableFileIcon.tsx
> runfix(react-ui-kit/icon): UnavailableFileIcon fill

- packages/api-client/src/team/feature/FeatureAPI.ts
Added API wrapper for updating channels feature config
> feat: add API wrapper for updating channels feature config [WPB-16603]

- packages/api-client/package.json
- packages/api-client/src/cells/CellsAPI.ts
- packages/api-client/src/cells/CellsStorage/CellsStorage.ts
- packages/api-client/src/cells/CellsStorage/S3Service.test.ts
- packages/api-client/src/cells/CellsStorage/S3Service.ts
- packages/core/package.json
- yarn.lock
Implements file upload progress.
> feat(api-client/cells): file upload progress [WPB-16866]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- packages/api-client/src/cells/CellsStorage/CellsStorage.ts
- packages/api-client/src/cells/CellsStorage/S3Service.test.ts
- packages/api-client/src/cells/CellsStorage/S3Service.ts
Added support for abord signal in the uploadFileDraft fn
> feat(api-client/cells): add support for abort signal [WPB-16843]

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/data/ConversationAddPermissionUpdateData.ts
- packages/api-client/src/event/ConversationEvent.ts
Added api wrapper for add_permissions update call
> feat: add api wrapper for add_permissions update call [WPB-16728]

- packages/api-client/src/conversation/NewConversation.ts
Add the `cells` option to create a new cell conversation. 
API docs - https://nginz-https.imai.wire.link/v9/api/swagger-ui/#/default/create-group-conversation
> feat(api-client/conversation): add the cells option [WPB-16965]

- packages/core/src/conversation/ConversationService/ConversationService.ts
typo createMLSConvcersation => createMLSConversation (caused by https://github.com/wireapp/wire-web-packages/pull/7004)
> fix(ConversationService): correct typo

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
Remove additional protocol check while inviting users
> fix: remove additional protocol check while inviting users [WPB-16998]

- packages/api-client/src/cells/CellsAPI.ts
> feat(CellsAPI): rename cells search sort param

- packages/api-client/src/cells/CellsAPI.ts
Reverts wireapp/wire-web-packages#7014
> revert: "feat(CellsAPI): rename cells search sort param"

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
This reverts commit 8d36900240f474638ee58c3e12de10063ddcbafd.
> revert: "feat(CellsAPI): add sorting parameters to searchFiles() method (#7013)"

- packages/api-client/src/http/HttpClient.ts
This reverts commit 39818b5cea41dffea46fa74d8ee046fa5b7e1d12.
> revert: "feat: include api versioning to endpoints with credentials [WPB-16119] (#7012)"

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
> feat(cells): api search sorting

- packages/api-client/src/http/HttpClient.ts
This reverts commit 0978e39549713646023feb3c1997f21de3cb05fc.
> feat: Revert "revert: "feat: include api versioning to endpoints withcredentials [WPB-16119] (#7012)" (#7017)"

- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/SelectStyles.tsx
Adding additional css props for the select component
> feat(react-ui-kit/Select): add additional css props [WPB-16997]

- .github/workflows/generate_test_report.yml
`awscli` come preinstalled in gitbub action containers and running the install script is unnecessary
> chore(gh-actions): use preintalled awscli

- .github/workflows/generate_test_report.yml
> Merge main into release/q2-2025

- packages/react-ui-kit/src/Icon/SidebarActiveIcon.tsx
- packages/react-ui-kit/src/Icon/SidebarInactiveIcon.tsx
- packages/react-ui-kit/src/Icon/SidebarUnactiveIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit/icon): sidebar icons [WPB-15678]

- packages/react-ui-kit/src/Icon/ChevronDownIcon.tsx
- packages/react-ui-kit/src/Icon/ChevronUpIcon.tsx
- packages/react-ui-kit/src/Icon/ZoomInIcon.tsx
- packages/react-ui-kit/src/Icon/ZoomOutIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit/icon): chevron and zoom icons

- packages/api-client/package.json
- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- yarn.lock
> feat(react-ui-kit/api-client): bump cells SDK to alpha10 and re-adapt payloads

- packages/react-ui-kit/src/Icon/HamburgerIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat: add hamburger icon [WPB-17114]

- packages/react-ui-kit/src/Icon/Files/AudioFileIcon.tsx
- packages/react-ui-kit/src/Icon/Files/CodeFileIcon.tsx
- packages/react-ui-kit/src/Icon/Files/DocumentFileIcon.tsx
- packages/react-ui-kit/src/Icon/Files/MultipleFilesIcon.tsx
- packages/react-ui-kit/src/Icon/Files/PdfFileIcon.tsx
- packages/react-ui-kit/src/Icon/Files/TextFileIcon.tsx
> fix(react-ui-kit/icon): adjust file icon sizes

- packages/react-ui-kit/src/Form/Button.tsx
- packages/react-ui-kit/src/Misc/ButtonGroup.tsx
- packages/react-ui-kit/src/Misc/IconButton.tsx
- packages/react-ui-kit/src/Modal/DropdownMenu/DropdownMenu.stories.tsx
- packages/react-ui-kit/src/Modal/DropdownMenu/DropdownMenu.tsx
1. Adds forwardRef to Button, ButtonGroup, and IconButton components
2. Conditionaly adds styles to DropdownMenu trigger
> fix(react-ui-kit): dropdown menu composition trigger

- packages/api-client/package.json
- yarn.lock
Bump `cells-sdk` to v0.1.1-alpha11 and `axios` to v1.9.0
> feat(api-client): bump cells-sdk to v0.1.1-alpha11

- packages/react-ui-kit/src/Misc/Badge/Badge.stories.tsx
- packages/react-ui-kit/src/Misc/Badge/Badge.styles.ts
- packages/react-ui-kit/src/Misc/Badge/Badge.tsx
A new `Badge` component. It's going to be used for the Wire Cells.
> feat(react-ui-kit): Badge [WPB-17811]

- packages/react-ui-kit/src/Misc/Badge/index.ts
- packages/react-ui-kit/src/Misc/index.ts
> fix(react-ui-kit): Badge export [WPB-17811]

- packages/api-client/package.json
- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- yarn.lock
> feat(CellsAPI): tags [WPB-17811]

- packages/react-ui-kit/package.json
- packages/react-ui-kit/src/Misc/Accordion/Accordion.stories.tsx
- packages/react-ui-kit/src/Misc/Accordion/Accordion.tsx
- packages/react-ui-kit/src/Misc/Accordion/AccordionItem/AccordionItem.styles.ts
- packages/react-ui-kit/src/Misc/Accordion/AccordionItem/AccordionItem.tsx
- packages/react-ui-kit/src/Misc/Accordion/index.ts
- yarn.lock
Adds `Accordion` component.
https://github.com/user-attachments/assets/94aadc66-792f-4f8a-a514-668b90616c4b
> feat(react-ui-kit): Accordion component

- packages/react-ui-kit/src/Misc/Accordion/AccordionItem/AccordionItem.styles.ts
Adjust the `Accordion` spacing + display line for the last element.
> fix(react-ui-kit): Accordion spacing

- packages/api-client/src/team/billing/BillingAPI.ts
Added `GET billing/plan/available` API call
> feat: add GET billing/plan/available API call [WPB-18092]

- packages/react-ui-kit/src/Identity/GlobalCssVariables/GlobalCssVariables.tsx
- packages/react-ui-kit/src/Surface/DropdownMenu/DropdownMenu.styles.ts
> feat(react-ui-kit): DropdownMenu padding & background [WPB-18354]

- packages/react-ui-kit/src/Identity/GlobalCssVariables/GlobalCssVariables.tsx
Fix `--dropdown-menu-bg` color
> fix(react-ui-kit): dropdown menu bg color

- packages/react-ui-kit/src/Navigation/Breadcrumbs/BreadcrumbItem/BreadcrumbItem.styles.ts
- packages/react-ui-kit/src/Navigation/Breadcrumbs/BreadcrumbItem/BreadcrumbItem.tsx
- packages/react-ui-kit/src/Navigation/Breadcrumbs/Breadcrumbs.stories.tsx
Fix breadcrumbs padding when there's only one item
> fix(react-ui-kit): Breadcrumbs padding [WPB-18354]

- package.json
- packages/api-client/src/tcp/ReconnectingWebsocket.ts
- packages/api-client/src/tcp/WebSocketClient.ts
- packages/core/src/Account.ts
- packages/react-ui-kit/package.json
- yarn.lock
we shouldn't send ping to the new async notifications sockets otherwise the backend will close the connection
> feat(api-client): Do not ping async notifications socket

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/IncomingProposalsQueue/IncomingProposalsQueue.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/IncomingProposalsQueue/index.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.ts
This reverts commit 7c1c7229db393363b6fe0fc2ce298982970d7e84.
> fix(core): Revert "Revert "fix(core): Queue incoming pending MLS proposals [WPB-18995] (#7102)" (#7105)"

- packages/core/src/Account.ts
- Sonarqube warnings that got fixed in the process
* Added `try-catch` blocks and error logging to the `wipeCommonData`, `wipeAllData`, and `wipeCryptoData` methods to ensure any failures during logout cleanup are captured and logged.
> fix: try deleting every kind of dataset even if an error happens [WPB-19348]

- packages/react-ui-kit/src/Inputs/ButtonGroup/ButtonGroup.tsx
Update the button inside the ButtonGroup to the Custom button so that it can adopt colours according to the theme.
https://github.com/user-attachments/assets/83711d98-95d6-4910-b612-ccd56f005e2a
> feat: update ButtonGroup to adapt colours according to dark/light theme [WPB-20282]

- packages/react-ui-kit/src/Inputs/ButtonGroup/ButtonGroup.tsx
Replace the attribute name from :first-child to :first-of-type
> feat(react-ui-kit): update attribute from :first-child to :first-of-type [WPB-20283]
