wireapp/wire-web-packages

- packages/store-engine/webpack.config.js
…th npm's "setimmediate" package
> fix(store-engine): Use Dexie from window namespace to avoid errors with npm's "setimmediate" package

- packages/lru-cache/src/main/LRUCache.ts
- yarn.lock
A function which returns all data, doesn't need parameters.
> fix(lru-cache): remove parameters for getAll

- packages/react-ui-kit/package.json
- packages/react-ui-kit/src/Form/Input.jsx
- yarn.lock
`btoa` is not available in Node.js, so we use `bazinga64` because we need to run the React UI Kit inside Node.js to be able to create server-side rendered webpages.
> refactor(react-ui-kit): Replace "btoa" with "bazinga64"

- packages/core/src/main/Account.ts
While this is fixing a short time issue we should clarify where we want to handle, save and map the different OTR message types.
> fix(core): Pass empty content in decodeEvent when message text is empty

- packages/api-client/src/main/http/HttpClient.ts
This partly reverts commit [`c3212e2`](https://github.com/wireapp/wire-web-packages/commit/c3212e2567148b48839099c82a785096e1db5bfe#diff-95d5338bd6a14015ed940d49cdf48d16) which introduced a bug in sending messages by not returning the whole error so the `core` couldn't check for missing prekeys.
> fix(api-client): Return complete error

- packages/api-client/CHANGELOG.md
- packages/api-client/webpack.browser.js
- packages/bazinga64/CHANGELOG.md
- packages/cbor/CHANGELOG.md
- packages/cli-client/CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/cryptobox/CHANGELOG.md
- packages/cryptobox/webpack.config.js
- packages/lru-cache/CHANGELOG.md
- packages/priority-queue/CHANGELOG.md
- packages/proteus/CHANGELOG.md
- packages/react-ui-kit/CHANGELOG.md
- packages/store-engine/CHANGELOG.md
- packages/travis-bot/CHANGELOG.md
According to the [docs](https://webpack.js.org/configuration/target/) `web` is the default value for `target`.
> chore: Remove default webpack target

- packages/travis-bot/src/main/cli.ts
... otherwise the bot would always send `undefined` as conversation ID if it was provided as environment variable and not as CLI argument.
> fix(travis-bot): Only read conversation ID if it is provided

- packages/core/src/main/conversation/ConversationService.ts
We don't need to upload an asset for sending a ping.
> fix(core): Don't send external message for ping

- packages/core/src/main/conversation/ConversationService.ts
Since we don't send the `from` field anywhere and use it only locally, we can return the content as the other side would receive it (which is the user ID in the `from` field).
> refactor(core): Return userId in PayloadBundle

- packages/cryptobox/package.json
When installing `@wireapp/cryptobox` from npm, `bazinga64` is not installed since none of the sub-dependencies have it as dependency but it is required in [`src/main/Cryptobox.ts`](https://github.com/wireapp/wire-web-packages/blob/8b522bd2e0917438f4aa54d0872654a89700de95/packages/cryptobox/src/main/Cryptobox.ts#L24).
> fix(cryptobox): Add missing dependency

- tsconfig.json
- tslint.json
See https://github.com/palantir/tslint/issues/1481.
> chore: no-unused-variable is deprecated in TSLint

- packages/core/src/main/Account.test.node.js
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/PayloadBundle.ts
To make our API a bit neater, this PR turns the following signature:
```ts
private async handleEvent(event: IncomingEvent): Promise<PayloadBundleIncoming | IncomingEvent | void>
```
Into:
```ts
private async handleEvent(event: IncomingEvent): Promise<PayloadBundleIncoming | void>
```
> refactor(core): Reduce amount of return types for "handleEvent"

- lerna.json
- package.json
- ~~[ ] My code is covered by tests~~
The npm registry is already defined in our `.npmrc` file and lerna will automatically resolve it from there. :)
> refactor: Use lerna.json over npm scripts

- packages/api-client/src/main/http/HttpClient.ts
With a default filesize limit of 10mb we can't upload large assets.
> fix(api-client): Increase maximum content length

- lerna.json
With Lerna v3 the "lerna" property is optional: https://github.com/lerna/lerna/issues/1546#issuecomment-411095945
> chore: Remove optional lerna property

- packages/core/src/demo/echo.js
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService.test.node.js
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/content/ConversationContent.ts
- packages/core/src/main/conversation/content/EditedTextContent.ts
- packages/core/src/main/conversation/content/LinkPreviewContent.ts
- packages/core/src/main/conversation/content/TextContent.ts
This PR will
* add a new type `LinkPreviewUploadedContent` to differentiate between link previews with uploaded image assets and without.
* let `createLinkPreview()` accept an object instead of 8 parameters.
* remove `Article` since it's deprecated.
* rename `linkPreview` in a PayloadBundle to `linkPreviews` since it's an array.
* expose the Asset API.
> fix(core): Linkpreview title, expose Asset API (WEBFOUND-34)

- packages/api-client/src/main/http/HttpClient.ts
The changes from #967 have unwanted side effects. Not all 403s indicate an outdated access token. The refresh causes unexpected behavior when ibis related requests are at stake. We are adding a check for the label indicating the invalid access token.
> fix: Check for invalid credentials label to trigger access token refresh

- packages/lru-cache/src/demo/demo.html
- packages/lru-cache/src/main/LRUCache.ts
- packages/lru-cache/test/specs/LRUCacheSpec.js
Given we have a message cache like:
```ts
const messageCache = new LRUCache();
messageCache.add(...);
```
Instead of using:
```ts
const messages = messageCache.getAll();
for (const messageObject of messages) {
const objectId = Object.keys(message)[0];
const message = messageObject[objectId];
// do something with the message
}
```
we can now iterate over the messages:
```ts
for (const message of messageCache) {
// do something with the message
}
```
> refactor(lru-cache): Implement iterator and getAll returns object (BREAKING)

- packages/core/src/main/conversation/ConversationService.ts
iOS currently only renders link previews which have the [deprecated](https://github.com/wireapp/generic-message-proto/blob/master/proto/messages.proto#L65) `Article` set.
> fix(core): Add Article for old iOS devices (WEBFOUND-42)

- yarn.lock
The latest version of `yarn` introduced some changes to the lock file format. Travis is using the latest version and thus never publishes because of a changed yarn lock file.
~~- [ ] My code is covered by tests~~
~~- [ ] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes~~
> chore: Update yarn lockfile

- package.json
`husky` 1.0.0 has changed the way of adding precommit hooks. See https://github.com/typicode/husky#upgrading-from-014.
> fix: Add new husky precommit hook

- packages/store-engine/src/main/engine/FileEngine.ts
The options in `init()` should be optional because
* [`storeName` is optional](https://github.com/wireapp/wire-web-packages/pull/1191/files#diff-333c4b7db5b6087797f2608a9df38dc5L29)
* [the options are merged with the default options](https://github.com/wireapp/wire-web-packages/pull/1191/files#diff-333c4b7db5b6087797f2608a9df38dc5L35)
> fix(store-engine): Make init() options optional

- packages/react-ui-kit/src/Misc/Loading.tsx
The `props` for the `<Loading />` component have been defined as follows:
```js
interface LoadingComponentProps {
progress?: number;
size: number;
}
```
The declaration of `progress?: number;` is the same as `progress: number | undefined;` which is different from `progress: number | null;`. So we have been always expecting a `number` or `undefined` value for the `progress` property but our code was checking against `null` which is wrong in that case.
> fix(react-ui-kit): Set initial loading progress to undefined

- packages/react-ui-kit/package.json
- yarn.lock
The `styled-components` are a listed under `dependencies`, so its types should also be listed under `dependencies` because it serves as library. We use the same approach already for the `color` dependency.
> fix(react-ui-kit): Add types for styled-components

- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/changelog-bot/src/main/Start.ts
Sometimes our changes only include a `chore` or a `build`. These types (and some others) are excluded so in that scenario our bot posts empty changelogs:
**Screenshot**
I refactored the code so that the bot is silent in such cases.
> fix(changelog-bot): Prevent empty changelogs from being posted

- packages/api-client/src/main/APIClient.ts
- packages/store-engine/src/main/engine/IndexedDBEngine.test.browser.js
- packages/store-engine/src/main/engine/IndexedDBEngine.ts
- packages/store-engine/src/main/engine/error/LowDiskSpaceError.ts
- yarn.lock
So far the API Client `initEngine` method was swalling unknown erros by creating a `new Error` which causes to lose the original errors instance and its source map. Now that's not the case anymore (replaced with `throw`).
Our IndexedDB engine can be initialized with an existing database via `initWithEngine` or a completely new database (created by the engine itself) using `init`. Within the engine we don't know which entry point the application chose so I streamlined them into a `assignDb` function which can be used for modifying any given instance (no matter if new or pre-existing).
The `hasEnoughQuota` was so far only able to detect when there is no quota given. Now it can also detect if too much quota is consumed.
Title says it all.
> fix(api-client,store-engine): Propagate database errors

- packages/core/src/main/conversation/ConversationService.ts
External generic messages are for text messages with large content and not for images.
> fix(core): Don't use external messages for asset sending

- .huskyrc.js
- package.json
From Husky:
> Warning: Setting pre-commit script in package.json > scripts will be deprecated
Please move it to husky.hooks in package.json, a .huskyrc file, or a husky.config.js file
- https://github.com/typicode/husky#upgrading-from-014
> refactor: Configure Husky through config file

- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/changelog-bot/src/main/Interfaces.ts
- packages/changelog-bot/src/main/Start.ts
- packages/changelog-bot/src/main/cli.ts
You can now run the changelog bot with the flag `-x` to customize the excluded commit types, e.g.
```
changelog-bot -e my@email.com -p mysecretpassword -c 1234 -x chore,build
```
To allow all commit types, simply use `-x ""`.
Furthermore, if the bot is unable to generate a changelog, it will display a warning and exit gracefully.
> feat(changelog-bot): Exclude commit types, don't throw on empty changelog

- packages/copy-config/README.md
- packages/copy-config/src/main/CopyConfig.ts
- packages/copy-config/src/main/cli.ts
I figured that, by default, we want to know which files were copied.
> chore(copy-config): Enable logger by default

- packages/cbor/package.json
- yarn.lock
We don't need coveralls anymore for the CBOR package and if we have a need for a coverage reporter service we would probably go for codecov.
> chore(cbor): Remove coveralls

- packages/commons/src/main/LogFactory.test.js
- packages/commons/src/main/LogFactory.ts
When running Node.js code not via a npm script, then `process.env.npm_package_name` is undefined and cannot be used to autodetect a namespace. In that case we have been showing `undefined` which is now replaced by an empty string.
> fix(commons): Don't print undefined namespace in log messages

- packages/commons/src/main/LogFactory.ts
@ffflorian After working with our wrapper I realized that it's better if the consuming application handles errors from our common module. Especially when using a linter that warns you about "floating promises" because then you would need to wrap a call to a promise anyway with a try-catch block.
See: https://github.com/wireapp/wire-desktop/pull/2316/commits/9104c1c364437a6411f47c57801ab3ae4240b0e6#diff-acab454f418662fe6f697507e4c4103aR401
> feat(commons): Expose log writing errors

- packages/copy-config/.gitignore
- packages/copy-config/src/main/CopyConfig.test.js
- packages/copy-config/src/main/CopyConfig.ts
- packages/copy-config/src/main/CopyConfigOptions.ts
Downloading over HTTP(s) was slower than expected.
Let's clone with `git` if it is available and only download over HTTP(s) if it is not.
> fix(copy-config): Download only if git is not available

- tsconfig.json
When removing comments, all JSDoc comments are removed, too.
It would be great to have JSDoc in the declaration files.
> chore: Keep comments when building

- package.json
Currently when you try to run `yarn && yarn boot` with yarn v0.15 it will fail because we need a very recent version of yarn. 
@ffflorian Do you know which version of yarn enforced https links in `yarn.lock` file? Then we could even make this our lower end requirement.
> chore: Enforce modern versions of node and yarn

- package.json
- tsconfig.json
Follow-up to #1667.
I was wondering why we don't enable all available ES libs since they will be transpiled to ES5 (now ES6) anyway.
> chore: Raise TS output to ES6

- packages/eslint-config/eslintrc.json
- yarn.lock
`"error"` is more explicit and understandable than `2`.
See https://eslint.org/docs/user-guide/configuring#configuring-rules.
> chore(eslint-config): Use "error" instead of 2

- .travis.yml
- packages/store-engine/src/main/engine/FileSystemEngine.test.browser.ts
- packages/store-engine/src/main/engine/IndexedDBEngine.test.browser.ts
- packages/store-engine/src/main/engine/LocalStorageEngine.test.browser.ts
- packages/store-engine/src/main/engine/LocalStorageEngine.ts
- packages/store-engine/src/main/engine/MemoryEngine.test.ts
- packages/store-engine/src/main/test/deleteSpec.ts
- packages/store-engine/src/main/test/readAllPrimaryKeysSpec.ts
- packages/store-engine/src/main/test/readAllSpec.ts
I adjusted the test cases because they expected a fixed order of items from `readAllPrimaryKeys` but that order is not guaranteed (and never was).
> test(store-engine): Fix flaky LocalStorageEngine tests

- packages/api-client/package.json
Source maps link to source code files, so they need the source code to be published to generate valid maps:
**Example**
```json
{
"file": "WebSocketClient.js",
"mappings": "...",
"names": [],
"sourceRoot": "",
"sources": [
"../../../src/main/tcp/WebSocketClient.ts"
],
"version": 3
}
```
> feat(api-client): Ship source code for source maps

- packages/commons/src/main/util/TypeUtil.ts
- packages/react-ui-kit/src/Form/Checkbox.tsx
- packages/react-ui-kit/src/Form/CodeInput.tsx
- packages/react-ui-kit/src/Form/ErrorMessage.tsx
- packages/react-ui-kit/src/Form/InputBlock.tsx
- packages/react-ui-kit/src/Form/InputSubmitCombo.tsx
- packages/react-ui-kit/src/Layout/Box.tsx
- packages/react-ui-kit/src/Layout/Column.tsx
- packages/react-ui-kit/src/Layout/Container.tsx
- packages/react-ui-kit/src/Layout/Content.tsx
- packages/react-ui-kit/src/Layout/Footer.tsx
- packages/react-ui-kit/src/Layout/Header.tsx
- packages/react-ui-kit/src/Layout/MatchMedia.tsx
- packages/react-ui-kit/src/Layout/headerMenu/HeaderSubMenu.tsx
- packages/react-ui-kit/src/Layout/headerMenu/MenuSubLink.tsx
- packages/react-ui-kit/src/Menu/MenuModal.tsx
- packages/react-ui-kit/src/Menu/TabBar.tsx
- packages/react-ui-kit/src/Modal/Overlay.tsx
- packages/react-ui-kit/src/Text/Label.tsx
- packages/react-ui-kit/src/Text/Paragraph.tsx
- packages/react-ui-kit/src/Text/TextLink.tsx
- packages/react-ui-kit/src/Text/Title.tsx
- packages/react-ui-kit/src/util.ts
In TypeScript 3.5, the `Omit` type was added to the standard library, see https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/#the-omit-helper-type
Additionally, I converted empty interfaces to types, which makes more sense and shouldn't change any behavior.
> feat(commons): Remove Omit and use types (BREAKING)

- packages/eslint-config/eslintrc.json
- packages/tslint-config/tslint.json
See [TSLint rule](https://palantir.github.io/tslint/rules/no-trailing-whitespace/), [ESLint rule](https://eslint.org/docs/rules/no-trailing-spaces).
Both rules have fixers so they should be automatically applied on commit.
> feat(eslint-config,tslint-config): Disallow trailing whitespace

- packages/eslint-config/eslintrc.json
Since this rule is fixable in most cases it will be fixed during commits in case of trailing space.
> fix(eslint-config): Change warn to error for trailing space

- packages/api-client/package.json
- packages/api-client/src/main/Config.ts
The latest production version of our API Client is not working because it fails to compile. The reason for this is that Dexie got removed from our "store-engine" and thus the API Client cannot get it anymore as a transitive dependency. In our monorepo we did not have that problem because the Dexie dependency gets hoisted. Maybe we should apply the [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/) schema here too, WDYT @Yserz? 
Anyhow, I removed Dexie completely from our API Client because it was just used for a type export and I think it's not justified to bring in a complete database lib just because we need the type once. 
The `store` of our `Config` also uses a generic type of `CRUDEngine` so its `schemaCallback` shouldn't require a specialized type like `Dexie`. It's okay to use …
> fix(api-client): Remove Dexie dependency

- packages/api-client/src/main/shims/node/cookie.ts
- packages/bazinga64/src/Converter.ts
- packages/cbor/src/main/cbor/Decoder.ts
- packages/proteus/src/main/util/ClassUtil.ts
- packages/store-engine-bro-fs/src/index.ts
- packages/store-engine/src/main/engine/LocalStorageEngine.ts
See https://jakearchibald.com/2017/await-vs-return-vs-return-await/.
This logs an `UnhandledPromiseRejection`:
```ts
const foo = async () => {
throw new Error('oh no')
};
(async () => {
try {
return foo();
} catch(error) {
console.log(error)
}
})()
```
While this logs the thrown error:
```ts
const foo = async () => {
throw new Error('oh no')
};
(async () => {
try {
const result = await foo();
return result;
} catch(error) {
console.log(error)
}
})()
```
> fix(api-client,bazinga64,cbor,proteus,store-engine,store-engine-bro-fs): Don't return immediately in a try-catch block

- .npmrc
- .yarnrc
- yarn.lock
We favor `yarn` over `npm` but we want to [stick with the npm registry](https://github.com/wireapp/wire-web-packages/blob/master/lerna.json#L14).
> chore: Use npm registry with yarn

- packages/store-engine-dexie/src/index.ts
Checking if the IndexedDB is usable **after** using Dexie doesn't really make sense and checking before using Dexie created a lot of errors in the WebApp, so let's revert it to [the state it was before](https://github.com/wireapp/wire-web-packages/commit/4a5b91c7ceaaa145c14adcad95cdb321ca7096c2#diff-bb108c1edd78163078083c97f40ec441L77).
> fix(store-engine-dexie): Remove dexie support check

- packages/api-client/src/main/notification/NotificationAPI.ts
The `cancel_fallback` option got removed by the backend.
> fix(api-client): Remove "cancel_fallback" from "/notifications"

- packages/api-client/src/main/user/UserAPI.ts
> fix(api-client): Property key is always a string

- packages/core/README.md
- packages/core/src/main/Account.ts
- packages/store-engine-fs/src/index.ts
Without this PR you have to check after calling `account.login` if `context` is existent. With the changes of this PR the conetxt will always be present after calling `login`.
> refactor(core): Make context always available after login

- packages/cli-client/package.json
- yarn.lock
They are not needed anymore [since v8.2.0](https://github.com/motdotla/dotenv/compare/v8.1.0...v8.2.0).
Follow-up to https://github.com/wireapp/wire-web-packages/pull/2430.
> chore: Remove dotenv types

- packages/bot-api/src/MessageHandler.test.node.js
- packages/core/src/main/Account.test.browser.js
- packages/core/src/main/Account.test.node.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/AssetService.test.node.ts
- packages/core/src/main/conversation/ConversationService.test.node.ts
- `initServices` will be made "private" in my upcoming / next PR
> feat(core): Expose "init" and "register" calls from API client

- packages/api-client/src/APIClient.ts
Fixes @C663605 and @C669373
The issue is that we first call logout which invalidates the cookie. Then the websocket is running for some more time until it gets disconnected as well. During this time the websocket complaints about the missing cookie.
> fix(api-client): Disconnect WebSocket before logout

- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/conversation/data/ConversationNameUpdateData.ts
- packages/api-client/src/conversation/data/index.ts
- packages/api-client/src/conversation/index.ts
Posting to `/conversations/{cnv}` is [deprecated](https://staging-nginz-https.zinfra.io/swagger-ui/tab.html#!//updateConversationName) and the new endpoint `/conversations/{cnv}/name` [should be used](https://staging-nginz-https.zinfra.io/swagger-ui/tab.html#!//updateConversationName_0).
To align this function with the others, I renamed and moved the appropriate interface.
> fix(api-client): Use new endpoint to update a conversation's name

- packages/commons/package.json
ansi-regex now provides its own type definitions, so no more external definitions needed.
> refactor(commons): Drop external ansi-regex definitions

- packages/api-client/src/tcp/ReconnectingWebsocket.ts
This removes long outputs from the logs since it's not possible to hide `debug` outputs from logdown.
> chore(api-client): Remove long debug output

- packages/api-client/src/auth/AuthenticationError.ts
- packages/api-client/src/conversation/ConversationError.ts
- packages/api-client/src/http/BackendError.ts
- packages/api-client/src/http/NetworkError.ts
- packages/api-client/src/team/TeamError.ts
- packages/api-client/src/user/UserError.ts
- packages/api-client/src/validation/ValidationError.ts
- packages/bazinga64/src/UnsupportedInputError.ts
- packages/cbor/src/main/cbor/BaseError.ts
- packages/cbor/src/main/cbor/DecodeError.ts
- packages/cryptobox/src/main/DecryptionError.ts
- packages/cryptobox/src/main/InvalidPreKeyFormatError.ts
- packages/cryptobox/src/main/error/CryptoboxError.ts
- packages/proteus/src/main/errors/DecodeError.ts
- packages/proteus/src/main/errors/DecryptError.ts
- packages/proteus/src/main/errors/InputError.ts
- packages/proteus/src/main/errors/ProteusError.ts
- packages/store-engine/src/main/engine/error/LowDiskSpaceError.ts
- packages/store-engine/src/main/engine/error/PathValidationError.ts
- packages/store-engine/src/main/engine/error/RecordAlreadyExistsError.ts
- packages/store-engine/src/main/engine/error/RecordNotFoundError.ts
- packages/store-engine/src/main/engine/error/RecordTypeError.ts
- packages/store-engine/src/main/engine/error/UnsupportedError.ts
Let's use `new.target.prototype`!
See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#support-for-newtarget
> refactor: Set prototype of errors

- packages/api-client/package.json
- yarn.lock
Since Florian's PR (https://github.com/pladaria/reconnecting-websocket/pull/113) got merged, we can take the official route. 😎
> chore(deps-dev): bump reconnecting-websocket to 4.4.0

- packages/api-client/src/broadcast/BroadcastAPI.ts
- packages/api-client/src/conversation/UserClients.ts
POSTing ` /broadcast/otr/messages` returns the same as posting to `/conversations/{cnv}/otr/messages`.
See:
- https://staging-nginz-https.zinfra.io/swagger-ui/tab.html#!/postProtoOtrMessage
- https://staging-nginz-https.zinfra.io/swagger-ui/tab.html#!/postOtrBroadcast
> fix(api-client): Change response type for broadcast OTR messages

- packages/api-client/src/http/BackendErrorLabel.ts
So backend changed it's mind here: https://github.com/zinfra/backend-issues/issues/1237
Which resulted in the change here: https://github.com/wireapp/wire-server/pull/1029#issuecomment-610996280
> fix(api-client): New error for owner deletion

- packages/api-client/src/APIClient.ts
- packages/api-client/src/auth/AccessTokenStore.ts
- packages/api-client/src/auth/CookieStore.ts
- packages/api-client/src/http/HttpClient.ts
- packages/api-client/src/tcp/WebSocketClient.ts
- packages/core/src/main/Account.ts
- packages/cryptobox/src/main/Cryptobox.ts
When a project uses "@types/node" 12.x and our "@wireapp/core" everything works great but when a project uses "@types/node" 13.x and our "@wireapp/core" then we will see this TypeScript error:
> error TS2507: Type 'typeof EventEmitter' is not a constructor function type.
Starting with Node 13 the `EventEmitter` should **not** be consumed from the default export: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42164#issuecomment-583045095
> fix(api-client,core,cryptobox): Improve type compatibility with Node 13

- packages/eslint-config/eslintrc.json
This will warn users who are committing `fdescribe()` or `fit()`.
> feat(eslint-config): Warn when using fdescribe or fit

- package.json
- packages/api-client/package.json
- packages/bot-api/package.json
- packages/bot-handler-debug/package.json
- packages/cli-client/package.json
- packages/core/package.json
- packages/license-collector/package.json
- packages/lru-cache/package.json
- packages/proteus/package.json
- packages/store-engine-bro-fs/package.json
- packages/store-engine-dexie/package.json
- packages/store-engine-fs/package.json
- packages/store-engine-sqleet/package.json
- packages/store-engine-web-storage/package.json
- yarn.lock
- With this PR "ts-node" becomes a shared dev dependency between all packages, there is no need anymore to declare it for every single package if you want to use it to run a demo script
- With this PR "ts-node" will be equipped with "tsconfig-paths". This allows us to run ts-node on a top level project without rebuilding transitive dependencies first. **Example:** When changing TypeScript code in the "api-client" and running a script with ts-node in our "core" module, the changes from the API client won't be usable until you rebuild the API client (compiling it to JavaScript). With "tsconfig-paths" you don't need to recompile packages from deep down as it will help the top-level ts-node script to resolve the TypeScript monorepo links.
> refactor: Resolve monorepo path aliases with ts-node

- package.json
- packages/bot-api/package.json
- packages/bot-handler-debug/package.json
- packages/bot-handler-uptime/package.json
- packages/changelog-bot/package.json
- packages/cli-client/package.json
- packages/commons/package.json
- packages/core/package.json
- packages/license-collector/package.json
- packages/store-engine-bro-fs/package.json
- packages/store-engine-dexie/package.json
- packages/store-engine-fs/package.json
- packages/store-engine-web-storage/package.json
- packages/travis-bot/package.json
- packages/webapp-events/package.json
- yarn.lock
The "@types/long" dependency should ship with ProtoBuf but it doesn't. That's why we added it in our "core" package. All packages based on the "core" package should receive "@types/long" as transitive dependency. However, when building scoped packages with lerna, this dependency is not hoisted because we added all packages of type "@types" to the "nohoist" list. This will change with my PR, so that "@types/long" will get hoisted when it comes in as a transitive dependency when building scoped packages.
I also streamlined the versions of TypeScript that are being used across our packages.
> chore: Hoist @types/long dependency

- packages/bot-api/src/Bot.ts
- packages/core/src/main/Account.ts
Code for Testing:
```typescript
import 'dotenv-defaults/config';
import path from "path";
import {ClientType} from "@wireapp/api-client/dist/client";
import {Bot, BotConfig, BotCredentials} from "..";
import {FileEngine} from "@wireapp/store-engine-fs";
async function main() {
const {EMAIL, PASSWORD} = process.env;
const config: BotConfig = {
backend: 'production',
clientType: ClientType.PERMANENT,
conversations: [],
owners: [],
};
const wireDirectory = path.join(process.cwd(), 'db');
const storeEngine = new FileEngine(wireDirectory, {fileExtension: '.json'});
await storeEngine.init('my-bot');
const credentials: BotCredentials = {
email: EMAIL!,
password: PASSWORD!,
};
const bot = new Bot(credentials, config);
await bot.start(storeEngine);
}
main().catch(console.error);
```
> fix(bot-api,core): Don't re-init an initialized store engine

- packages/api-client/src/broadcast/BroadcastAPI.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/conversation/NewOTRMessage.ts
- packages/core/src/main/broadcast/BroadcastService.ts
- packages/core/src/main/conversation/ConversationService.ts
BREAKING CHANGES:
- `postOTRMessage()` now takes a `boolean` as fourth parameter to avoid confusion because `report_missing` needs to be set in `messageData` anyway.
- `report_missing` will be deleted from the `messageData` since `ignore_missing` will take precedence anyway.
> feat(api-client): Remove `ignore_missing` URL parameter (BREAKING)

- .gitignore
- packages/webapp-events/package.json
- packages/webapp-events/tsconfig.json
This PR will allow us to solely use TypeScript code in our mono repo structure by doing the following:
- It links to a "main" entry in "package.json" without file extension
- If there are no JavaScript sources, the TypeScript compiler will auto-complete the missing file extension with ".ts"
- Because the TypeScript compiler defaults to ".ts" extension, other TypeScript packages can link to the original sources within the mono-repo, so if A consumes B, B does not need to be compiled anymore because it can be used directly by A (if A is also written in TypeScript)
- During a "yarn release", the JavaScript code gets built, so that a Node.js environment can auto-complete the missing file extension to ".js", so it will be able to pick-up an "index.js" file which is uploaded to npmjs
- If …
> refactor(webapp-events): Use plain TypeScript locally

- packages/commons/src/main/util/Runtime.ts
**From Chrome:**
> [Deprecation] RTCRtpReceiver.createEncodedVideoStreams is deprecated and will be removed in M85, around August 2020. Please use RTCRtpReceiver.createEncodedStreams instead. See https://www.chromestatus.com/features/6321945865879552 for more details.
> fix(commons): Remove check for deprecated 'createEncodedVideoStreams'

- packages/api-client/src/user/User.ts
The `assets` attribute is part of the `RegisterData` type via `Pick`. For guests `assets` are not required.
> fix(api-client): Optional User assets attribute

- packages/proteus/src/main/session/Session.ts
- packages/proteus/src/main/util/KeyDerivationUtil.ts
Since `SessionTag.toString()` uses `sodium.to_hex()` and is therefore quite costly this will save a few CPU cycles.
> fix(proteus): Convert SessionTag to string only once

- packages/proteus/package.json
Proteus' build files are created in `src` but the `clean` script was removing files from the non-existent `dist` dir.
> chore(proteus): Clean js files from src

- packages/core/package.json
The "core" inherits "protocol-messaging" and "store-engine" from "api-client" and "cryptobox" and thus doesn't need these as direct dependencies.
> refactor(core): Remove transitive dependencies

- package.json
We recently updated our npm token and are now using an [Automation token](https://docs.npmjs.com/creating-and-viewing-access-tokens). By default Lerna tries to authenticate the user using `npm whoami`. This is not possible with an automation token so we have to skip the user authentication step (see https://github.com/lerna/lerna/issues/2788).
> fix: Publish releases with npm Automation token

- packages/api-client/src/conversation/Conversation.ts
- packages/api-client/src/conversation/ConversationAPI.ts
Can be tested with:
```typescript
const apiClient = await initClient();
const conversations = await apiClient.conversation.api.getRemoteConversations('staging.zinfra.io');
```
> feat(api-client): Get remote conversations

- packages/api-client/src/conversation/ConversationAPI.ts
To optimize performance when protobuf encodes an entity, it first generates a big ArrayBuffer which it fills with the content of the entity and then generates a DataView (namely `Uint8Array`) on top of it that has `byteOffset` and `byteLength` properties that tell how the buffer should be read.
Axios currently ignores those properties and send the entire 8k buffer through the wire. 
This fix slices the `Uint8Array` in order to create a new array that has exactly the right amount of bytes in it. Axios still uses the complete buffer but this time it only has the right bytes, no more, no less.
> fix(api-client): Force protobuf arrays to be recreated before sent

- packages/prettier-config/index.json
`jsxBracketSameLine` was [deprecated](https://prettier.io/docs/en/options.html#deprecated-jsx-brackets).
> fix(prettier-config): Use bracketSameLine

- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
This adds a new callbacks parameter to the `send` method of the conversationService that allows the consumer to get notified when the message is about to be sent and when it is successfully sent. 
It's a first draft that only works for text message, as of now, but can be easily generalized to all the other message types
This can be used to update a UI state when the message starts being sent and update the UI again when the message is actually sent.
> feat(core): Add callbacks for message sending state

- packages/core/src/main/broadcast/BroadcastService.ts
- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/MessageService.ts
- packages/core/src/main/user/UserService.ts
In order to know, for a consumer point of view, when a message was sent (with the backend timestamp), we need to surface the response from the server to the upper layers of the core in order to send the timestamp to the `messageSendingCallback.onSuccess` callback
See https://github.com/wireapp/wire-webapp/pull/11887 for an example of usage
> feat(core): Surface the message sent time to consumer

- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/conversation/data/ConversationMemberLeaveData.ts
- packages/api-client/src/conversation/data/ConversationMemberUpdateData.ts
- packages/api-client/src/event/ConversationEvent.ts
This aligns the types of the conversation events with the types defined by the backend. 
It also adds a way to discriminate events when consumed on the webapp. 
Needed for https://github.com/wireapp/wire-webapp/pull/11886
> feat(api-client): Improve event types

- packages/api-client/src/event/UserEvent.ts
- packages/api-client/src/user/data/UserDeleteData.ts
- packages/api-client/src/user/data/UserLegalHoldRequestData.ts
- packages/api-client/src/user/data/UserPropertiesDeleteData.ts
The typing for `UserDelete` and `UserLegalHoldRequest` data were off. 
It was also missing the `UserPropertiesDelete` event.
> fix(api-client): Align user event definitions

- packages/core/src/main/Account.ts
- packages/core/src/main/cryptography/CryptographyService.ts
This enable the consumer of the core to set a federation domain to use when computing session ids. 
When set, this domain will be used to create session ids (if not given in the message payload) and decrypt with this session.
> feat(core): Add option to set a domain on an account

- packages/core/src/main/broadcast/BroadcastService.ts
- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/MessageService.test.node.ts
- packages/core/src/main/conversation/message/MessageService.ts
- packages/core/src/main/conversation/message/UserClientsUtil.ts
- packages/core/src/main/conversation/message/UserClientsUtils.test.node.ts
- packages/core/src/main/util/TypePredicateUtil.ts
BREAKING CHANGE
- When calling `account.services.converation.send` with a list of `UserClients`, the core will not try to fetch the latest clients from the backend and will instead only send to the given clients. This might generate a mismatch error is there are missing clients given. 
This PR will:
- Simplify the `MessageService` API to only 2 public methods (`sendMessage`, `sendFederatedMessage`);
- Move all the encryption jobs to the `MessageService`, the `ConversationService` is not even aware encryption exists;
- Harmonize how mismatch are handled and retried in the `MessageService`;
- Cover the main sending scenarios (as external, with mismatch, as protobuf...) with tests;
> refactor(core): Simplify and streamline responsibilities of the MessageService

- packages/core/src/main/cryptography/CryptographyService.test.node.ts
- packages/core/src/main/cryptography/CryptographyService.ts
Instead of failing completely, when a session with a user is not found, we remove the client for the payload and let the mismatch handler take care of creating the session later on
> fix(core): Gracefully handle missing sessions when encrypting

- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
This adds the possibility for the consumer to cancel a message from being sent. 
This allows the consumer to access the full `genericMessage` (can be used for optimistic event) but still cancel the sending.
> feat(core): Add a mechanism to cancel message sending

- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/MessageService.test.node.ts
- packages/core/src/main/conversation/message/MessageService.ts
This will allow messages to be send to a particular set of users in the conversation. 
There are three target mode possible:
- NONE (default) will target no user in particular (so will try to send to all the users in the conversation). This will trigger a mismatch error if some user/client pair are missing on backend side ;
- `USERS` Will target some specific users. Only clients missing from those users will trigger a mismatch error. Missing users will not
- `USERS_CLIENTS` will target specific users/clients. Basically the same as forcing the message to be sent and ignores all missing users/clients.
- confirmation message => only sent to the user from the original message but all his devices (`USERS`) (see https://github.com/wireapp/wire-webapp/pull/12207)
- calling message while in call …
> feat(core): Add ability to send targeted message to specific users

- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/PayloadBundle.ts
When sending a message and the consumer decided to cancel message sending because of a mismatch error, then the returned payload has the `state: PayloadBundleState.CANCELLED` property set
> feat(core): Add cancelled flag when message sending was cancelled

- packages/core/src/main/conversation/ConversationMapper.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/message/PayloadBundle.ts
`PayloadBundle` now gets decorated with `qualifiedConversation` and `qualifiedFrom` and can be read on consumer side
> feat(core): Map qualified_conversation and qualified_from in message payloads

- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
This enables the consumer to get a fresh list of participants and clients for a given conversation.
> feat(core): Add a method to get all participants/clients of a conversation

- packages/bot-api/src/MessageHandler.test.node.ts
- packages/bot-api/src/MessageHandler.ts
- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/cli-client/src/index.ts
- packages/core/src/demo/composite.ts
- packages/core/src/demo/echo.ts
- packages/core/src/demo/sender.ts
- packages/core/src/demo/status-bot.ts
- packages/core/src/main/Account.test.node.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/AssetService.test.node.ts
- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/content/LinkPreviewContent.ts
- packages/core/src/main/conversation/message/MessageBuilder.ts
- packages/core/src/main/index.ts
- packages/core/src/main/linkPreview/LinkPreviewService.ts
- packages/core/src/main/linkPreview/index.ts
BREAKING CHANGE:
- `MessageBuilder` has been moved from `account.services.conversation.messageBuilder` to an own stateless class.
- All method of the `MessageBuilder` now take a required `from` parameter
- `MessageBuilder` is not uploading files under the hood. Upload must be done in a separate function call
Replace
```
const textPayload = account.service.conversation.messageBuilder.createText(...);
```
With
```
import {MessageBuilder} from '@wireapp/core/src/main/conversation/message/MessageBuilder';
//...
const textPayload = MessageBuilder.createText(...);
```
Replace
```
const linkPreview = await account.service.conversation.messageBuilder.createLinkPreview(...);
cons textPayload = account.service.conversation.messageBuilder.createText(...).withLinkPreview([linkPreview]);
```
With
``` …
```
> feat(core): Make message builder stateless

- packages/bot-api/src/MessageHandler.ts
- packages/core/src/demo/echo.ts
- packages/core/src/demo/sender.ts
- packages/core/src/main/conversation/message/MessageBuilder.ts
BREAKING CHANGE:
Replace `MessageBuilder.createImage({..., imageAsset: asset})` with `MessageBuilder.createImage({..., asset})`
> refactor(core): Harmonize asset param name

- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/conversation/GenericMessageType.ts
This PR adds:
- caching of the self conversation getter (since the self conversation never changes, there is no need to fetch multiple times)
- ability to sync the last read timestamp across devices
- ability to sync the countly id across devices
> feat(core): Add lastRead and Countly message to the core

- packages/core/src/main/broadcast/BroadcastService.ts
- packages/core/src/main/user/UserService.ts
BREAKING CHANGE: the setAvailability of the user service will by default now only send to directly connected users. To send to absolutely all the users in the team call `setAvailability` with the `{sendAll: true}` option
> feat(core): Send availability status only to directly connected members

- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/cryptography/AssetCryptography/EncryptedAsset.ts
- packages/core/src/main/cryptography/AssetCryptography/crypto.browser.ts
- packages/core/src/main/cryptography/AssetCryptography/crypto.node.ts
- packages/core/src/main/cryptography/AssetCryptography/index.ts
- packages/core/src/main/cryptography/AssetCryptography/interfaces.ts
- packages/core/src/main/cryptography/CryptographyService.test.browser.js
- packages/core/src/main/cryptography/CryptographyService.test.node.ts
Since node `Buffer` is a subclass of `Uint8Array` and that we don't need the specific features of `Buffer` we can just use plain `Uint8Array` everywhere. (see https://nodejs.org/api/buffer.html#buffer)
> fix(core): Use Uint8Array in place of Buffer

- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/cryptography/CryptographyService.ts
BREAKING CHANGE: If you were using the `Account` with a federationDomain, you need to replace `federationDomain: 'the.domain'` to `useQualifiedIds: true`. The domain will be found automatically by the core
> feat(core): Remove the need to give a domain to use qualified Ids

- packages/api-client/src/user/UserPreKeyBundleMap.ts
- packages/core/src/main/cryptography/CryptographyService.test.node.ts
- packages/core/src/main/cryptography/CryptographyService.ts
Backend response for prekey bundle can eventually be `null`. We need to handle that case in the core to prevent crashes
> fix(core): Do not try to encrypt for clients without prekeys

- packages/api-client/src/APIClient.test.node.ts
- packages/api-client/src/APIClient.ts
- packages/api-client/src/connection/ConnectionAPI.ts
- packages/api-client/src/conversation/ConversationAPI.test.ts
- packages/api-client/src/conversation/ConversationAPI.ts
- packages/api-client/src/user/UserAPI.ts
- packages/bot-api/src/MessageHandler.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/client/ClientDatabaseRepository.ts
- packages/core/src/main/client/ClientService.ts
- packages/core/src/main/connection/ConnectionService.ts
- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService.ts
- packages/core/src/main/cryptography/CryptographyService.test.browser.js
- packages/core/src/main/cryptography/CryptographyService.test.node.ts
- packages/core/src/main/cryptography/CryptographyService.ts
Allow the API to be fixed to a specific backend version
By default, the APIClient will use version 0. If you want to use a different version, you should use the `useVersion` method of the APIClient
```js
const version = await apiClient.useVersion([1,2]);
// Will resolve with the version that will be used
// Will reject if no version in common is found with the backend
```
All the methods that were using `useFederation` do not need this parameter anymore (since the federation state is guessed from the api version number)
> feat(api-client): Allow setting a backend version

- packages/react-ui-kit/src/Form/ErrorMessage.tsx
- packages/react-ui-kit/src/Form/__snapshots__/ErrorMessage.test.tsx.snap
Description:
In the application's, the decorative SVG graphics buttons, are not hidden with aria-hidden="true" for assistive technologies and are output when reading linearly with a screen reader.
> fix(react-ui-kit/accessibility): add aria-hidden to error message icon #ACC-23

- packages/bot-api/src/Bot.ts
- packages/bot-api/src/MessageHandler.test.node.ts
- packages/changelog-bot/src/main/ChangelogBot.ts
- packages/cli-client/src/index.ts
- packages/core/src/demo/sendCounter.ts
- packages/core/src/demo/sender.ts
- packages/core/src/demo/status-bot.ts
- packages/core/src/main/Account.test.node.ts
- packages/core/src/main/Account.ts
This PR harmonizes how an already initialized database can be given to the core.
Initially, there was 3 different methods where a db could be given. They would all have slightly different behavior and would mean exactly the same thing:
- either in the constructor of the Core, give a `storeEngineProvider` that will be called when a database needs to be accessed by the core
- or in the `login` or `init` methods give a direct instance of a database
- or overwrite the `storageEngine` of the instance directly (hack). 
Now there is only a single way to give an already existing database: add the `createStore` option in the constructor. 
This function will be called with the `storeName` and `context` so that the consumer can decide what kind of database should be given depending on the type of …
> refactor: Cleanup storage initialization

- packages/core/src/main/conversation/ConversationService.ts
This will prepare for MLS. 
Since we want MLS only to be mentioned in the core (and not in the webapp), we need to use a little more of the core in the webapp (so we can easily hook MLS functionalities into the core). 
This PR ensures that we can create conversations that are compatible with the conversations we create in the webapp
Associated webapp PR https://github.com/wireapp/wire-webapp/pull/12974
> feat: Allow complete payload to create conversations

- packages/core/src/main/conversation/ConversationService.ts
When sending `lastRead` or `Countly` message, the consumer cannot give an explicit list of users to send to. 
This is a performance issue as the core will then try to download all the members of the conversation and send that message to all of them (useless back and forth with backend). 
Also since the backend returns all the members including the current device, we will try to create a session with the device the user is currently using which makes very little sense. 
BREAKING CHANGE: To send `lastRead` and `countly` as protobuf message, you now need to provide a `MessageSendingOptions` object as last parameter. 
```js
core.service.conversation.sendLastRead(conversation, timestamp, true);
// Becomes
core.service.converstaion.sendLastRead(conversation, timestamp, {sendAsProtobuf: true}); …
```
> fix: Allow sending targeted lastRead and Countly messages

- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService.test.node.ts
- packages/core/src/main/conversation/message/MessageService.test.node.ts
- packages/core/src/main/cryptography/CryptographyService.test.browser.js
- packages/core/src/main/cryptography/CryptographyService.test.node.ts
- packages/core/src/main/cryptography/CryptographyService.ts
Will allow the consumer to set a number of prekeys to generate. 
As of now it defaults to 1, which means that we only ever use the last resort prekey. 
This will allow generating more prekeys and let cryptobox generate new as they are consumed
> feat: Allow consumer to set number of prekeys generated

- packages/core/src/main/Account.test.browser.js
- packages/core/src/main/Account.ts
- packages/core/src/main/client/ClientService.ts
BREAKING CHANGE: if you were relying on `account.init()` to also create a new client, this behavior now change and will throw an error instead. If you also want to create a device (if it doesn't exist already), you should use the `account.login()` or `account.initClient()` methods instead
> fix: Avoid silently creating client when initializing core

- packages/api-client/src/notification/NotificationAPI.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/notification/NotificationBackendRepository.ts
- packages/core/src/main/notification/NotificationService.ts
When fetching the notification stream, if the current client has connected for more than 28 days, we will have notifications that have been missed and removed from the backend. 
This hook allows the consumer to be warned when such missed notifications are detected
> feat: Add missed notifications hook

- packages/core/src/main/Account.ts
- packages/core/src/main/notification/NotificationService.test.node.ts
- packages/core/src/main/notification/NotificationService.ts
This will allow consumer to just get events without storing the last notification id and not decrypting events
> feat: Add listen dryrun option

- packages/api-client/src/APIClient.test.browser.ts
- packages/api-client/src/auth/AccessTokenStore.ts
- packages/api-client/src/http/HttpClient.test.node.ts
- packages/api-client/src/http/HttpClient.ts
- packages/api-client/src/tcp/WebSocketClient.test.node.ts
- packages/api-client/src/tcp/WebSocketClient.ts
- packages/core/src/main/Account.ts
We had a nasty race condition when reconnecting to the websocket after the access token was expired. In this race condition both the notification stream request and the websocket would both trigger an access token refresh ending up in both coliding with each other
> fix(core): Make sure access token is valid before connecting to websocket

- packages/react-ui-kit/src/Layout/StyledApp.tsx
- packages/react-ui-kit/src/Layout/Theme.tsx
Modify StyledApp and ThemeProvider so you can pass either a themeId for the prebuilt light/dark theme or a complete theme object as StyledApp prop.
> feat: modify StyledApp to accept either theme object or themeId as prop

- packages/core/src/main/Account.ts
BREAKING CHANGE: the `enableMLS` flag has been removed in favor of a config object. If the config object is set, then MLS will be activated
> feat: Use mls config object

- packages/react-ui-kit/src/Form/Select.tsx
`Select` component initial current value fix.
With this PR the "current value" state of the Select component depends only on the `value` prop.
> fix(react-ui-kit): fix select component current value empty (#SQSERVICES-1661)

- packages/api-client/src/http/BackendErrorLabel.ts
Added error label which is returned on invalid secure hold url (TM).
> feat(api-client): add LEGAL_HOLD_SERVICE_UNAVAILABLE backend error label (#SQSERVICES-1493)

- packages/react-ui-kit/src/Form/Checkbox.tsx
auth screens checkbox are centre aligned, while other checkbox after login are left aligned. To resolve the issue we are using a flag alignCenter whose default value is false and set to true for auth screen checkbox only. Using the flag we set width to be 100 percent or auto.
> fix: centre align auth screen checkbox(ACC-207)

- packages/react-ui-kit/src/Form/DropFileInput.md
- packages/react-ui-kit/src/Form/DropFileInput.test.tsx
- packages/react-ui-kit/src/Form/DropFileInput.tsx
- packages/react-ui-kit/src/Form/__snapshots__/DropFileInput.test.tsx.snap
- packages/react-ui-kit/src/Icon/SVGIcon.md
- packages/react-ui-kit/src/Icon/UploadIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
Added file input with drop zone area:
- user is able to upload files by dropping files in the zone or by clicking on input's label text (eg. select file from your device)
- customisable:
- dropdown text (heading and clickable label) 
- description under input
- zone's styles (css object)
- `onFilesUploaded` callback passed as props run after file is successfully uploaded using dropdown or native file select; takes an array of files as a first (and only) param.
- `onInvalidFilesDropError` - native file picker won't allow user to pick file with unexpected type, but we have to validate types of files uploaded using drop area. This callback will run after invalid file was dropped on drop area.
- `accept` (native file input's attribute) - accepted file mime-types list joined with comma (`,`)
- …
> feat(react-ui-kit): add DropFileInput component (#SQSERVICES-758)

- packages/api-client/src/team/team/NewTeamData.ts
- packages/api-client/src/team/team/TeamData.ts
- packages/api-client/src/team/team/UpdateTeamData.ts
Added `splash_screen` field to `TeamData` model due to backend update
> feat(api-client): add 'splash_screen' field to TeamData model (#SQSERVICES-758)

- packages/react-ui-kit/src/Form/RangeInput.md
- packages/react-ui-kit/src/Form/RangeInput.styles.ts
- packages/react-ui-kit/src/Form/RangeInput.test.tsx
- packages/react-ui-kit/src/Form/RangeInput.tsx
- packages/react-ui-kit/src/Form/__snapshots__/RangeInput.test.tsx.snap
- packages/react-ui-kit/src/Form/index.ts
- packages/react-ui-kit/src/util.ts
Add custom `RangeInput` (`range` type input) component to `react-ui-kit` package. (we need it in TM splash screen customisation component). Custom input styling was applied, so input should look the same across different browsers.
Customisable:
- wrapper styles (`wrapperCSS` prop)
- input styles (`css` emotions prop)
- min and max value labels (`minValueLabel` and `maxValueLabel` strings)
- label (`label` string prop)
- all input's native props (`onChange`, `value`, `min`, `max`, `step`, etc.)
> feat(react-ui-kit): add custom RangeInput component (#SQSERVICES-758)

- packages/react-ui-kit/src/Layout/MatchMedia.tsx
`useMatchMedia` was returning incorrect matching state. The reason was matchMedia object (`MediaQueryList`) was recreated on each render and there were multiple instances listening for the same event. I've also replaced `.addListener` (deprecated) with `.addEventListener`.
> fix(react-ui-kit): fix missmatching media queries

- packages/react-ui-kit/src/Form/Checkbox.tsx
- packages/react-ui-kit/src/Form/Input.tsx
- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/SelectStyles.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/ErrorMessage.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Input.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
- packages/react-ui-kit/src/Text/Link.tsx
- packages/react-ui-kit/src/Text/Text.tsx
- packages/react-ui-kit/src/Text/__snapshots__/Label.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/Link.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/Text.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/TextLink.test.tsx.snap
- packages/react-ui-kit/src/Text/__snapshots__/Title.test.tsx.snap
- Add a Link variant to use the UI-kit Link in the web-app
- Keep the previous option as the default not to require any change to team-management
- Remove hardcoded style for color and links from Checkbox component
- Fix styles that were not being applied because of React-Select prebaked theme
- Restore the disabled prop to Select and apply the corresponding styles
- Apply a border radius to Input corresponding to webapp design
> feat: add a link variant for use in the webapp

- packages/react-ui-kit/src/GlobalCssVariables.tsx
- packages/react-ui-kit/src/GlobalStyle.tsx
- packages/react-ui-kit/src/Layout/Theme.tsx
- Move the theme object from the webapp to the ui-kit
- Expose css variables in GlobalStyles so they can be accessible from team setting and removed from the webapp .less files
- It ables us to change components in the ui-kit wthout having to fiddle with .less files on the webapp
- It will allow team-setting to use the same theme as webapp
> feat: move the theme in ui-kit and expose css variables

- packages/react-ui-kit/src/Form/Select.tsx
- disabled prop restored [here](https://github.com/wireapp/wire-web-packages/pull/4354) should be optional
> runfix: make disabled prop optional on select component

- packages/react-ui-kit/src/Text/Link.tsx
- corect `focus:active` to `focus-visible`
> runfix: correct typo for Link focus state

- packages/core/src/main/Account.ts
- packages/core/src/main/util/encryptedStore.ts
When logging out, if the user wants to clear the data, we also need to clear any database that was created on the account of the core. 
This PR adds the `clearData` param to the `logout` method in order to do this
> feat: Clear created databases when logging out

- packages/core/src/main/Account.ts
Will allow a user to also create an mls device when logging in with a device that was previously proteus-only
> feat: Also create MLS device when logging in with old proteus device

- packages/api-client/src/conversation/Member.ts
- packages/core/src/main/conversation/ConversationService/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService/ConversationService.ts
This PR will change getAllParticipantsClients, basically previously we used to send an empty message to backend to get a list of missing clients as a hacky way to get a list of user clients in a conversation (**BROKEN FOR MLS CONVERSATIONS**), in this PR the logic is slightly changed without a breaking change, what is done is instead of calling an endpoint with empty message we first fetch the conversation from the backend and extract a fresh list of users in it then make a request to another endpoint we have which if we give it a list of user ids it'll return a list of clients.
> feat: Update getAllParticipantsClients to use better endpoints without a hack

- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService/ConversationService.ts
- packages/core/src/main/cryptography/CryptographyDatabaseRepository.ts
- packages/core/src/main/mls/MLSService/MLSService.ts
- packages/core/src/main/mls/index.ts
- packages/core/src/main/mls/types.ts
- packages/core/src/main/notification/NotificationDatabaseRepository.ts
- packages/core/src/main/notification/NotificationService.test.browser.js
- packages/core/src/main/notification/NotificationService.test.node.ts
- packages/core/src/main/notification/NotificationService.ts
- packages/core/src/main/notification/types.ts
- packages/core/src/main/util/LowPrecisionTaskScheduler/LowPrecisionTaskScheduler.test.node.ts
- packages/core/src/main/util/LowPrecisionTaskScheduler/LowPrecisionTaskScheduler.ts
- packages/core/src/main/util/TaskScheduler/TaskScheduler.ts
[link to confluence use case](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/611910060/Use+case+periodic+update+of+key+material+MLS)
Each user periodically updates their key material for each MLS group they're in.
Goals:
(1)
Store the date (timestamp) of group creation / welcome message as last-kay-material:
Dates are stored in indexedDB's `last_key_material_update_dates` table as objects ({groupId:string, previousUpdateDate: number})
(2)
(3)
(4)
(5)
This pull request also adds new `MLSService` class which contains mls-related methods shared between conversation and notification services. This is the only service that has access to coreCryptoClient (which is lazy-initialised and possible `undefined` - proteus case). All other services should call coreCrypto methods …
> feat(core): update keys periodically (FS-562)

- packages/core/src/main/cryptography/CryptographyDatabaseRepository.ts
Client was not able to delete all stores on login from a fresh (deleted) device.
`Object.keys` (eg. `"AMPLIFY"`) was used instead of `Object.values` (eg. `"amplify"`) for table names, so the client was not able to find the tables and showed `unexpected error` message on client's side.
> runfix(core): address dexie error on deleting all stores on login 

- packages/store-engine-web-storage/package.json
`@wireapp/store-engine-web-storage` package had wrong (non-existing) entry file defined in `package.json` `main` field, what resulted in `cannot find module and its type declarations` ts error.
> runfix(store-engine-web-storage): fix package entry point

- packages/store-engine-web-storage/package.json
- packages/store-engine-web-storage/src/index.ts
Change `@wireapp/store-engine-web-storage` package's entry point to root (`index.ts`)
> runfix(store-engine-web-storage): set web storage package main file to root

- packages/promise-queue/package.json
- yarn.lock
Downgrade `typescript` version to `4.4.2` as it caused compilation errors in `@wireapp/core` package.
> runfix(promise-queue): downgrade ts version to 4.4.2

- packages/core/src/main/Account.ts
Call mls-related methods only for environments with MLS enabled.
> runfix: call mls methods for mls envs only

- packages/core/package.json
- packages/core/src/main/Account.ts
- packages/core/src/main/conversation/ConversationService/ConversationService.test.node.ts
- packages/core/src/main/conversation/ConversationService/ConversationService.ts
- packages/core/src/main/conversation/message/messageSender.ts
- packages/core/src/main/mls/MLSService/MLSService.ts
This will allow not sending messages before we have handled the complete notification stream and be sure that we are up to date with the current `epoch` of each and every conversation
> feat: Queue message sending [FS-882]

- packages/core/src/main/conversation/ConversationService/ConversationService.ts
- packages/core/src/main/mls/MLSService/MLSService.ts
[Use case: leaving a conversation (MLS)](https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/617382226/Use+case+leaving+a+conversation+MLS)
Removes `leaveMLSConversation` wrapper method (we use `leaveMLSConversation` - it works for both mls and proteus protocols).
Adds `wipeMLSConversation` core-crypto method to conversation service (which will be used in `wire-webapp` to wipe conversation after client receives `conversation.member-leave` event.
> feat: leave mls conversation (FS-683)

- package.json
- yarn.lock
With the introduction of yarn 2 and its advanced workspace capabilities (like pnpm) we will have an easier time referring to other packages via the workspace protocol (https://yarnpkg.com/features/workspaces#workspace-ranges-workspace).
The following problem occurs now:
Since we use lerna to publish, we rely on lerna to support the new yarn command, that is used to replace the "workspace" version with the latest version numbers. This ticket (https://github.com/lerna/lerna/issues/2564) mentions active work on the feature, but it is two years old, and the feature is not implemented yet.
Since lerna is not very actively maintained and doesn't support newer protocols like "workspaces" from yarn 2 and pnpm, a switch to the actively maintained lerna-lite needs to happen. Lerna-lite takes a new …
> refactor: replace lerna with maintained fork lerna-lite

- packages/core/src/main/conversation/ConversationService/ConversationService.ts
- packages/core/src/main/conversation/ConversationService/messageGenerator.ts
- packages/core/src/main/conversation/message/MessageBuilder.ts
This will allow the consumer to send `hide` message even in MLS conversations 
BREAKING CHANGES: the `deleteMessageLocal` method has been removed. You should now use the `send` method in combinaison with `MessageBuilder.buildHideMessage` 
`MessageBuilder.createDelete` has been renamed `MessageBuilder.createMessageDelete`
> feat: Enable sending hide message to mls conversations

- bin/testUpdated.js
- packages/certificate-check/package.json
Right now build is actually ran 3 times:
- one in the testUpdated.js script (we build all the changed packages)
- one for each package test (some test script build their own version before actually testing)
- when releasing. 
We can remove the build from the testUpdated.js since the packages are now responsible for building (if they need to) when `yarn test` is called
> chore: avoid running build twice for each package

- packages/react-ui-kit/src/Form/RangeInput.tsx
This will remove the `Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?` for the RangeInput component.
> fix(ui-kit): Proper use of forwardRef for RangeInput

- packages/api-client/src/APIClient.test.node.ts
- packages/api-client/src/APIClient.ts
BREAKING CHANGE: The APIClient would, initially, always consider the development version when calling `useVersion`. Now, to actually use bleeding edge version of the backend API a new flag needs to be provided
> fix(api-client): Add flag to use dev version of the api

- packages/api-client/package.json
- yarn.lock
This should improve the workflow when updating the `ui-kit` (we won't have to build both the `core` and `api-client` whenever the ui-kit is updated)
Since #4420 the ui-kit is not used anymore on the `api-client` side
> chore(api-client): Remove ui-kit from api-client deps

- packages/core/src/main/conversation/ConversationService/ConversationService.ts
- packages/core/src/main/conversation/message/MessageBuilder.ts
BREAKING CHANGE: The `sendLastRead`, `SendCountly` and `clearConversation` methods have been removed in favor of using the regular message sending method `send`. You now need to use the `MessageBuilder` and the `send` method to send those types of messages. `conversationService.send({payload: MessageBuilder.buildClearedMessage(conversationId) ...})`
> refactor: extract lastRead, cleared and DataTransfer message from ConversationService

- packages/core/src/main/Account.ts
- packages/core/src/main/cryptography/CryptographyService.ts
- packages/core/src/main/cryptography/GenericMessageMapper.ts
- packages/core/src/main/notification/NotificationService.ts
- packages/core/src/main/util/TaskScheduler/TaskScheduler.ts
We have identified a potential missing message gap in the handling of the notification stream. 
Here is the full explanation for this:
We we connect to the websocket, the very first thing we do is locking the websocket (so that no message coming in will be parsed before the notification stream). 
Once locked we start processing the notifications given by the `/notifications` endpoint one by one. 
**Here is the catch** if, somehow, the websocket loses the connection **while** we are processing the notification stream, we are going to cancel the notification handling process **BUT** we are not going to avoid `unlocking` the websocket. 
As a result, if ever, there were some messages buffered in the websocket, they are going to be released at this point but we will still have missed the …
> fix: Avoid unlocking websocket when connection is aborted

- packages/core/src/main/mls/MLSService/MLSService.ts
- packages/core/src/main/notification/NotificationService.ts
This will prevent coreCrypto specific messages to be sent back to the consumer. 
They need to stay completely opaque to coreCrypto and don't have any application value. 
This PR also improves the logs and display the new epoch when receiving a commit
> feat: Gracefully handle mls protocol messages

- packages/core/src/main/Account.ts
- packages/core/src/main/mls/types.ts
Rename `secretsCrypto` to `systemCrypto`, see https://github.com/wireapp/wire-desktop/pull/6094
> runfix: rename system crypto config

- packages/core/src/main/Account.ts
Since [#4402](https://github.com/wireapp/wire-web-packages/pull/4402/files#diff-c4b99150dbc7672f5929baaccfef2bafe8fc6a95d69ccd7e9682db7e0b4d4e8dR41) CoreCrypto is not only imported with `type`. So there is no need of re-loading it later on.
> fix: Do not import CoreCrypto twice

- packages/api-client/src/client/ClientClassification.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/cryptography/CryptographyService.test.node.ts
- packages/core/src/main/cryptography/CryptographyService.ts
Migrate back session handling code from the webapp to the core. 
This enables the core to hook into the cryptobox sessions handling and react to it. 
Namely, we have 2 hooks:
- `onNewSession` which is called when cryptobox receives a message from a client it doesn't have a session with
- `onNewPrekeys` which is called when cryptbox is warned that a prekey has been consumed and generates new ones
BREAKING CHANGE: the `Account.init` function signature has changed. If you used `cookie` or `initClient` they are now moved to the option param. `account.init(clientType, cookie, false)` becomes `account.init(clientType, {cookie, initClient: false})`
> feat: Session creation callbacks

- packages/api-client/src/APIClient.ts
- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.test.ts
- packages/core/src/main/Account.ts
- packages/core/src/main/mls/MLSService/MLSService.ts
Add `supportsMLS` flag to backend features interface on `api-client` and enable it when **`backendVersion >= 2`**.
Consume the flag on the `core` side and based on that, decide whether to initialise MLS client or not.
> feat(api-client, core): add supportsMLS flag to api backend features [FS-1051]

- packages/api-client/package.json
- yarn.lock
Istanbul is deprecated and no longer in use since #4420
> chore: remove unused dependency istanbul

- yarn.lock
Leftover duplicate dependency to `async` missed in #4540
> chore: dedupe async

- packages/core/src/main/cryptography/CryptographyService.ts
This adds 2 new methods to the `CryptographyService`:
- `getLocalFingerprint` that will give back the fingerprint of the client the user is currently using
- `getRemoteFingerprint` that will give the fingerprint of another device
> feat: Add fingerprint generation for local and remove clients

- packages/api-client/package.json
- packages/api-client/src/http/HttpClient.ts
- packages/cli-client/package.json
- packages/copy-config/package.json
- packages/core/package.json
- yarn.lock
Axios 1.1.3 has a problem with webpack build (see https://github.com/axios/axios/issues/5154)
> fix: Revert axios to version 1.1.2

- packages/commons/src/main/util/UrlUtil.test.ts
- packages/commons/src/main/util/UrlUtil.ts
No breaking changes introduced.
Added two new APIs to allow future migration from `getURLParameter` to `getURLParameterFromHash`.
> feat: provide utils to extract parameters from URL's hash (SQSERVICES-1610)

- packages/core/src/main/mls/MLSService/MLSService.ts
- packages/core/src/main/util/TaskScheduler/TaskScheduler.ts
It can happen that core-crypto is giving us uppercase user ID when requesting is a user is part of a group or not. 
We need to be more resilient about it and always lower case the ids given by core-crypto
> fix: More resilient id comparison for external proposals

- packages/core/src/main/Account.ts
This ensures that the `clientId` has been set before actually initiating cryptobox. 
This fixes an issue where prekeys could be generated but a clientId was not defined yet (so keys could not be uploaded to be backend)
> fix: Make sure clientId is set before init cryptobox

- packages/react-ui-kit/src/Form/Button.tsx
- packages/react-ui-kit/src/GlobalCssVariables.tsx
- packages/react-ui-kit/src/Layout/Theme.tsx
- Secondary buttons from ui-kit do not use accent colors in webapp
- make use of the new theme for secondary buttons
> refactor: use new theme with secondary button

- packages/core/package.json
- packages/core/src/Account.ts
- packages/core/src/mls/MLSService/MLSService.ts
- packages/core/src/mls/types.ts
- packages/core/src/notification/NotificationService.ts
- yarn.lock
BREAKING CHANGE: the coreCrypto callbacks now need a `userAuthorize` callback to be set. The `mlsConfig` has changed quite a bit
> fix: Prepare for core-crypto proteus support

- packages/core/src/Account.ts
This will allow the consumer to set the api version that they want to use directly from the `core` and avoid mismatch between the configuration of the core and the API Client.
> feat: Configure apiVersion from the core

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Since entropy data can be fed to `coreCrypto` right before proteus/mls devices are initialised, we can actually build our coreCrypto instance very early and have the instance accessible
> refactor: Streamline creation of coreCrypto instance

- packages/core/__mocks__/@wireapp/core-crypto.ts
- packages/core/jest.setup.ts
- packages/core/package.json
- packages/core/src/Account.test.ts
- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/WithMockedGenerics.test.ts
- packages/core/src/util/encryptedStore.test.node.ts
- yarn.lock
Since `@wireapp/core-crypto` is a esmodule only, we cannot, as of now, import it in our unit test, we need to manually mock it
> test: Fix Account tests

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
When no users are added to an MLS conversation, a simple update to the keying material can be done.
> fix: Handle case of empty list of users added to a conversation

- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/Utility/SessionHandler/SessionHandler.ts
Adds the handling of `session reset` messages (they should decrease the number of prekeys that are tracked since the sending side has generated a new session from a fresh prekey)
> feat: Consume prekey when a session is reset

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.types.ts
When a new session is detected (by receiving an event from a client we do not have a session with) we need to warn the consumer that a new client has been detected. 
That can be used later on to trigger conversation degradation
> feat: trigger event when a new client is detected

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/data/ConversationAccessUpdateData.ts
Remove deprecated endpoints/fields due to api v3 updates (backwards compatibility):
> feat(api-client): api v3 deprecated endpoints [FS-1268]

- packages/core/src/Account.ts
- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/mls/types.ts
- packages/core/src/util/TypePredicateUtil.ts
Adds logic for `MLS` conversation to recover from `404` error in quick sync flow.
> feat(core): recover mls conversation from quick sync 404 error [FS-1172]

- packages/core/package.json
- packages/core/src/conversation/message/MessageBuilder.ts
- yarn.lock
This will allow sending calling message to the `selfConversation` referring to a call in a different conversation
> feat: Add conversationId to calling messages

- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
This will allow the consumer to be warned that a new client sent a message. 
This allows detecting a change in verified devices (an potentially degrade a conversation verification state if a message from an unknown device has been sent)
> fix: Warn consumer when a new client is detected

- packages/core/src/index.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/DecryptionErrorGenerator/DecryptionErrorGenerator.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/DecryptionErrorGenerator/DecryptionErrorGenerator.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/index.ts
We do not have perfect handling for decryption error code on coreCrypto side, but we can still handle a bunch of different scenarios that will improve user facing errors on the front-end
> fix: Improve granularity of coreCrypto decryption error handling

- packages/api-client/src/event/ConversationEvent.ts
- packages/core/src/messagingProtocols/mls/EventHandler/ConversationEvent/events/messageAdd/messageAdd.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/mls/MLSService/subconversationGroupIdMapper.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/subconversationGroupIdMapper.ts
Will allow parsing and decrypting messages that are sent in a subconversation.
> feat: Keep track of subconversation group ids

- .eslintrc.json
Adds `"@typescript-eslint/no-floating-promises": "warn"` eslint rule.
> chore: add eslint warning for floating promises

- packages/react-ui-kit/src/Form/Checkbox.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Checkbox.test.tsx.snap
[[ACC-398]](https://wearezeta.atlassian.net/browse/ACC-398)
- checkboxes get sqished by the label in some modals / when the font size is set to max
- assign a min-width to the checkbox
[ACC-398]: https://wearezeta.atlassian.net/browse/ACC-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> runfix: prevent checkboxes from squishing [ACC-398]

- packages/core/src/Account.ts
Since when creating an MLS device we already need to init it, we need to avoid initializing coreCrypto a second time
> fix: Avoid init MLS twice

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.types.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CryptoClient.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CryptoClient.types.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CryptoboxWrapper.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.mocks.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.types.ts
- packages/core/src/messagingProtocols/proteus/Utility/SessionHandler/SessionHandler.test.ts
This will avoid loading both CoreCrypto and Cryptobox in the same instance of the webapp (since only one of them is going to be used at a time).
This also cleans up which components are aware of CoreCrypto/Cryptobox. Now only the `CryptoClient` are aware of those classes and know how to build them
> refactor: Lazy load crypto clients 

- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CryptoboxWrapper.ts
We currently do not upload new prekeys to the backend when they are generated. This fixes it
> fix: Do call onNewPrekeys handler on cryptobox wrapper

- packages/core/src/messagingProtocols/mls/EventHandler/EventHandler.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Allows the consumer to subscribe to epoch changes. 
`mlsService.on('newEpoch', ({epoch, groupId}) => {/*...*/});`
> feat: Emit event when MLS conversation epoch changes

- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Use `string` type for `groupId` instead of `Uint8Array` in exposed api.
> refactor(core): use string for group id in conversation exists

- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.mocks.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/Utility/SessionHandler/SessionHandler.test.ts
- packages/core/src/messagingProtocols/proteus/Utility/SessionHandler/SessionHandler.ts
This cleans up a bit the unit tests in preparation of handling partial message sending. 
The idea is that when a federated backend is down and some messages could not go through, we will need to warn the sender that some recipients will not be able to receive those messages. 
When creating a session, we will need to detect sessions that could not be created because the remote backend is down, this is an effort to prepare for this
> refactor: Cleanup session unit tests to prepare for partial message sending

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
There's no need to refetch subconversation after joining it. From now consumer will get members from their local client (`corecrypto.getClientIds()`) and use them to update epoch info to AVS. (Will add a follow up PR on webapp side). This way we'll be sure we're updating AVS with our actual state, not with what we fetch from backend.
> runfix(core): reduce number of api calls to subconversation endpoint

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
req_new_epoch callback from AVS require client to advance epoch number by calling `corecrypto.updateKeyingMaterial()`, this PR will makes `renewKeyMaterial` public that will enable webapp to use the api.
> feat: expose material key renewal api

- packages/core/src/Account.ts
There are cases where a race condition could happen because we are not awaiting the external incoming event handler to be finished before processing the next event. 
If the consumer needs to do some async task (like saving the event to the DB) it might not expect the next event to come in **before** this task is actually done. 
It is important here to await for the consumer to be done before processing the next event
> fix: Await incoming event handler

- packages/core/src/Account.ts
- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
Removes the method that was used to fetch all conversation's participants in a hacky way + removes ConversationService dependencies that are not needed anymore.
Improves the api of the method we're using instead.
> refactor(core): remove unused deprecated method and improve fetchAll api

- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CryptoClient.types.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CryptoboxWrapper.ts
https://wearezeta.atlassian.net/browse/FS-1542
Access last resort prekey from `corecrypto` directly - no need to generate it using hardcoded last key id number (`65535`).
Last prekey and its id remained the same after changes:
I've also removed `LAST_PREKEY_ID` from our types as it did already exist in `@wireapp/proteus` package and will be consumed by `cryptobox` implementation only (Did a `console.log` to make sure the value is exactly the same).
> feat(core): access last resort prekey and its id from corecrypto [FS-1542]

- packages/api-client/src/tcp/ReconnectingWebsocket.ts
we already have a ping/pong implementation but it is only used to keep the web socket connection alive.
this PR will change the implementation of our ping/pong system to trigger a reconnect if the ping pong is is timed out
> fix: Trigger reconnect method on ping pong failure (SQSERVICES-1896)

- packages/core/src/conversation/message/MessageService.ts
Since the `SessionHandler` already has the logic of fetching prekeys when the sessions do not exist, there is no need to also do it in the `reencryptForMismatch` method (the prekeys are going to be downloaded in the `proteusService.encrypt` method
> refactor: Remove duplicated session creation logic

- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/Utility/SessionHandler/SessionHandler.ts
Since `initSessions` and `initSession` share the same logic, `initSession` could actually use the former to generate a single session
> refactor: factorize session creation logic

- packages/core/src/conversation/message/MessageService.test.ts
- packages/core/src/conversation/message/MessageService.ts
When a mismatch happens but we do not already have a recipients that is part of the `domain` of the mismatch, the app currently crashes.
> fix: Avoid crashing when a mismatch happens on a domain we are not aware of

- packages/api-client/src/user/UserAPI.ts
- packages/core/src/broadcast/BroadcastService.ts
- packages/core/src/conversation/message/MessageService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/Utility/PreKeyBundle/PreKeyBundle.ts
- packages/core/src/messagingProtocols/proteus/Utility/SessionHandler/SessionHandler.test.ts
- packages/core/src/messagingProtocols/proteus/Utility/SessionHandler/SessionHandler.ts
When we want to encrypt a message for recipients for whom we do not have a session already we need to:
- fetch some prekeys for those users 
- create a session from those prekeys
- encrypt the message for those sessions
If a backend holding those users is down, the prekeys listing will partially fail (and return and error object containing the users we could fetch prekeys for). 
That list is then forwarded to the `encrypt` method that will return a `failed` user list
> feat: Warn consumer that some prekeys could not be fetch when encrypting a message

- packages/react-ui-kit/src/Identity/colors-v2.ts
- packages/react-ui-kit/src/Identity/colors.ts
Something that has bothered me for ages: our COLOR variables are woefully untyped. 
Before: 
https://user-images.githubusercontent.com/37285713/222223047-5dacec87-fc0e-4612-a777-3fc7ef135f51.mov
After: 
https://user-images.githubusercontent.com/37285713/222223093-e90361cb-43b4-44ad-a6a7-91247c56f66b.mov
> feat: improve typing for color packages

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/mls/MLSService/stores/subconversationGroupIdStore/subconversationGroupIdStore.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/stores/subconversationGroupIdStore/subconversationGroupIdStore.ts
Improves naming inside `subconversationGroupId` store module. 
Covers one extra case where subconversation entry can be removed from the store.
> refactor(core): subconversation group id store

- packages/core/package.json
- packages/core/src/conversation/ConversationService/ConversationService.types.ts
- packages/core/src/conversation/message/MessageService.test.ts
- packages/core/src/conversation/message/MessageService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/Utility/SessionHandler/SessionHandler.ts
- yarn.lock
When a prekey could not be retrieved from backend, we need to warn the consumer that sending the message failed for those users
> feat: Forward users for which message could not be encrypted to sender

- packages/api-client/src/client/ClientAPI.ts
- packages/core/package.json
- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/CoreCryptoWrapper.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/PrekeysTracker/PrekeysTracker.store.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/PrekeysTracker/PrekeysTracker.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/PrekeysTracker/PrekeysTracker.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CryptoClient.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CryptoClient.types.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CryptoboxWrapper.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.mocks.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- yarn.lock
Currently the number of prekeys that are available are only computed by the client. 
Which can easily lead to an out-of-sync state between client and backend. 
In order to make sure we are in sync, when we init the device, we query the backend for all the prekey ids we have for this client and store this in a local state. 
This way backend is always the single source of truth
> fix: Improve prekeys tracking between client and backend

- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/CoreCryptoWrapper.ts
User logged in on removed device ended up crushing on conversation view and not getting logged out properly (device was not completely deleted, storage was not cleared). For more details see [ticket](https://wearezeta.atlassian.net/browse/FS-1562).
Due to rust lang specificity, only 1 "strong reference" is being allowed to be alive at a time - reference gets created every time we call any `corecrypto` method (and gets cleared after the method is done executing). It was possible that in case of deleting other self device, it was not logged out properly because client tried to call `.wipe()` method while it was decrypting a message (`.decryptMessage()` was still executing).
CoreCrypto implemented new api - `.strongRefCount()` method, allowing us to check whether corecrypto is ready to call …
> fix(core): wait until corecrypto is ready to call .wipe method [FS-1562]

- packages/core/src/Account.ts
- packages/core/src/client/ClientService.ts
This will ensure that we don't try to send messages for a device we will never have a session with (namely the current device)
> fix: Make sure current client is not duplicated in database

- packages/api-client/src/user/UserAPI.ts
- packages/core/src/user/UserService.ts
- packages/core/src/util/TypePredicateUtil.ts
This will adapt the API client to receive partial list of users (for when one federated backend is down). 
BREAKING CHANGE: The return type of `postListUser` will now always wrap the result in a full `UsersResponse`
> feat: allow partial user listing for federated backends

- packages/core/src/conversation/message/MessageBuilder.ts
Adding the `messageId` to the parameters of `buildFileMetaDataMessage` allows for overwriting the optimistic event of a message that failed to be sent in database with newly sent metadatas
> feat(core): allow retrying to send asset metadatas on an existing message

- packages/api-client/src/user/UserAPI.ts
the `found` field will always be present (even if empty)
> refactor: Sync user endpoint with backend types

- packages/api-client/src/conversation/MessageSendingStatus.ts
`failed_to_send` is optional on backend side. We need to align this in the types
> fix: Align failed_to_send signature with backend

- packages/promise-queue/src/PromiseQueue.ts
The PromiseQueue should be able to run in a web and node environment. Hardcoding `window.setInterval` doesn't allow nodejs to run that code
> fix: make PromiseQueue node compatible

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
From version 4 this endpoint needs at least an empty body.
https://staging-nginz-https.zinfra.io/swagger-ui/#!/conversations/createConversationCode
> fix: Add empty body to code creation endpoint (FS-1836)

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/NewConversation.ts
- packages/api-client/src/conversation/data/ConversationProtocolUpdateData.ts
- packages/api-client/src/event/ConversationEvent.ts
Adds a request handler for `PUT: /conversations/{domain}/{id}/protocol`.
Protocol field value update from `"proteus"` to `"mixed"` is the first step of conversation migration flow. For more details see tech use cases under https://wearezeta.atlassian.net/wiki/spaces/CORE/pages/746488003/Proteus+to+MLS+Migration.
[swagger doc](https://nginz-https.anta.wire.link/v4/api/swagger-ui/#/default/put_conversations__cnv_domain___cnv__protocol)
> feat(api-client): put conversation protocol [FS-1888]

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/event/ConversationEvent.ts
- add event to ConversationEvent union type
- improve js doc of the method
- return null as response if request status was 204 - it means that protocol was not updated (it already had the value we wanted it to update to) (see https://nginz-https.anta.wire.link/v4/api/swagger-ui/#/default/put_conversations__cnv_domain___cnv__protocol)
> feat(api-client): improve conversation protocol put request handler

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
It's possible that `mlsService.getKeyPackagesPayload` can return empty array, we usually call `mlsService.addUsersToExistingConversation`. Calling this method with empty array of keypackages will make `corecrypto` throw an error. We want to skip calling this method.
> runfix(core): don't call addUsersToExistingConversation with empty list

- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/EventHandler/EventHandler.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- fixes types for onEpochChanged callback to async
- does check if group does exist, before checking epoch number and emitting an event (when `corecrypto.getEpoch` is called with `groupId` that does no longer exists, an error is thrown)
> runfix(core): emit new epoch event only if the group still exists

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/conversation/ConversationService/ConversationService.types.ts
backend response type for failed_to_send on mls is actually QualifiedId[] not QualifiedUserClients
> fix: Correct type for mls failed_to_send (FS-2030)

- yarn.lock
Reverts recent @types/react version bump as it introduced some breaking changes (don't really have time to deal with those right now, and it's breaking the CI, preventing us from publishing new versions of core)
> Revert "chore(deps-dev): bump @types/react from 18.2.7 to 18.2.8"

- packages/api-client/src/asset/AssetAPI.test.ts
- packages/api-client/src/asset/AssetAPI.ts
- pass tokenAsParam = false to set the access token using Authorisation header
> fix: pass tokenAsParam = false to set the access token using Authorisation header

- packages/core/__mocks__/@wireapp/core-crypto.ts
- packages/core/package.json
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/CoreCryptoWrapper.ts
- yarn.lock
- Updates corecrypto, it fixed the issue where self key package was consumed when creating new MLS group.
- We are hardcoding ciphersuite to the only one we support currently, this is the only one that will be delivered with Zulu release (we will need to read it from team-settings in the future).
> runfix: update core-crypto

- packages/api-client/src/conversation/NewConversation.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
`creator_client` field is not needed anymore in api v4. It was being used only when creating new MLS group, and since MLS is not enabled on api versions <4, so we can simply remove it and pretend it never existed. See https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/761266263/API+changes+v3+v4
It also removes `selfUserId` from the conversationData we pass as a payload - I've made it a separate function param.
> runfix: remove creator_client field from conversation creation payload

- .github/workflows/release_beta_package.yml
I feel that this might fix the issue with task being auto-cancelled, maybe this cancel-action does not play well with `workflow_dispatch` trigger.
> runfix: remove canceling tasks

- .github/workflows/release_beta_package.yml
The issue of this manual action being cancelled was the fact that after it was published once, given branch contained the commit: `chore: Publish [skip ci]` and there was a rule in this script (copied from the auto release from main script), that was skipping (cancelling) the job when `skip ci` or `ci skip` was included in last commit. 
The solution is to simply remove this field. Since this action is manual it won't get re-triggered after pushing another publish commit into the branch (what would happen if this rule was not included in the auto-deploy main branch script).
> runfix: manual task cancelled when last commit was publishing a package

- packages/react-ui-kit/src/Form/Tooltip.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Tooltip.test.tsx.snap
- STR: Navigate to reaction pill with keyboard
Actual: The pill is highlighted, but the tooltip box containing info about emoji name and amount of people is not displayed
Expected: The tooltip box should appear when keyboard navigation is used to get to the reaction pills
> fix: [Web] Reactions: Keyboard navigation - Focus state of reaction pill does not show tooltip box

- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Fail fast and let the consumer catch the error instead of silently returning `null` for `uploadCommitBundle` method. Method's response is not always read, therefore it's possible that the method will silently fail without the consumer knowing that something went wrong, when error is thrown we have to make sure this call is handled properly with try/catch.
> runfix: upload commit bundle throws error

- package.json
Don't update changelog files of packages when beta version of package is released.
> runfix: skip changelog update when releasing beta version of package

- packages/api-client/src/team/feature/Feature.ts
Adds `supportedProtocols` field to `mls` feature config.
> feat(api-client): add supportedProtocols to mls feature config

- packages/api-client/src/client/RegisteredClient.ts
- packages/core/src/client/ClientService.ts
- add `last_active` field to client entity
- Since new field was added, I've noticed that the local client (under `'local_identity'` key in our local store) was never updated with the client fetched from backend. Since we are fetching the client anyway to see if it still exists on backend I think it makes sense to update the entry in the local store with the fresh one in case it was updated.
> feat(api-client, core): parse client last active field [WPB-2186]

- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Some refactoring in mls service:
- created a separate method to establish empty mls conversation (just register it with epoch 0 without adding other users or sending empty commit)
- refactored some methods to expect string group ids instead of uint8array
> refactor: method to register empty mls conversation

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
void operator evaluates the given expression and then returns undefined what prevents consumer from catching potential error thrown by corecrypto. void keyword is not needed there.
> runfix: properly await mls conversation creation

- packages/store-engine-dexie/package.json
- yarn.lock
This will allow the consumer of the library to set the desired version of Dexie (as long as it's above 3.2.0). 
This will allow the webapp to actually upgrade Dexie in the future (and avoid conflicting versions)
> fix: more flexible dexie version

- packages/api-client/src/conversation/MessageSendingStatus.ts
- packages/core/src/conversation/message/MessageService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
backend response for proteus messages that are queued after failing to reach the recipient changed for `failed_to_send` to `failed_to_confirm_clients`
> refactor: rename failed_to_send to failed_to_confirm_clients (WPB-3393)

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/ConversationError.ts
- packages/api-client/src/conversation/FederatedBackendError.ts
- packages/api-client/src/conversation/index.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
This creates a generic error class for federated backend errors (handles unreachable backends and non connected backend later)
> refactor: Generic federated backend error class

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/FederatedBackendsError.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/userDomainFilters.ts
This will add the ability to handle backend errors when adding users to a conversation. 
If users from an unreachable backend are added, then those users are filtered out and marked as `failedToAdd` in the response.
> feat: Handle adding users that are on an unreachable backend

- packages/api-client/src/conversation/Conversation.ts
- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
Adds a method to establish (register) MLS conversation, when registering a group fails, check the epoch number of remote conversation and:
- if it's `0` it means the group was not established yet, wipe and retry
- if it's more than `0`, it means that the group was already established by you / the other user, we should join with external commit.
> feat(core): establish mls 1to1

- packages/api-client/src/conversation/FederatedBackendsError.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/errors/FederatedBackendsError.ts
- packages/core/src/errors/index.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/WithMockedGenerics.test.ts
This will allow the core to handle the case of 2 backends not connected to each other when it comes to creating a new conversation and adding users to a conversation. 
The gist is:
- when adding users in a conversation that are from 2 non-connected backends, the `addUsersToConversation` will adds all the other users and return the users from those unconnected backends as `failedToAdd`;
- when creating a conversation with users from 2 non-connected backends, the conversation creation will fail with a `NonFederatingBackendsError`
> feat: Handle backend non federating errors

- packages/promise-queue/src/PromiseQueue.ts
Changes the type of interval to the type that is returned from `setInterval` and expected by `clearInterval` methods. Should fix failing CI.
> runfix(promise-queue): correct return type for interval

- packages/api-client/src/conversation/Conversation.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/conversation/ConversationService/ConversationService.types.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/WithMockedGenerics.test.ts
- packages/core/src/testUtils/index.ts
This will make sure all the methods that add users to a conversation return the same format.
```js
{
failedToAdd: {reason: ..., users: ...}
// method specific data
}
```
> refactor: harmonize failedToAdd response in conversation creation and user addition

- packages/core/src/messagingProtocols/proteus/ProteusService/DecryptionErrorGenerator/DecryptionErrorGenerator.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/DecryptionErrorGenerator/DecryptionErrorGenerator.ts
The logic would fail when we would have received 0 as `proteusErrorCode` or `code` when decryption error is handled. The reason behind it is simply 0 being a falsy value.
The fix is to simply check typeof the value to match `number`.
> runfix: decryption error generator

- packages/core/src/Account.ts
We are leaking many internal services from Account.ts to the outside world.
Long term, we want to get rid of all of them and leak the functions that the webapp absolutely needs to run, in a more descriptive way.
MLS is a low-hanging fruit since the webapp currently does not use it.
> feat: stop leaking the MLS service to the outside world

- packages/core/src/Account.ts
Reverts wireapp/wire-web-packages#5414
We actually user mls everywhere in the webapp, its proxied as "mlsService"
> fix: re-expose mls service publicly

- packages/core/src/Account.ts
- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/CoreCryptoMLSErrors.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/mls/types.ts
- packages/core/src/util/TypePredicateUtil.ts
Adds recovery mechanism to mls message decryption failure. 
When `corecrypto.decryptMessage` fails with "WrongEpoch" error, it means that the client got out of sync - missed some handshake messages - and is receiving messages from a new epoch it is not a member of. 
At this point we should fetch conversation from backend compare local epoch number with the epoch number on the remote conversation and if there's no match - rejoin conversation with external commit.
This PR also extends `ConversationService` with event emitter. `MLSConversationRecovered` event is emitted after client has successfully rejoined a group. Consumer should subscribe to this event and react to it by inserting a system message into the chat (this will be handled by the webapp)
> feat: mls decrypt error recovery [WPB-523]

- packages/api-client/src/APIClient.ts
#5416 was merged a little too early. Api v5 is not yet ready on backend. 
We need to revert for now in order to still be able to work on MLS before api v5 is out
> fix: re-enable mls on api v4

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
There's no need to check epoch numbers if group is not even established locally.
> runfix(core): handling epoch mismatch for unestablished groups

- packages/api-client/src/http/HttpClient.ts
After `axios` version has been bumped to `> 1.1.3`, we can remove `as any` and the comment explaining the work-around. Webpack build seems to pass now 👌
> refactor(api-client): improve axios types

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.types.ts
- packages/core/src/messagingProtocols/mls/types.ts
Adds ability to specify `defaultCiphersuite` and `defaultCredentialType` to be specified by a consumer via MLSService config.
> feat: specify default ciphersuite

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Splits the concerns of mls group just existing and being established:
- Group exists if `coreCrypto.conversationExists` returns true, the epoch number doesn't matter, could be `0` (initial number after group creation) or more (after some users were added or just key material was updated).
- We say that the group is established when it exists (see point above) and epoch number is at least 1 - it means that at least one commit was sent in the group. There's a new method that checks that on `MLSService`: `mlsService.isConversationEstablished`.
If group is established (epoch number is at least `1`) we know that backend is aware of this group since the commit bundle needed to be successfully uploaded, processed by backend and accepted by one of the members. If group only exists (with epoch …
> refactor: mls conversation exists

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
This will make a method for establishing mls 1:1 conversation check if the group is already established first before trying to register it. Since both users are very likely to do this operation at the same time, only one of them will register the group successfully, other user will either receive a welcome message or join with an external commit.
Example: 
- User A sends a connection request to user B.
- B accepts a connection
- Users `A` and `B` are being sent an event about connection being accepted
- They both try to establish MLS group at at this point, a "race" begins
- Only one of them will successfully establish MLS group, the other one will receive an error from backend when trying to upload a commit bundle to backend (`"group was already established!"`)
- User that has won the …
> runfix: check if 1:1 is already established before registering it

- packages/core/src/Account.ts
We were mistakenly using `nbPrekeys` (for proteus prekeys) variable to config `nbKeyPackages` (for mls key packages).
`nbKeyPackages` is set to 100 by default and can be configured by a consumer (webapp) via `cryptoProtocolConfig.mls` object.
> runfix: do not use number of prekeys for number of mls key packages

- packages/api-client/src/APIClient.ts
This will make sure only to enable MLS only if backend api is v5
> fix: Finalize backend api v4

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
This includes:
- a refactoring to use the same method to generate base qualified conversation urls
- making sure the `/conversation/{domain}/{id}/(self | receipt-mode | message-timer)` endpoints can be hit on a federated env
> feat: make /self and /receipt-mode endpoint federation ready

- packages/bazinga64/src/Encoder.test.ts
- packages/bazinga64/src/Encoder.ts
base64url is a different standard than the default base64.
Since we use base64url data now in the E2EI - flow, enhancing our Encoder seems like a good idea.
> feat: add toBase64Url to Encoder

- packages/core/src/conversation/message/MessageBuilder.ts
This will make sure that the `lastRead` event we send to sync current user's devices will contain qualified information about the conversation being updated
> fix: Add the qualified conversation ID to last read messages

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
It can happen that the client the user is using was using only proteus initially, and later after MLS feature was enabled, it has upgraded to mls (by calling `CoreCrypto.mlsInit`). 
Previous flow of registering/initialising mls client goes as follows:
- check if corecrypto client exists (doesn't matter if it support mls already or not)
- if it exists, call mlsService.initClient()
- if it does not exist, call mlsService.registerClient()
Only `.registerClient()` method included uploading a public key and key packages to backend. When client did already exist previously, but mls client was not yet created, we were calling only `.mlsInit()` without uploading key packages / public key to backend. Such client ended up being mls device without any key packages uploaded to backend, therefore …
> runfix: upload kp after upgrade to mls device

- packages/api-client/src/client/RegisteredClient.ts
`mls_public_keys` field is not optional and is empty object (`"{}"`) by default.
> runfix(api-client): mls_public_keys field required

- packages/core/src/Account.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
We (and other platforms) were missing a check for amount of local key packages after receiving a welcome message. We were performing a check only once every 24h. This PR adds this functionality.
Explanation:
When somebody tries to add you to a MLS group, they need to first claim one of your key packages you've uploaded to backend when registering MLS device. After successfully claiming your key package, you're being sent a welcome message. After welcome message is processed, corecrypto "consumes" your key package. Minimal number of key packages client should have uploaded to backend is half of the default amount of keys which is 100 by default (so minimal required number is 50 by default).
We need to keep track of the local amount of keypackages, to know when we should generate new keys …
> feat: refill check on welcome message [WPB-4773]

- packages/api-client/src/APIClient.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
There's undesired behaviour on backend when sending a commit bundle with external commit (e.g when joining mls groups you are member of after registering completely new client). When request is being processed (we've not received a response from backend yet), it can happen that we will receive a bunch of messages on different a "channel" (websocket in this case). Those messages are usually mls messages we cannot decrypt anyway since external join (external commit) was not fully processed, and we're not yet a group member locally.
Current behaviour:
- we send a commit bundle to backend
- while request is being processed we receive some messages via websocket we cannot decrypt anyway, we're thrown a bunch of errors from core-crypto
- response from backend finally arrives, but we don't have …
> feat: lock websocket when uploading a commit bundle to backend

- packages/api-client/src/event/TeamEvent.ts
Omits data attribute from base team event type. It allows us to narrow down config field after providing proper name field on event object. It is not overwritten by default but extended with what comes after `&`.
Before:
`TeamEventData` was not properly overwritten (we could still access fields on different type of config update event)
After:
We ignore generic `TeamEventData` type on `data` field from base type. Type is narrowed only to the one chosen with `name` field
> runfix(api-client): remove data field from team event base type

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/conversation/ConversationService/ConversationService.types.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.types.ts
Adds a recovery mechanism to mls message sending when failed with `"mls-stale-message"` error. When error is catched, we should rejoin the group with external commit, retry to send a message once and notify consumer (webapp) that mls group has recovered from epoch mismatch. Consumer will then insert system message into the recovered conversation.
> feat: recover from mls stale message error

- packages/core/src/util/LowPrecisionTaskScheduler/LowPrecisionTaskScheduler.ts
- packages/core/src/util/RecurringTaskScheduler/RecurringTaskScheduler.test.ts
- packages/core/src/util/RecurringTaskScheduler/RecurringTaskScheduler.ts
Recurring task scheduler was never resuming a task after app was reloaded. We were storing only last fire date, which simply didn't exist before the task was run for the first time.
We store `firingDate` instead and make sure it's stored even before the task runs for the first time. If `firingDate` already exists, we just load it from the store.
> runfix: recurring task scheduler not resumed after reload

- packages/core/src/Account.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/welcomeMessage/welcomeMessage.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/storage/CoreDB.ts
- packages/core/src/testUtils/index.ts
- packages/core/src/util/LowPrecisionTaskScheduler/LowPrecisionTaskScheduler.test.ts
- packages/core/src/util/RecurringTaskScheduler/RecurringTaskScheduler.test.ts
- packages/core/src/util/RecurringTaskScheduler/RecurringTaskScheduler.ts
- packages/core/src/util/TaskScheduler/TaskScheduler.ts
Makes recurring task scheduler more generic and allows its consumer to specify storage where events will be stored.
Now `core` has its own recurring task scheduler that is using core's database (indexedDB) to store the events.
> runfix: recurring task scheduler with indexeddb store

- packages/core/src/util/RecurringTaskScheduler/RecurringTaskScheduler.ts
Use `unknown` as task's return type so we can pass a function that returns anything (not necessarily `void`).
> refactor: use unknown for recurring task return type

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/CoreCryptoMLSError.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Adds a method for trying to establish a mls group for mixed conversation. This logic did previously live in webapp, but since it's plain core/mls logic, it can be moved to core package's `ConversationService`.
> feat: try establishing mls group for mixed conversation

- packages/core/src/conversation/ConversationService/ConversationService.ts
Adds `getMLS1to1Conversation` method to core's conversation service, so the consumer (webapp) can call it instead of calling api client directly.
> feat: add getMLS1to1Conversation method to convo service

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
We were never clearing pending proposals tasks after MLS group was wiped. Trying to do it after we're no longer a group member could result in CoreCrypto throwing `"Conversation does not exist"` error.
This PR also improves the task key to be `pending-proposals-${groupId}` instead of just groupId.
> runfix: cancel pending proposals task on group wipe

- packages/core/src/client/ClientDatabaseRepository.ts
- packages/core/src/client/ClientService.ts
Since is_verified is for the current proteus implementation, and we need to have proteus and MLS live side by side for the foreseeable future, we introduce a new value named is_mls_verified.
> feat: add new value to client in database

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIService.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/index.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/mls/index.ts
- packages/core/src/messagingProtocols/mls/types.ts
We need to export more E2EI-related types for the web app / consumers of core.
> feat: export needed e2ei types

- packages/core/src/Account.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.test.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Moves subconversations related logic to new `SubconversationService`. 
Also adds some logic that previously lived on webapp side.
Added a bunch of test cases.
> refactor: move subconversations logic to separate service

- packages/core/src/self/SelfService.test.ts
- packages/core/src/self/SelfService.ts
- packages/core/src/user/UserService.ts
Adds a method for fetching other user's supported protocols to `UserService` so we don't have to maintain any logic on consumer (webapp) side and we do not call apiClient directly.
> feat: add get supported protocols to user service

- packages/api-client/src/APIClient.ts
TIL: `finally` block does execute **BEFORE** `return` or `throw` statements are executed in `try`/`catch` block.
We want to make sure wrapped callback is completely done executing before unlocking the socket.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#the_finally_block
> runfix(api-client): unlock socket after method is done executing

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Upload of prekeys was broken in case of a new client and active E2EI
This fixes it.
> fix: upload of publicKeys in case of active E2EI

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
CoreCrypto is using base64 encoded strings to identity users. 
In order for consumers of the `core` not to have to implement the logic of mapping base64 encoded userIds to regular userIds, we map the userIds right before returning the identity.
> feat: Map coreCrypto userIds to regular userIds

- packages/core/src/Account.test.ts
- packages/core/src/Account.ts
The entire `client` is needed to enroll for E2EI. But the consumer doesn't necessarily need to store this client, so the core can hold on to it and keep it around when enrolling later on
> fix: Keep local instance of the registered client

- packages/api-client/src/client/ClientAPI.ts
- packages/api-client/src/client/NewClient.ts
- packages/api-client/src/client/RegisteredClient.ts
- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
We have a problem in the webapp, in the case of active E2EI, that we need to know if the current client is a fresh client.
This PR adds a function to E2EIServiceExternal to solve this issue for consumers.
This PR also enhances the typing of the MLSPublicKeys, which are used to determine if a client is freshly created or already in use.
> feat: add export for webapp to check if the current mlsClient is a new one

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
The current E2EI enrollment only supported fresh clients. This change adds the possibility to rotate existing certificates (for renewal).
> feat(E2EI): add possibility to rotate a active certificate 

- packages/core/src/Account.ts
- packages/core/src/notification/NotificationService.ts
Client id was not properly passed to `getLastNotification` method. `this.apiClient.clientId` was `undefined` at this point. Client was trying to fetch and process all the notifications (including mls messages) directed to user, not this new client. 
It could result in `"You have missed some messages"` system message being injected into all the conversations, event though the client is completely new and it should not receive those messages since the device is new and was not listed in message's recipients when the message was sent.
> runfix: include clientId on last notification api call

- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/SelectStyles.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
- `display: none` on the control component of the Select prevent's keyboard navigation completely
- the select menu isn't in focus when clicking the button to show the Select-Group
- replace `display: none` by `position: absolute, z-index: -9999`
- add the react `autoFocus` prop to the select component when it is of type "group"
> runfix: allow keyboard navigation in group-select

- packages/core/jest.setup.ts
This should fix ci by checking whether atob/btoa already exists before overwriting it.
> chore: fix ci

- packages/core/src/conversation/SubconversationService/SubconversationService.test.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.ts
In MLS conference calls we update avs with current epoch info every time subconversations epoch changes or every time its parent conversation's epoch changes. For the latter, we were mistakenly updating subconversation's epoch info with parent's conversation epoch instead of actual subconversation's epoch. It was causing some errors in avs making users unable to send/receive audio/video.
> runfix: always use subconversation epoch number

- packages/core/src/Account.ts
Previously we determined if E2EI should be active only via the team-settings. 
This PR also takes the local settings into consideration and prevents unwanted behaviour.
> fix: use local settings and team settings for e2ei

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/util/fullyQualifiedClientIdUtils.ts
the method `getUserIdentities` from CoreCrypto doesn't list the MLS basic devices in the return value. But we need to indicate those devices as `not downloaded` so we need to be aware of those. 
To circumvent this issue, we:
- ask CoreCrypto to give us all the devices known in the conversation (both with identities and basics)
- ask CoreCrypto the devices that have identities
- merge both values in order to add basic devices to the return value
> fix: Add MLS basic devices to the return value of user identities

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
remove the refreshActiveCertificate dependency instead use CC hasActiveCertificate and initialise MLSService with e2eServiceExternal
> feat: replace refreshActiveCertificate with hasActiveCertificate and initialise MLSService with e2eServiceExternal

- packages/api-client/src/APIClient.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/IncomingMessagesQueue/IncomingMesssagesQueue.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/IncomingMessagesQueue/index.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.test.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
When uploading a commit bundle to backend, there's a chance we will receive a bunch of mls message before the response from this call is returned. Before that happens, we cannot decrypt those messages.
A previous solution for that was locking the whole websocket and unlocking it after receiving a response from backend and merging a commit locally. The downside of this approach was that while loading the app initially for the first time, when client was joining all the mls groups with external commit, we were spamming with lock/unlock websocket methods.
This PR introduces a better solution - an incoming MLS messages queue for each conversation. Instead of processing `conversation.mls-message-add` straight away, we put it in the queue which is unlocked by default (so we do not change the …
> feat: add a queue for incoming mls messages

- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
External proposal have been replaced by external commits for a while. 
This method is not up to date with e2ei. As it's not needed now, let's remove it and avoid confusion
> fix: Remove outdated sendExternalJoinProposal method

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Storage/E2EIStorage.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
This cert storage was a leftover from early development. Certificates are stored by core-crypto already and should be retrieved from there.
> feat(e2ei): remove device storage for e2ei cert

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
This hardcoded value is used instead of the value from the certificate server when set lower. So we need to up it to at least 90 days to match the server settings.
> feat(e2ei): update the certificate expiry time to 90 days 

- packages/core/src/Account.test.ts
- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/types.ts
- packages/core/src/secretStore/encryptedStore.ts
- packages/core/src/secretStore/secretKeyGenerator.test.ts
- packages/core/src/secretStore/secretKeyGenerator.ts
This will make sure the `secets-db ` is wiped when the account is wiped. 
For that, we need to keep track of the secretDB instance in order to wipe it. So we need to change a bit how secret keys are generated. 
Previously generating a secret key would fire up a DB that would be closed right after (and potentially re-openned later on). 
Now we always create the secret DB and eventually use it to generate a key
> fix: Delete secrets store when account is wiped

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
For consistency, we always use the same source of truth for the cipher suite used in the core (the one given in the general config).
> fix: Use config ciphersuite when querying e2ei

- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/AcmeService.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/schema.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
Before the first enrolment, we need to fetch the local root certificate and pass it to core-crypto for it to be validated.
This should be done only once.
> feat: fetch local certificate root [WPB-3338]

- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/AcmeService.ts
`/directory` is a part of discovery url and will be included in e2ei configuration in team settings admin panel.
> runfix: remove hardcoded directory path

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/AcmeService.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/AcmeService.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIService.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/Authorization.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/DpopChallenge/DpopChallenge.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/OidcChallenge.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/Order.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Storage/E2EIStorage.schema.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Storage/E2EIStorage.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
This is preparation of installing core-crypto 1.0.0-rc.31 that will change the format of the challenges returned.
It improves a few areas:
- error reporting (avoid, as much as possible, catching errors in the deep layers of the flow, and let them bubble up)
- types refactoring (avoid having duplicated definitions)
- minor code improvements
> refactor: Improve E2EI enrollment error handling

- packages/core/src/messagingProtocols/mls/E2EIdentityService/Storage/E2EIStorage.ts
> fix(core): replace btoa with bazinga in e2ei storage

- packages/core/package.json
- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/AcmeService.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/schema.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/OidcChallenge.ts
- packages/core/src/util/RecurringTaskScheduler/RecurringTaskScheduler.ts
- yarn.lock
Fetch cross-signed (federated) certificates from acme server and pass them to core-crypto. We do this periodically - first on app load and then every 24h.
This PR also bumps core-crypto to version `.rc33`.
> feat: federation cross signed certs [WPB-5391]

- packages/core/package.json
- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/AcmeService.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/schema.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/storage/CoreDB.ts
- yarn.lock
Once corecrypto finds any new crl distribution points (array of urls):
- for every URL in the list, fetch CRL
- pass CRL to e2ei_register_crl
- it will return expiration time and `dirty` boolean flag
- we set a new timer that will execute a task* on expiration time
- if it was `dirty`, call `e2eiConversationState` for every conversation
This PR also bumps core-crypto to version `rc32`
> feat: maintain revocation list timers

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
Changed from days to seconds with latest @wireapp/core-crypto
> fix(e2ei): certificate duration

- packages/core/src/Account.ts
- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
When detecting epoch mismatch in a "conference" subconversation (a MLS group we use for mls calls) we were mistakenly rejoining its parent conversation via external commit instead of rejoining the actual subconversation.
> runfix: epoch mismatch subconversations

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/util/qualifiedIdUtil.ts
- MLS service is now a dependency of `E2EIServiceExternal`
Added a method to get all the mls group user identities - it's needed to calculate the list of degraded users when adding a client without a certificate into the group. We were using webapps conversation.particupating_user_ids() which is not always up-to-date with mls group state in core-crypto. Before receiving member-join event the list of participants was still empty even though user was already a member of mls group.
Webapp PR will follow.
> runfix: add method to get all group user identities

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIService.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
When calling `account.enrollE2EI` you can now give a `certificateTtl` that will define the number of days the generated certificate will be valid
> feat(e2ei): Allow configuring the certificate time to live

- packages/api-client/src/client/NewClient.ts
- packages/core/src/client/ClientService.ts
Currently, newly created devices do not have the capability to work with clients under legal hold. 
We need to add this capability to newly created clients
> fix: Allow new created client to be legal hold ready

- packages/core/src/Account.ts
- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/conversationRejoinQueue.test.ts
- packages/core/src/messagingProtocols/mls/conversationRejoinQueue.ts
When we detect an epoch mismatch when handling the notification stream, we should avoid directly trying to rejoin the conversation. This could trigger some unexpected behavior. 
So we should first: 
- process the entire notification streams (we might even be able to decrypt some messages as there is a certain tolerance threshold for decrypting messages from future epochs)
- then rejoin the conversations that are on the wrong epoch.
> feat: Queue recovering MLS conversations on notification stream processing

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Storage/E2EIStorage.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
The `initialData` are always given when creating the `E2EIServiceInternal` instance. So no need to stored them in long term storage. 
This will avoid leaking user data in localStorage
> fix: Avoid storing unecessary enrollement data

- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/mls/types.ts
It's possible that a MLS group get stuck in state where it had a pending commit, which prevents any further operations to be performed in a that group. This PR allows a client to recover from that state by clearing all the pending commits and trying to commit them one more time.
> runfix: recover from commit proposals failure [WPB-6729]

- packages/api-client/src/team/search/TeamContact.ts
Nullable `email_unvalidated` field was missing in TeamContact's entity type definition.
> runfix(api-client): add missing email_unvalidated field to team contact

- packages/api-client/src/user/User.ts
According to swagger docs https://staging-nginz-https.zinfra.io/v5/api/swagger-ui/#/default/get_users__uid_domain___uid_ (and real-life response from backend), `email_unvalidated` does not exist on user entity. It appears on TeamContact though, see: https://github.com/wireapp/wire-web-packages/pull/5993
> runfix(api-client): remove unexisting field from user entity type

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.test.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
> fix: Pass parent conversation external senders to subconversation creation

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/Authorization.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/DpopChallenge/DpopChallenge.types.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Steps/OidcChallenge.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Storage/E2EIStorage.schema.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Storage/E2EIStorage.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/storage/CoreDB.ts
Will use indexedDB as storage for temporary e2ei enrollment flow. 
Since indexeddb is unique per user, this will ensure that no other user logged in on the same browser will share enrollment data
> fix: Use indexeddb to store e2ei enrollment temporary data

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/conversation/ConversationService/ConversationService.types.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
End user was not informed at all if adding a user to a conversation was not possible because of the lack of their keys on backend.
We're returning an array of failures currently. It was not a case for proteus as there was only one request needed to add all the users, so we ended up with one error message. With MLS we're claiming each user's keys separately, it's possible that we can have a different failure reason for each users. E.g one of them have not uploaded keys, the other one's backend is unreachable.
There are still federation error left to handle (this PR only covers non-uploaded keys on backend).
A webapp PR adapting failure reason as a list of failures will follow.
> runfix: system message keys claiming failure [WPB-6641]

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
We don't want to indicate that it was not possible to claim self user's keys when creating a group conversation.
> runfix: skip self user keys claiming failure

- packages/core/package.json
- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- yarn.lock
BREAKING CHANGE: enrolling to E2EI doesn't take an `oAuthToken` directly but rather a function that will be called when the token is needed. This makes the consumer not needing to be aware of the start/continuation of the flow (in case there is a redirect needed).
> refactor: lazily ask consumer for oAuth token

- packages/core/src/messagingProtocols/mls/MLSService/CoreCryptoMLSError.ts
We should ignore `StaleCommit`, `StaleProposal` and `DuplicateMessage` errors thrown by corecrypto when decrypting a message.
Error message is currently the only way we can differentiate between various corecrypto errors. Strings source: https://github.com/wireapp/core-crypto/blob/bc6f8e20ff45a883633490863bc98f423022969e/crypto/src/error.rs.
> runfix: add more corecrypto errors to be ignored [WPB-6451]

- packages/core/src/messagingProtocols/mls/EventHandler/events/welcomeMessage/welcomeMessage.test.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/welcomeMessage/welcomeMessage.ts
Emit a `newEpoch` event after processing a welcome message - this will notify a consumer about new (and their first) epoch in a MLS group.
> runfix: emit new epoch event for welcome message

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
`CoreCrypto.getUserIdentities` would fail when called if the group does not exist in the store anymore (e.g. after user has left it or got removed).
Before trying to call this method, we check if group exists, if it doesn't we return `undefined`.
> runfix: return undefined for user identities if group does not exist [WPB-6864]

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Helper/index.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Will make sure we will not try to upload a device public key after enrollment when an MLS device was already registered
> fix: Do not upload public key for registered MLS devices

- packages/core/package.json
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Connection/AcmeServer/AcmeService.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- yarn.lock
We should not try to eagerly fetch self CRLs. This can cause some problems (as the url we use to fetch them might not match the url set in the certificate). 
Instead we rely only on the new distribution point detection mechanism in place to update CRLs lazily.
> fix: strip https scheme from fetched self crls

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
We do not need to eagerly fetch the self crls anymore. They will be provided by CoreCrypto when the user enrolls to E2EI.
> fix: Rely on new distribution points to update CRL

- packages/api-client/src/http/HttpClient.ts
- packages/priority-queue/src/Config.ts
- packages/priority-queue/src/PriorityQueue.ts
Use a `PriorityQueue` with a built in retry mechanism with a growing delay between each request for backing off when 420 rate limit is hit.
> runfix: use priority queue with growing delay for 420 backoff

- packages/core/package.json
- yarn.lock
Will allow non-e2ei devices to join conversations with e2ei devices
(see https://github.com/wireapp/core-crypto/blob/develop/CHANGELOG.md#100-rc47---2024-03-04)
> fix: Address non-e2ei devices not being able to join conversations

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Improve mls message add handler error message when failed finding a group id for a conversation (**or a subconversation**).
> runfix: improve error logs

- packages/api-client/package.json
- packages/core/package.json
- yarn.lock
updating api-client to remove security warning (the dep in question is unused)
> fix(sec): update deps to silence warning

- packages/core/src/util/TaskScheduler/TaskScheduler.ts
We should check whether there's actually ongoing timer with given key, not just if the key is stored (not all the tasks use the built-in storage).
> runfix: check pending timeout in task scheduler

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/CoreCryptoMLSError.ts
When following corecrypto error is thrown, we should join the conversation with external commit:
`Although this Welcome seems valid, the local KeyPackage it references has already been deleted locally. Join this group with an external commit`
This is so called Orphan Welcome message, backend does not track claimed KeyPackages. Only way to recover is to rejoin with ext commit. 
This can happen when a client is being added to multiple mls groups at the same time.
> runfix: join with ext commit on welcome with deleted key

- packages/react-ui-kit/src/Icon/MLSVerified.tsx
- packages/react-ui-kit/src/Theme/GlobalCssVariables.tsx
- packages/react-ui-kit/src/Theme/Theme.tsx
Use theme value and its new `successColor` for MLSVerified icon's green color so it respects theme changes.
Before
After
> fix(react-ui-kit): mls verified icon color based on theme [WPB-6888]

- packages/react-ui-kit/src/Icon/CertificateExpired.tsx
- packages/react-ui-kit/src/Icon/CertificateRevoked.tsx
- packages/react-ui-kit/src/Icon/ExpiresSoon.tsx
Fixes mls verification status icons colors for dark theme. Basically a follow up to https://github.com/wireapp/wire-web-packages/pull/6084.
> fix: mls status dark theme icon colors [WPB-6888]

- packages/core/src/secretStore/secretKeyGenerator.ts
This will use `crypto.subtle.generateKey` instead of `crypto.randomBytes`
> fix: Improve database key generation

- packages/copy-config/package.json
`rimraf` is directly used by the package when installed and used by the consumer. 
We need to define it as such
> fix(copy-config): make rimraf production dependency

- packages/copy-config/src/CopyConfig.ts
- packages/copy-config/src/CopyConfigOptions.ts
- packages/copy-config/src/cli.ts
- packages/copy-config/src/utils.ts
This will allow the consumer to limit the verbosity of the copyConfig CLI tool. 
```text
ℹ️  @wireapp/copy-config Found configuration file "/Users/atomrc/Workspace/wire-webapp/.copyconfigrc.js".
ℹ️  @wireapp/copy-config Cloning "https://github.com/wireapp/wire-web-config-wire" (branch "master") ...
ℹ️  @wireapp/copy-config Resolving "/Users/atomrc/Workspace/wire-webapp/config/wire-webapp/content/**"
ℹ️  @wireapp/copy-config/CopyConfig Copying "/call_drop.mp3" -> "/call_drop.mp3"
ℹ️  @wireapp/copy-config/CopyConfig Copying "/Users/atomrc/Workspace/wire-webapp/config/wire-webapp/content/audio/call_drop.mp3" -> "/Users/atomrc/Workspace/wire-webapp/resource/audio/call_drop.mp3"
ℹ️  @wireapp/copy-config/CopyConfig Copying "/Users/atomrc/Workspace/wire-webapp/config/wire-webapp/content/audio/cam …
```
> fix(copy-config): allow configuring the log level

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/ClientMLSError.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Adds a separate method for registering a 1:1 conversation with a given user. When no keys of the user we want to create a 1:1 conversation with are available, we will throw an error which then can be handled by a consumer. For group conversations we keep the behaviour of creating an empty group by sending an empty commit (key packages update) if no keys are available, we don't want to do that for 1:1 conversations - backend requires a first commit sent in a MLS 1:1 conversation to add exactly one other user.
> runfix: separate method for registering mls 1:1 conversation

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
We were maintaining a boolean flag of whether the root CA was already registered or not. What could happen is: after the root cert is registered but before we've set the flag to true, the app crashes (or simply get closed). Then the client thinks that is still has not registered the root certificate, tries to do so, fails (CoreCrypto error is thrown) and the client is stuck on a loading screen.
The solution is to use CoreCrypto's `.e2eiIsPKIEnvSetup()` method that will return false if the root cert is not yet registered and rely on that. With a single source of truth (CoreCrypto) we're sure whether the root CA is registered (or not).
> runfix: root CA registered flag

- packages/core/__mocks__/@wireapp/core-crypto.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.test.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
Instead of an actual enum value, CoreCrypto returns us enum's key as a string for a `credentialType` value. Until the fix for that is included in the library, we are wrapping the value with a method that would map the received string to the actual enum value.
> runfix: fix credential type value

- packages/core/package.json
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- yarn.lock
CoreCrypto has fixed enums, so we can use the raw returned value, without need to map enum's key to an enum value.
> runfix: use fixed corecrypto enums

- packages/core/src/Account.ts
Since it's possible to init a non-MLS client in an MLS enabled env, there is no need to throw an error in case a client is init without an MLS configuration. 
Regression introduced with https://github.com/wireapp/wire-web-packages/pull/6168
> fix: Do not throw error when initClient is called without MLS config

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Helper/index.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/CoreCryptoWrapper.ts
Previous PR enabling dynamic ciphersuite selection missed one hardcoded ciphersuite when enrolling to the e2ei process
> fix: Pass the correct ciphersuite when starting the e2ei enrollment process

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
This will allow the consumer to know if an MLS device has been setup or not. 
This is to prevent trying to do MLS operations if the devices has not been initialized
> fix: Correctly detect if current device is MLS capable

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
We should not overwrite the consumer-provided MLS configuration by the default config, but rather use this config on top of the default config. This PR addresses that. We also make sure we filter out undefined values, in this case the default value will be used (consumer might want to set a value to `undefined` explicitly to make sure the default will be used).
> runfix: mls default config

- packages/core/package.json
- yarn.lock
Bumps CoreCrypto with version that fixes using different than default ciphersuite. Previously the param in createConversation and probably other methods was ignored by the library and was always using the first cert.
> runfix: bump cc with version that fixes multiple ciphersuites issue

- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
We should not listen for `newCrlDistributionPoints` event if e2ei feature is disabled. Instead of subscribing to an event when the service is initialised, we do that in the explicit `initialize` method call. 
We need the acme service to be initialised first anyway.
It will remove the unhandled console error:
> runfix: start listening for new crl points on e2ei service init

- archive/bot-api/package.json
- packages/api-client/package.json
- packages/core/package.json
- yarn.lock
This fixes the `protobufjs` security issue found by dependabot
> chore: upgrade @wireapp/protocol-messaging WPB-7240

- packages/eslint-config/package.json
- yarn.lock
`yarn lint` was causing:
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.4.0
YOUR TYPESCRIPT VERSION: 5.4.5
```
> chore: upgrade eslint-typescript dependencies WPB-7240

- archive/bot-api/package.json
- archive/bot-api/src/Bot.ts
- packages/core/package.json
- packages/core/src/Account.test.ts
- packages/core/src/conversation/AssetService/AssetService.test.ts
- packages/core/src/conversation/message/MessageBuilder.ts
- packages/core/src/conversation/message/MessageService.test.ts
- packages/core/src/test/PayloadHelper.ts
- packages/store-engine-dexie/package.json
- packages/store-engine-dexie/src/index.test.ts
- yarn.lock
Motivation: bump `uuidjs` from v 4.2.13 to v 5.1.0 causes problems with `jest` that are hard to resolve.
And since `uuid` has 103,276,467 weekly downloads vs `uuidjs` - 9,841, it makes sense to use `uuid`.
> fix: Replace `uuidjs` with `uuid` WPB-7240

- packages/react-ui-kit/src/Icon/CircleCloseIcon.tsx
The circle close icon has it's fill color hardcoded in a way it cannot be reassigned for dark mode.
After removing the hardcoded value, the component gets a correct value from its default `SVGIconProps` props that can be reassigned
before:
After:
> fix: remove hardcoded fill color for CircleCloseIcon

- packages/api-client/src/tcp/ReconnectingWebsocket.ts
- packages/api-client/src/tcp/WebSocketClient.ts
- packages/api-client/src/utils/BackFromSleepHandler/BackFromSleepHandler.test.ts
- packages/api-client/src/utils/BackFromSleepHandler/BackFromSleepHandler.ts
- packages/api-client/src/utils/BackFromSleepHandler/index.ts
Once we've realised that the app was (**probably**) sleeping and during the possible "sleep time" the socket was disconnected, we will immediately reconnect. This should fix the bug where after coming back from sleep mode, messages are not synced immediately.
> fix(api-client): socket reconnect after coming back from sleep

- packages/core/src/conversation/SubconversationService/SubconversationService.test.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.ts
We should respect backend's federation config when updating AVS with MLS call's epoch info.
> runfix: mls calls on non-fed env [WPB-9710]

- packages/react-ui-kit/src/Form/Select.md
- packages/react-ui-kit/src/Form/Select.tsx
- packages/react-ui-kit/src/Form/SelectStyles.tsx
There was an Issue where the selects is not able to being scrolled with very long lists.
Additionally it was also not being searchable.
This PR fixes both behaviours trough:
- setting a max height for the option-list to 400px
- add a parameter to activate the search feature, disabled by default
> fix(ui:select): make searchable and fix scroll behaviour

- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.ts
This will simplify the cryptobox to coreCrypto migration logs and add the time it took to migrate.
> fix: Improve coreCrypto migration logs

- packages/react-ui-kit/src/Layout/MatchMedia.tsx
Adds multi-window support for MatchMedia util. Useful when opening an external window (e.g. calling popout view).
> feat: allow match media to support external window

- packages/commons/src/util/Runtime.ts
To check if `RTCDataChannel's` are offered we creating `RTCPeerConnection` objects
Creating `RTCPeerConnection` objects leads to too many unnecessary ghost objects in the background that are not cleared away. This can potentially lead to errors in the app.
> fix: do not create an RTC object for check

- packages/api-client/src/user/data/UserPropertiesSetData.ts
This attribute should not be used anymore. So we remove it
> feat: remove improve_wire privacy attribute

- packages/api-client/src/client/ClientAPI.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
Backend requires a comma-separated ciphersuites as a query param when replacing mls key packages during the enrollment.
> fix: add ciphersuites param when replacing keys [WPB-10236]

- packages/api-client/src/team/feature/Feature.ts
New conference calling setting that allows to use sft server for 1:1 calls instead of peer-to-peer connection.
> feat: add flag for 1:1 sft calls

- yarn.lock
Latest dependabot PR got an auto merge conflict, the `yarn.lock` file is incorrect as a result.
This is just a push of the correct file
> chore: submit correct lockfile

- packages/api-client/CHANGELOG.md
- packages/api-client/package.json
- packages/copy-config/CHANGELOG.md
- packages/copy-config/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/eslint-config/CHANGELOG.md
- packages/eslint-config/package.json
- packages/react-ui-kit/CHANGELOG.md
- packages/react-ui-kit/package.json
This reverts commit dcbe8d6811804d1d0aa145633b5e760de5d8109d.
The latest publish commit didn't result in the packages actually being deployed on npm.
Using `fix` as the commit identifier will make sure the pipeline will publish the packages correctly (`chore` commits do not get published)
> fix: Revert "chore: Publish [skip ci]"

- packages/api-client/src/asset/AssetAPI.ts
- packages/api-client/src/http/HttpClient.ts
- packages/api-client/src/team/member/MemberAPI.ts
[WPB-10469](https://wearezeta.atlassian.net/browse/WPB-10469)
Removed `access_token` from query param and passed it through `Authorization` header.
**Explanation:**
On the ticket there are 4 files mentioned that require changes:
- https://github.com/wireapp/wire-web-packages/blob/e875aa251d9da0df0b7caa7ba066279fecf1f4d7/packages/api-client/src/team/member/MemberAPI.ts#L163
- https://github.com/wireapp/wire-web-packages/blob/e875aa251d9da0df0b7caa7ba066279fecf1f4d7/packages/api-client/src/tcp/WebSocketClient.ts#L226 There is no other way of passing access_token. Additionally, we may not be seeing the URL in logs.
- https://github.com/wireapp/wire-webapp/blob/b89a390c78f4ba604d93b504b581104ac9adf548/src/script/assets/AssetService.ts#L30-L64
Already removed in this PR: …
> fix: use of Auth header to pass access-token instead of query param

- packages/api-client/src/user/data/UserPropertiesSetData.ts
error_reporting is gone and should not be used anymore.
Added marketing_consent to have all privacy-related options, that a user has to give consent to, in one place.
> feat: replace error_reporting with marketing_consent [WPB-10506]

- packages/api-client/src/conversation/Conversation.ts
- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/NewConversation.ts
- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
See https://wearezeta.atlassian.net/browse/WPB-10737 for a more in depth description of the issue.
In a nutshell, it's possible for a federated user to create a 1:1 conversation even if it's not hosted on their own backend, in which case it can introduce a host of issues because they're lacking the correct removal key.
to address that issue, the response from the endpoint `GET /conversations/one2one/{domain}/{userId}` was changed to include that removal key, from
```
{ <conversation metadata> }
```
to
```
{
"conversation": { <conversation metadata> },
"public_keys": {
"removal": {
"<sig-algo>": "string",
...
}
}
}
```
> feat: establish 1on1 mls conversation with new removal key [WPB-10744]

- packages/react-ui-kit/src/Form/Input.md
- packages/react-ui-kit/src/Form/Input.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Input.test.tsx.snap
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
- packages/react-ui-kit/src/Theme/GlobalCssVariables.tsx
- packages/react-ui-kit/src/Theme/Theme.tsx
- packages/react-ui-kit/styleguide.config.js
https://wearezeta.atlassian.net/browse/WPB-9764
We have a problem with autocomplete styles. In the task there's an example of it:
On the screen above, you almost can't see the "show password" (eye icon) button. This is because the browser injects its own styles for the autocomplete (in this case, a yellow background).
The yellow background isn't always there, e.g. I have a nice blue color in my Chrome browser:
But it doesn't look good in the dark mode:
---
To unify the experience, we could set our background when the user uses the autocomplete browser feature. I did exactly this in this PR. 
Light mode:
https://github.com/user-attachments/assets/5aa057be-8ba8-47d4-9886-5333567c41de
Dark mode:
https://github.com/user-attachments/assets/981fe061-b24e-4ece-9859-f99fdcb4289d
I've tested it in …
> fix(react-ui-kit): input autocomplete background color [WPB-9764]

- packages/api-client/src/team/invitation/TeamInvitation.ts
Added property created_by_email in TeamInvitation (info) type.
BE PR refferrence: https://github.com/wireapp/wire-server/pull/4332
> feat(team-inv-info): add created_by_email in TeamInvitation type [WPB-12142]

- packages/telemetry/package.json
Due to failing first release of the telemetry package, changing the version to be `0.0.0`, maybe then the CI will know that there's no package like that in the registry yet.
https://github.com/wireapp/wire-web-packages/actions/runs/11797832352/job/32862666948
> fix(telemetry): version

- packages/react-ui-kit/src/Form/Tooltip.tsx
Long words in the tooltip should break onto new lines
> fix(react-ui-kit): fix content inside tooltip [WPB-11596]

- packages/react-ui-kit/src/Form/InputLabel.tsx
- packages/react-ui-kit/src/Form/__snapshots__/RangeInput.test.tsx.snap
Fixed input label spacing.
Fixed:
Bug:
> fix: updated input label spacing

- .github/dependabot.yml
- yarn.lock
Latest Typescript update broke our pipeline see documented issue [here](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#typedarrays-are-now-generic-over-arraybufferlike)
Upgrading @types/node does't solve the issue for us
This reverts the Typescript bump, and prevents dependabot updates of Typescript for mnor and major versions
> chore(dependabot): freeze dependabot typescript updates

- packages/api-client/src/APIClient.test.ts
- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/user/UserAPI.ts
Slashes are hardcoded into some of the url constants in the conversation and user api;
This remove those slashes, allowing us to use those constant where the API endpoints change the order around, as is the case for V&, see https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/1309868033/API+changes+v6+v7
> runfix: remove slashes from conversation and user api constants

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
a missing slash in the ONE_2_ONE endpoint was still missing after last refactor
> runfix: add missing slash to conversation endpoint

- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/util/RecurringTaskScheduler/RecurringTaskScheduler.ts
We should check key packages not just every 24h, but also when the app comes back in focus. 
Since our key-packages are generalized and should not require a browser environment to be executed, this feature requires the "browser api" check and is only executed inside of a browser env.
> feat: add periodic keypackages check and logging [WPB-14727]

- archive/bot-api/src/MessageHandler.ts
- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
The endpoint using a `string` as user id is deprecated in v7 and replaced by an endpoint that accepts `QualifiedId` only, see https://staging-nginz-https.zinfra.io/v4/api/swagger-ui/#/default/update-other-member
> feat(api-client/core): use v7 endpoint for setting member conversation roles [WPB-15024]

- archive/bot-api/src/MessageHandler.ts
- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
The new endpoint also requires the conversation's domain
https://staging-nginz-https.zinfra.io/v4/api/swagger-ui/#/default/update-other-member
> runfix(api-client/core): use conversation's qualified id to set conversation role [WPB-15024]

- .husky/pre-commit
- packages/copy-config/src/utils.ts
- packages/core/package.json
- yarn.lock
- Update of CC to the latest version
- Fix for lint staged:
> I ran into an issue where lint-staged started with npx and got no access to my workspace, and the prettier + eslint commands that write files failed. Change to yarn (which we use anyways) fixed that.
- copy-config fix
> It had a type mismatch, which led to the package not being able to be built.
> feat: update CC to new version

- packages/react-ui-kit/src/Form/Input.tsx
eye icon for passwords should work vice verse the current behavior.
> fix(react-ui-kit): Adjust the behavior of eye icon on password input (WPB-15930)

- packages/react-ui-kit/src/Icon/AlertIcon.tsx
- packages/react-ui-kit/src/Icon/index.ts
> feat(react-ui-kit): alert icon [WPB-15703]

- packages/core/src/messagingProtocols/mls/MLSService/CoreCryptoMLSError.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
We need to swallow another CoreCrypto error, which currently throws an error.
> feat(mls): add mlsOtherError to error ignore list [WPB-16234]

- packages/commons/src/util/StringUtil.test.ts
- packages/commons/src/util/StringUtil.ts
JSON.stringify throws an Error while stringifying large objects due to memory constraints.
> fix: issue with stringifying very large objects

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- packages/api-client/src/cells/CellsStorage/CellsStorage.ts
- packages/api-client/src/cells/CellsStorage/S3Service.test.ts
- packages/api-client/src/cells/CellsStorage/S3Service.ts
Added the `path` parameter to the `getAllFiles` method in the cells API + rename parameters (`filePath` => `path`) and replace one param with an object.
> feat(api-client/cells): add path parameter for getAllFiles method

- packages/react-ui-kit/src/Form/SelectComponents.tsx
The function isGroup was used as a boolean, always returning true. Used it as a function and passed options
> fix: use isGroup as a function and pass options

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
Replaces the `path` parameter with the `uuid` for the `deleteFile` cells method.
> feat(api-client/cells): replace path with uuid in the deleteFile method

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- introduced the `getFilePublicLink` method to retrieve public links for files.
- updated createFilePublicLink to handle optional label and removed `alreadyShared` parameter.
- enhanced test cases for both methods, including error handling for invalid UUIDs
> feat(api-client/cells): add createFilePublicLink method and refactor getFilePublicLink [WPB-15679]

- packages/api-client/src/APIClient.ts
- packages/api-client/src/Config.ts
- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- packages/api-client/src/demo/initClient.ts
We need to change how we configure Cells in the web application. Currently, the config is static (just an API key), but we have to make it dynamic, based on the current user data.
> feat(api-client/cells): dynamic cells configuration [WPB-16524]

- packages/api-client/src/APIClient.ts
- packages/api-client/src/cells/CellsAPI.ts
I have found that CellsApi is initialing multiple times which was causing configuration errors since we configure it not in the constructor, but via the function (https://github.com/wireapp/wire-web-packages/pull/6987)
To fix this issue, we have to make sure CellsApi is initialized only once.
> fix(api-client/cells): single cells initialization

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
Adds configurable "limit" and "offset" options for the `searchFiles` and `getAllFiles` options.
> feat(api-client/cells): add "offset" and "limit" configuration [WPB-15679]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- packages/api-client/src/cells/CellsStorage/CellsStorage.ts
- packages/api-client/src/cells/CellsStorage/S3Service.test.ts
- packages/api-client/src/cells/CellsStorage/S3Service.ts
Change the AWS `leavePartsOnError` setting to `false` + switch `signal` to the abort controller.
> fix(api-client/cells): change leavePartsOnError to false in S3Service [WPB-16843]

- packages/api-client/package.json
- yarn.lock
Upgrades the `cells-sdk-ts` to v0.1.1-alpha09.
Release changes: [Wire Cells - Pydio SDK Versions - Release Notes](https://wearezeta.atlassian.net/wiki/spaces/PAD/pages/1701838852/Wire+Cells+-+Pydio+SDK+Versions+-+Release+Notes)
> feat(api-client): upgrade cells-sdk-ts to v0.1.1-alpha09 [WPB-17111]

- packages/core/src/Account.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.test.ts
- packages/core/src/conversation/SubconversationService/SubconversationService.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceExternal.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/Helper/index.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.test.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/welcomeMessage/welcomeMessage.test.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/welcomeMessage/welcomeMessage.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.test.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/identityClearer.ts
There is an issue where our existing RegisteredClient and the CryptoClient no longer have matching signatures. This makes the client unusable for MLS purposes.
- This PR adds a check to the client initialisation that ensures that the Registered Client and the Crypto clients have matching signatures and emits an even in case they don't.
- This PR adds a possibility to wipe only the cryptographic database and the stored SelfClient while processing a logout action
- - Wiping only this data ensures that the message history of the user stays intact
- This PR refactors the Event propagation of the MLSService.ts
The event handling will be part of the webapp repository.
> feat(mls): detect a client mismatch and emit an specific event [WPB-16934]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
Add sorting to searchFiles() method, defaulting to "mtime/descending". 
[WPB-16997] This is linked to Pagination to make sure "Load More" returns consistent results.
[WPB-16997]: https://wearezeta.atlassian.net/browse/WPB-16997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(CellsAPI): add sorting parameters to searchFiles() method

- packages/react-ui-kit/src/Form/SelectStyles.tsx
- packages/react-ui-kit/src/Form/__snapshots__/Select.test.tsx.snap
**The problem:**
The select styles were available during local development but disappeared when deployed (e.g. on edge). 
Select was adjusting styles based on the control class, which had a different name after bundling than the hardcoded one in the UI kit package.
**The solution:**
Remove the hardcoded solution, and base it on the control function styles, provided by the react-select.
It's been tested on TM and Webapp, and looks good.
> fix(react-ui-kit/select): control styles [WPB-16997]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
Adds sort options to the `getAllFiles` method, similarly to `searchFiles` in https://github.com/wireapp/wire-web-packages/pull/7018 + adds tests for the `searchFiles` method.
> feat(api-client/cells): getAllFiles sorting [WPB-17384]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- packages/core/package.json
Removing the type "leaf" filter from the search query, since we're introducing folders and want to display both of these types in the search view.
> feat(api-client/cells): remove type filter from search [WPB-17388]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
Adds createFile and createFolder methods to the CellsAPI.
> feat(api-client/cells): createFile & createFolder [WPB-17571]

- packages/core/src/Account.ts
- packages/core/src/client/ClientService.ts
Since https://github.com/wireapp/wire-web-packages/pull/7007 , we attempts to delete the local client from the backend on logout.
this fails and prevents the local database from being deleted
> fix(core): allow database deletion on logout [WPB-17316]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- renames getAllFiles => getAllNodes
- renames searchFiles => searchNodes
- adds the `type` param to specify which node type to fetch
> feat(api-client/cells): add type param for getting nodes [WPB-17386]

- packages/api-client/src/http/HttpClient.ts
version prefix is still present for the remaining `/access` endpoints and needs to be removed
> fix(api-client): remove version prefix for all access endpoints [SECC-641]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
1. Add `permanently` option to the `deleteNode` method
2. Add `restoreNode` method
3. Rename existing methods to contain "node" instead of "file"
> feat(api-client/cell): permanent delete + restore + rename methods [WPB-17716]

- packages/core/package.json
- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/E2EIdentityService/E2EIServiceInternal.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/CoreCryptoWrapper.ts
- packages/core/src/secretStore/secretKeyGenerator.ts
- yarn.lock
The new CC version includes a breaking change for us regarding the Database Key. The format changes from 128 to 256-bit key length. Additionally, the library introduced its Key type. 
To make this work, we have to run a database migration for existing clients (only once).
To achieve this goal, we generate a new encryption key and store it in our database next to the existing one.
Following cases exist:
1. If the old key exists and the new key is freshly generated -> We run the migration, delete the old key and return the new key
2. If the old key is freshly generated and the new key is freshly generated -> We return the new key
3. If the old key is freshly generated and the new key exists -> We return the new key
> feat!: CC bump to 6. 

- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
When we don't have a established connection to a MLS conversation we add our current self client with an external commit then we should try to add our other clients as well and for this to work we need to filter whatever client we already have in the conversation otherwise core crypto will throw an error.
MlsErrorOther: Duplicate signature key in proposals and group
> fix(core): MLS - Filter already exisiting client ids when trying trying to add users to MLS conversation (WPB-17095)

- packages/react-ui-kit/src/Form/Select/ComboboxSelect/ComboboxSelect.stories.tsx
- packages/react-ui-kit/src/Form/Select/ComboboxSelect/ComboboxSelect.styles.ts
- packages/react-ui-kit/src/Form/Select/ComboboxSelect/ComboboxSelect.tsx
Add loading variant to the `ComboboxSelect` component.
> feat(react-ui-kit/combobox-select): loading [WPB-17810]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
Adds a tags filter for the `searchNodes` cells method.
> feat(api-client/cells): filter by tags in searchNodes [WPB-17818]

- packages/core/src/Account.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
This pull request introduces critical updates to enhance error handling and ensure proper initialization in the `Account` and `ConversationService` classes. The changes address potential issues with client state and backend calls, improving system reliability.
* **`Account` class (`packages/core/src/Account.ts`)**:
- Added a step to wipe the existing Proteus client before creating a new one. This prevents the reuse of an existing identity, which could lead to an unrecoverable state for the user.
* **`ConversationService` class (`packages/core/src/conversation/ConversationService/ConversationService.ts`)**:
- Introduced a validation to ensure `keyPackages` is not empty before calling `core-crypto` to add users to an existing conversation. This avoids backend failures caused by invalid …
> fix(CC): unrecoverable client error and avoiding unnecessary backend calls

- packages/core/src/Account.ts
- packages/core/src/conversation/ConversationService/ConversationService.test.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/CoreCryptoWrapper.ts
This pull request includes updates to enhance the handling of cryptographic data, improve error recovery, and fix issues in conversation service workflows. Key changes include introducing a new utility for wiping the CoreCrypto database, modifying cryptographic client initialization to handle errors more robustly, and refactoring conversation-related logic for better reliability.
* Added a utility function `wipeCoreCryptoDb` to encapsulate logic for wiping the CoreCrypto database, improving code reuse and error handling. (`packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/CoreCryptoWrapper.ts`, [packages/core/src/messagingProtocols/proteus/ProteusService/CryptoClient/CoreCryptoWrapper/CoreCryptoWrapper.tsR116-R131](diffhunk://#diff-bd3d3c86e95bb9a86 …
> fix(cc): make sure to delete the cc database when wiping data

- packages/api-client/src/conversation/Conversation.ts
- packages/core/src/messagingProtocols/proteus/ProteusService/ProteusService.test.ts
Add `cells_state` field in the `Conversation` type - [documentation](https://wearezeta.atlassian.net/wiki/spaces/PAD/pages/1800962144/2025-03-19+Wire+Cells+implementation+in+wire-server).
> feat(api-client/conversation): add cells_state type field [WPB-18135]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
Removes default sorting from `getAllNodes` and `searchNodes` methods.
> feat(api-client/cells): remove default sorting [WPB-17387]

- packages/core/src/messagingProtocols/mls/EventHandler/events/welcomeMessage/welcomeMessage.test.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/welcomeMessage/welcomeMessage.ts
- packages/core/src/messagingProtocols/mls/MLSService/MLSService.ts
This pull request enhances the handling of MLS (Messaging Layer Security) group join events by introducing additional logging and event notifications. The changes improve observability and ensure that the system is informed when a new epoch begins after joining a group.
* **Emit `NEW_EPOCH` event upon joining a group via welcome message**: added logging when a new group is joined via a welcome message, providing better visibility into group state changes. (`packages/core/src/messagingProtocols/mls/EventHandler/events/welcomeMessage/welcomeMessage.ts`, [packages/core/src/messagingProtocols/mls/EventHandler/events/welcomeMessage/welcomeMessage.tsR45-R48](diffhunk://#diff-d3b00a8e97ae3002de697ff37f7b040bcaf2c00a3180dda38ae38c21d01f25b2R45-R48))
* **Emit `NEW_EPOCH` event upon joining a group …
> fix(MLS): emit epoch change for conversations we join [WPB-18371]

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
Fix passing tags to the `searchNodes` cells method.
> fix(api-client/cells): searchNodes tags

- packages/core/src/Account.ts
web socket processing queue must be flushed when disconnect function is called in order to avoid duplicate decryption
> fix(core): Pause and flush notification queue on disconnect call [WPB-18486]

- packages/core/src/Account.ts
- packages/core/src/notification/NotificationService.ts
we're not supposed to call /notifications/last once we switched to consumable-notifications
> fix(core): Do not call /notifications/last once switched to consumable-notifications

- packages/api-client/src/cells/CellsAPI.test.ts
- packages/api-client/src/cells/CellsAPI.ts
- packages/api-client/src/cells/CellsStorage/S3Service.test.ts
- packages/api-client/src/cells/CellsStorage/S3Service.ts
Fixes getting a fresh refresh token for the cells' S3 service.
> fix(api-client/cells): s3 fresh access token [WPB-18596]

- packages/core/src/Account.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/IncomingProposalsQueue/IncomingProposalsQueue.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/IncomingProposalsQueue/index.ts
- packages/core/src/messagingProtocols/mls/EventHandler/events/messageAdd/messageAdd.ts
Problem:
On web pending proposals which arrive during the incremental sync are committed immediately before the sync is completed. This is very wasteful and. leads to large amount of errors, since the the requests often will fail with  409 conflict since the proposal has already been committed by someone else.
This is sometimes causing very long decryption time or making the app freeze during initial startup.
Solution:
Commit any still remaining pending proposals after the incremental sync is complete.
> fix(core): Queue incoming pending MLS proposals [WPB-18995]

- packages/api-client/package.json
- yarn.lock
This pull request updates the dependency version for `cells-sdk-ts` in the `packages/api-client/package.json` file. The version has been changed from a GitHub reference (`https://github.com/pydio/cells-sdk-ts#v0.1.1-alpha12`) to a direct version reference (`0.1.1-alpha14`).
> feat: use published npm pkg for cells-sdk-ts [WPB-18944]

- packages/api-client/src/team/feature/Feature.ts
- packages/api-client/src/team/feature/FeatureAPI.ts
- packages/api-client/src/team/feature/FeatureList.ts
Expose the Cells `enabled` and `locked` status to the feature config API to be able to use it in the `teamState` observables
> feat(cells): expose cells config to the team feature API [WPB-19293]

- packages/api-client/src/conversation/ConversationAPI/ConversationAPI.ts
- packages/api-client/src/conversation/data/ConversationMLSResetData.ts
- packages/api-client/src/event/ConversationEvent.ts
- packages/api-client/src/http/BackendErrorLabel.ts
- packages/core/src/conversation/ConversationService/ConversationService.ts
Support for mls reset conversation event & added the implementation of the endpoint needed to trigger a reset on the backend.
> feat(api-client): Support for reset MLS event [WPB-17706]

- package.json
- yarn.lock
This reverts commit 0424d396109d8f35533d594683d35ffc2c817079.
This Dependabot merge s causing a [lockfile issue](https://github.com/wireapp/wire-web-packages/actions/runs/17022165600/job/48252732100)
> chore: Revert "chore(deps-dev): bump @lerna-lite/publish from 4.7.0 to 4.7.2"

- packages/api-client/src/user/data/UserDeleteData.ts
the `user.delete` backend event returns a qualified id, required to handle deleted users in 1:1 conversations.
> fix(events): add qualified_id to UserDeleteData type [WPB-18869]

- packages/api-client/src/http/BackendErrorMapper.test.ts
- packages/api-client/src/http/BackendErrorMapper.ts
This PR addresses an issue where sharing the same cookie across multiple tabs/users caused inconsistent session handling.
When two different users share the same cookie, the session gets invalidated.
The access token remains valid, so the site continues to appear responsive.
After 15 minutes when the access token expires(/access JSON response expires_in: 900), the invalid user stays logged in but the console is flooded with 403 errors.
This happened due to incorrect error mapping, which prevented a proper logout flow.
Corrected error mapping for 403 responses tied to invalid sessions.
Ensured that doLogout is triggered when session invalidation is detected.
Prevents flooding of 403 errors after access token expiry.
Provides a smoother and more consistent logout experience.
> fix: Handle expired token gracefully(WPB-19368)

- packages/core/src/Account.ts
- packages/promise-queue/src/PromiseQueue.ts
createEventHandler is not doing any async operations at all so it shouldn't be an async function
> refactor(core, promise-queue): Turn listen method event handler to a sync function [WPB-18813]

- packages/api-client/src/http/BackendErrorMapper.test.ts
- packages/api-client/src/http/BackendErrorMapper.ts
- packages/api-client/src/http/HttpClient.ts
- replaced pre-built error instances with handler functions
- ensures each backend error maps to a new object with actual code/label
- added label-level default handlers as fallback when message does not match
- prevents user sessions getting stuck on unmapped messages (e.g. token errors)
Our previous BackendErrorMapper relied on message strings and stored pre-built error instances. This caused two problems:
Stuck loading: if the backend sent an unmapped message (same label, different text), the mapper returned a raw BackendError, so refresh/logout flows didn’t trigger.
Reused instances: the same Error object was returned repeatedly, losing the actual backend code/label and risking stale stack traces.
Introduced handler functions ((e: BackendError) => new …Error(...)) for each mapping, so …
> fix: create fresh error instances via handler functions in BackendErrorMapper and add fallback for unknown messages(WPB-19061)

- packages/react-ui-kit/src/DataDisplay/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- packages/react-ui-kit/src/Inputs/ButtonGroup/ButtonGroup.tsx
Update the interface GroupButtonProps so that it can inherit all the native options of HTM Button Element
> feat: update GroupButtonProps interface [WPB-20282] 

- packages/api-client/src/tcp/WebSocketClient.ts
- packages/core/src/Account.ts
When these logs are added we can create charts on datadog to see number of migrations to async notification system and the calls to legacy vs async
> chore: Add logs for migration to async notifications [WPB-19981]
